import { PlayerDossier } from './playerDossier';

export const CENTRAL_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // CHICAGO BULLS (CHI)
  // ==========================================
  'Josh Giddey': {
    tacticalRole: 'Base Organizador Alto & Creador de Juego de Élite',
    specialty: 'Visión de pase panorámica, pases picados imposibles, rebote ofensivo y control del ritmo',
    playStyle: 'Base puro de 2,03m con instinto anotador y capacidad constante de triple-doble',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 6,
      teamName: 'Oklahoma City Thunder',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Adelaide 36ers (Australia / NBL)',
    },
    draft: '2021 · Pick #6 (1ª Ronda por Oklahoma City Thunder)',
    experience: '4 Temporadas (Thunder / Bulls)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Adelaide 36ers',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '27,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 6 — Contrato Rookie)',
      },
      {
        season: '24/25',
        date: '21/06/2024',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '35,00 mill. $',
        feeOrType: 'Traspaso Directo (por Alex Caruso)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Jugador Más Joven en la Historia en Lograr un Triple-Doble', count: 1, details: '19 años y 84 días' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2022' },
      { icon: 'ribbon', name: '4x Rookie del Mes de la Conferencia Oeste', count: 4, details: 'Nov, Dic, Ene, Feb 2021-22' },
      { icon: 'medal', name: 'Estrella de la Selección de Australia (Boomers)', count: 1, details: 'Juegos Olímpicos París 2024 / Mundial FIBA 2023' },
    ],
    seasonAverages: {
      pts: '14.2',
      reb: '7.8',
      ast: '7.2',
      stl: '1.0',
      blk: '0.6',
      fgPct: '47.5%',
      threePct: '36.8%',
      ftPct: '81.2%',
    },
  },

  'Norman Powell': {
    tacticalRole: 'Escolta Anotador Explosivo & Campeón de la NBA (Stormin Norman)',
    specialty: 'Penetraciones contundentes al aro, tiro tras recepción de tres puntos y anotación en rachas',
    playStyle: 'Anotador implacable con experiencia de campeonato y amenaza perimetral constante',
    draftInfo: {
      year: 2015,
      round: 2,
      pick: 46,
      teamName: 'Milwaukee Bucks (Traspasado a Raptors)',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'UCLA Bruins',
    },
    draft: '2015 · Pick #46 (2ª Ronda por Milwaukee Bucks)',
    experience: '10 Temporadas (Raptors / Trail Blazers / Clippers / Bulls)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'UCLA Bruins',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '2,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 46 / Traspasado con 1ª ronda 2017 por Greivis Vásquez)',
      },
      {
        season: '20/21',
        date: '25/03/2021',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '42,00 mill. $',
        feeOrType: 'Traspaso (por Gary Trent Jr. + Rodney Hood)',
      },
      {
        season: '21/22',
        date: '04/02/2022',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Traspaso (junto a Robert Covington por Eric Bledsoe + Justise Winslow + Keon Johnson)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '38,00 mill. $',
        feeOrType: 'Traspaso de Veterano Anotador',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2019 (Toronto Raptors)' },
      { icon: 'sparkles', name: 'Rookie del Mes de la Conferencia Este', count: 1, details: 'Abril 2016' },
      { icon: 'flame', name: '1er Equipo All-Pac-12', count: 1, details: '2015 (UCLA)' },
    ],
    seasonAverages: {
      pts: '16.8',
      reb: '3.1',
      ast: '2.0',
      stl: '0.8',
      blk: '0.3',
      fgPct: '48.6%',
      threePct: '42.4%',
      ftPct: '83.9%',
    },
  },

  'Nic Claxton': {
    tacticalRole: 'Pívot Protector de Aro & Especialista Defensivo Móvil',
    specialty: 'Tapones en ayuda, cambio en bloqueos directos sobre bases, alley-oops y rebote',
    playStyle: 'Pívot defensivo hiperactivo de élite y ancla de la pintura',
    draftInfo: {
      year: 2019,
      round: 2,
      pick: 31,
      teamName: 'Brooklyn Nets',
      teamAbbr: 'BKN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
      origin: 'Georgia Bulldogs',
    },
    draft: '2019 · Pick #31 (2ª Ronda por Brooklyn Nets)',
    experience: '6 Temporadas (Nets / Bulls)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Georgia Bulldogs',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '4,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 31)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Renovación y Traspaso de Franquicia (4 años / $100M)',
      },
    ],
    awards: [
      { icon: 'shield', name: '2º Máximo Taponador de la NBA', count: 1, details: '2022-23 (2.5 tapones por partido)' },
      { icon: 'flame', name: 'Líder en Porcentaje de Tiros de Campo de la NBA', count: 1, details: '2022-23 (70.5% FG)' },
      { icon: 'shield-checkmark', name: 'Candidato a Defensor del Año de la NBA (DPOY Top 5)', count: 1, details: '2023' },
    ],
    seasonAverages: {
      pts: '12.8',
      reb: '10.2',
      ast: '2.1',
      stl: '0.7',
      blk: '2.2',
      fgPct: '64.5%',
      threePct: '0.0%',
      ftPct: '57.8%',
    },
  },

  'Matas Buzelis': {
    tacticalRole: 'Alero Moderno Versátil & Futura Estrella de Chicago',
    specialty: 'Manejo de balón para su altura (2,08m), tapones atléticos en transición y tiro exterior',
    playStyle: 'Alero todoterreno con mentalidad competitiva implacable y techo ilimitado',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 11,
      teamName: 'Chicago Bulls',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'G League Ignite / Lituania & Chicago',
    },
    draft: '2024 · Pick #11 (1ª Ronda por Chicago Bulls)',
    experience: '2 Temporadas (Chicago Bulls)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'G League Ignite',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '23,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 11 — Contrato Escala Rookie 4 años)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'McDonald\'s All-American Game', count: 1, details: '2023' },
      { icon: 'ribbon', name: 'Jordan Brand Classic', count: 1, details: '2023' },
      { icon: 'star', name: 'Rising Stars Challenge Participant', count: 1, details: '2024 (NBA All-Star Weekend)' },
    ],
    seasonAverages: {
      pts: '12.5',
      reb: '5.2',
      ast: '2.0',
      stl: '0.9',
      blk: '1.4',
      fgPct: '45.2%',
      threePct: '35.8%',
      ftPct: '78.5%',
    },
  },

  'Tre Jones': {
    tacticalRole: 'Base Director Tradicional & Especialista en Cuidado de Balón',
    specialty: 'Ratio asistencias/pérdidas de élite, defensa perimetral intensa y flotadoras',
    playStyle: 'Base cerebral y seguro con gran disciplina táctica',
    draftInfo: {
      year: 2020,
      round: 2,
      pick: 41,
      teamName: 'San Antonio Spurs',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'Duke Blue Devils',
    },
    draft: '2020 · Pick #41 (2ª Ronda por San Antonio Spurs)',
    experience: '5 Temporadas (Spurs / Bulls)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '4,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 41)',
      },
      {
        season: '24/25',
        date: '05/07/2024',
        fromTeam: 'San Antonio Spurs',
        fromTeamAbbr: 'SAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '20,00 mill. $',
        feeOrType: 'Traspaso de Base Organizador',
      },
    ],
    awards: [
      { icon: 'shield', name: 'Jugador Defensivo del Año ACC & Jugador del Año ACC', count: 1, details: '2020 (Duke)' },
      { icon: 'albums', name: '2º Equipo All-American', count: 1, details: '2020' },
    ],
    seasonAverages: {
      pts: '10.0',
      reb: '3.8',
      ast: '6.2',
      stl: '1.1',
      blk: '0.1',
      fgPct: '50.5%',
      threePct: '33.5%',
      ftPct: '85.6%',
    },
  },

  'Guerschon Yabusele': {
    tacticalRole: 'Ala-Pívot Físico & Héroe Olímpico Francés (The Dancing Bear)',
    specialty: 'Potencia bajo el aro, tiro exterior fiable tras bloqueo, físico imparable y garra competitiva',
    playStyle: 'Ala-pívot moderno potente con experiencia dorada en Europa y subcampeón olímpico',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 16,
      teamName: 'Boston Celtics',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Rouen Métropole / Francia',
    },
    draft: '2016 · Pick #16 (1ª Ronda por Boston Celtics)',
    experience: '4 Temporadas NBA + 5 en Europa (Celtics / Real Madrid / Bulls)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Rouen Métropole',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '12,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 16)',
      },
      {
        season: '21/22',
        date: '12/07/2021',
        fromTeam: 'ASVEL Lyon-Villeurbanne',
        toTeam: 'Real Madrid Baloncesto',
        toTeamAbbr: 'RMB',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '6,00 mill. $',
        feeOrType: 'Fichaje Estrella Europeo',
      },
      {
        season: '24/25',
        date: '18/08/2024',
        fromTeam: 'Real Madrid Baloncesto',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '5,00 mill. $',
        feeOrType: 'Regreso Triunfal a la NBA tras Juegos Olímpicos París 2024',
      },
    ],
    awards: [
      { icon: 'medal', name: '2x Medalla de Plata Olímpica (Francia)', count: 2, details: 'Tokio 2020, París 2024 (Mate histórico sobre LeBron James)' },
      { icon: 'trophy', name: 'Campeón de la Euroliga', count: 1, details: '2023 (Real Madrid)' },
      { icon: 'trophy', name: '2x Campeón de la Liga ACB', count: 2, details: '2022, 2024 (Real Madrid)' },
    ],
    seasonAverages: {
      pts: '11.0',
      reb: '5.6',
      ast: '1.9',
      stl: '0.8',
      blk: '0.5',
      fgPct: '49.8%',
      threePct: '40.2%',
      ftPct: '82.0%',
    },
  },

  'Zach Collins': {
    tacticalRole: 'Pívot Físico con Tiro Exterior & Dureza en Pintura',
    specialty: 'Juego en pick-and-pop, tapones intimidatorios y pase desde el poste alto',
    playStyle: 'Pívot versátil con tiro abierto y presencia defensiva física',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 10,
      teamName: 'Sacramento Kings (Traspasado a Blazers)',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'Gonzaga Bulldogs',
    },
    draft: '2017 · Pick #10 (1ª Ronda por Sacramento Kings)',
    experience: '7 Temporadas (Blazers / Spurs / Bulls)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Gonzaga Bulldogs',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '16,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10)',
      },
      {
        season: '24/25',
        date: '07/07/2024',
        fromTeam: 'San Antonio Spurs',
        fromTeamAbbr: 'SAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '35,00 mill. $',
        feeOrType: 'Traspaso de Pívot Veterano',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Final Four de la NCAA', count: 1, details: '2017 (Gonzaga Bulldogs)' },
      { icon: 'shield-checkmark', name: 'WCC All-Freshman Team', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '11.2',
      reb: '5.4',
      ast: '2.8',
      stl: '0.5',
      blk: '0.8',
      fgPct: '48.4%',
      threePct: '32.0%',
      ftPct: '78.5%',
    },
  },

  'Rob Dillingham': {
    tacticalRole: 'Base Anotador Eléctrico & Virtuoso del Uno Contra Uno',
    specialty: 'Manejo de balón supersónico, creación de tiro en step-back y cambios de ritmo demoledores',
    playStyle: 'Microondas ofensivo de puro talento anotador generacional',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 8,
      teamName: 'San Antonio Spurs (Traspasado a Timberwolves/Bulls)',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2024 · Pick #8 (1ª Ronda por San Antonio Spurs)',
    experience: '2 Temporadas (Timberwolves / Bulls)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '28,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 8 — Traspaso en Noche de Draft)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Mejor Sexto Hombre de la SEC', count: 1, details: '2024 (Kentucky)' },
      { icon: 'ribbon', name: 'SEC All-Freshman Team', count: 1, details: '2024' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-16 Américas', count: 1, details: '2021 (MVP del Torneo)' },
    ],
    seasonAverages: {
      pts: '11.8',
      reb: '2.1',
      ast: '3.9',
      stl: '0.8',
      blk: '0.1',
      fgPct: '44.0%',
      threePct: '38.2%',
      ftPct: '82.5%',
    },
  },

  'Mac McClung': {
    tacticalRole: 'Combo Guard Aéreo & 2x Campeón del Torneo de Mates NBA',
    specialty: 'Salto vertical descomunal (1,10m+), mates históricos en suspensión y anotación en carrera',
    playStyle: 'Fenómeno viral y uno de los mejores machacadores de todos los tiempos',
    draftInfo: {
      year: 2021,
      round: 0,
      pick: 0,
      teamName: 'Undrafted (Fichado por Lakers / Warriors / 76ers / Bulls)',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'Texas Tech Red Raiders / Georgetown',
    },
    draft: '2021 · No Drafteado (Agente Libre)',
    experience: '4 Temporadas (Lakers / Bulls / 76ers / Magic)',
    transfers: [
      {
        season: '21/22',
        date: '10/08/2021',
        fromTeam: 'Texas Tech',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Contrato de 10 días / Two-Way',
      },
      {
        season: '24/25',
        date: '04/09/2024',
        fromTeam: 'Osceola Magic',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '2,20 mill. $',
        feeOrType: 'Contrato NBA Estándar',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón Concurso de Mates NBA All-Star (Slam Dunk Contest)', count: 2, details: '2023 (Puntuación casi perfecta de 50s), 2024' },
      { icon: 'sparkles', name: 'MVP de la NBA G League', count: 1, details: '2024 (Osceola Magic)' },
      { icon: 'ribbon', name: 'Rookie del Año de la NBA G League', count: 1, details: '2022' },
    ],
    seasonAverages: {
      pts: '12.5',
      reb: '2.8',
      ast: '3.4',
      stl: '0.7',
      blk: '0.2',
      fgPct: '46.1%',
      threePct: '37.4%',
      ftPct: '84.0%',
    },
  },

  'Patrick Williams': {
    tacticalRole: 'Alero / Ala-Pívot Físico 3&D (The Paw)',
    specialty: 'Defensa sobre estrellas rivales, manos gigantes, tiro de tres puntos en esquinas y versatilidad',
    playStyle: 'Alero físico moderno con gran capacidad defensiva',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 4,
      teamName: 'Chicago Bulls',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'Florida State Seminoles',
    },
    draft: '2020 · Pick #4 (1ª Ronda por Chicago Bulls)',
    experience: '5 Temporadas (Chicago Bulls)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Florida State',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '32,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4)',
      },
      {
        season: '24/25',
        date: '01/07/2024',
        fromTeam: 'Chicago Bulls',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Extensión de Contrato (5 años / $90M)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2021' },
      { icon: 'sparkles', name: 'Mejor Sexto Hombre de la ACC', count: 1, details: '2020 (Florida State)' },
    ],
    seasonAverages: {
      pts: '10.0',
      reb: '4.2',
      ast: '1.6',
      stl: '0.9',
      blk: '0.8',
      fgPct: '45.0%',
      threePct: '39.9%',
      ftPct: '78.8%',
    },
  },

  'Isaac Okoro': {
    tacticalRole: 'Especialista Defensivo Perimetral Asfixiante (Ice)',
    specialty: 'Defensa individual al hombre, presión de toda la pista y cortes hacia el aro',
    playStyle: 'Defensor de contención puro y finalizador físico',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 5,
      teamName: 'Cleveland Cavaliers',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'Auburn Tigers',
    },
    draft: '2020 · Pick #5 (1ª Ronda por Cleveland Cavaliers)',
    experience: '5 Temporadas (Cavaliers / Bulls)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Auburn Tigers',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '29,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 5)',
      },
      {
        season: '24/25',
        date: '14/09/2024',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '33,00 mill. $',
        feeOrType: 'Sign & Trade (3 años / $33M)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2021' },
      { icon: 'shield', name: 'Equipo Defensivo de la SEC', count: 1, details: '2020 (Auburn)' },
    ],
    seasonAverages: {
      pts: '9.4',
      reb: '3.0',
      ast: '1.9',
      stl: '0.8',
      blk: '0.5',
      fgPct: '49.0%',
      threePct: '39.1%',
      ftPct: '67.9%',
    },
  },

  'Jalen Smith': {
    tacticalRole: 'Ala-Pívot Tirador & Protector Interior (Stix)',
    specialty: 'Triples en pick-and-pop, tapones en rotación defensiva y rebote ofensivo',
    playStyle: 'Espaciador interior moderno con gran presencia física',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 10,
      teamName: 'Phoenix Suns',
      teamAbbr: 'PHX',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
      origin: 'Maryland Terrapins',
    },
    draft: '2020 · Pick #10 (1ª Ronda por Phoenix Suns)',
    experience: '5 Temporadas (Suns / Pacers / Bulls)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Maryland Terrapins',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '19,30 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10)',
      },
      {
        season: '24/25',
        date: '08/07/2024',
        fromTeam: 'Indiana Pacers',
        fromTeamAbbr: 'IND',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '27,00 mill. $',
        feeOrType: 'Agencia Libre (3 años / $27M)',
      },
    ],
    awards: [
      { icon: 'albums', name: '1er Equipo All-Big Ten & Equipo Defensivo', count: 1, details: '2020 (Maryland)' },
      { icon: 'trophy', name: 'Finalista de la NBA Cup', count: 1, details: '2023 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '10.5',
      reb: '6.0',
      ast: '1.1',
      stl: '0.4',
      blk: '1.0',
      fgPct: '59.2%',
      threePct: '42.4%',
      ftPct: '69.2%',
    },
  },

  // ==========================================
  // CLEVELAND CAVALIERS (CLE)
  // ==========================================
  'Donovan Mitchell': {
    tacticalRole: 'Escolta Superestrella & Anotador Letal de 70+ Puntos (Spida)',
    specialty: 'Explosividad al aro, triples kilométricos tras drible, clutch en playoffs y mates estratosféricos',
    playStyle: 'Anotador top de la NBA y uno de los jugadores más temibles en postemporada',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 13,
      teamName: 'Denver Nuggets (Traspasado a Jazz)',
      teamAbbr: 'UTA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
      origin: 'Louisville Cardinals',
    },
    draft: '2017 · Pick #13 (1ª Ronda por Denver Nuggets)',
    experience: '8 Temporadas (Jazz / Cavaliers)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Louisville Cardinals',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '14,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13 / Traspasado por Trey Lyles + Pick 24)',
      },
      {
        season: '22/23',
        date: '01/09/2022',
        fromTeam: 'Utah Jazz',
        fromTeamAbbr: 'UTA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '163,00 mill. $',
        feeOrType: 'Mega-Traspaso de Franquicia (por Collin Sexton + Lauri Markkanen + Ochai Agbaji + 3 primeras rondas)',
      },
      {
        season: '24/25',
        date: '02/07/2024',
        fromTeam: 'Cleveland Cavaliers',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '150,30 mill. $',
        feeOrType: 'Extensión Máxima (3 años / $150.3M)',
      },
    ],
    awards: [
      { icon: 'star', name: '5x NBA All-Star', count: 5, details: '2020, 2021, 2022, 2023, 2024' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2023' },
      { icon: 'trophy', name: 'Campeón del Concurso de Mates NBA (Slam Dunk Contest)', count: 1, details: '2018' },
      { icon: 'flame', name: 'Partido Histórico de 71 Puntos', count: 1, details: '02/01/2023 vs Chicago Bulls (8ª mayor anotación en la historia de la NBA)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2018' },
    ],
    seasonAverages: {
      pts: '26.6',
      reb: '5.1',
      ast: '6.1',
      stl: '1.8',
      blk: '0.5',
      fgPct: '46.2%',
      threePct: '36.8%',
      ftPct: '86.5%',
    },
  },

  'James Harden': {
    tacticalRole: 'MVP Histórico, Maestro del Aclarado & Máximo Asistente (The Beard)',
    specialty: 'Step-back triple imparable, provocación de faltas, pases de alley-oop milimétricos y visión de juego',
    playStyle: 'Uno de los anotadores y creadores ofensivos más dominantes y revolucionarios de la historia',
    draftInfo: {
      year: 2009,
      round: 1,
      pick: 3,
      teamName: 'Oklahoma City Thunder',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Arizona State Sun Devils',
    },
    draft: '2009 · Pick #3 (1ª Ronda por Oklahoma City Thunder)',
    experience: '16 Temporadas (Thunder / Rockets / Nets / 76ers / Clippers / Cavaliers)',
    transfers: [
      {
        season: '09/10',
        date: '25/06/2009',
        fromTeam: 'Arizona State',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '18,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '12/13',
        date: '27/10/2012',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '80,00 mill. $',
        feeOrType: 'Traspaso Histórico (por Kevin Martin + Jeremy Lamb + rondas)',
      },
      {
        season: '20/21',
        date: '14/01/2021',
        fromTeam: 'Houston Rockets',
        fromTeamAbbr: 'HOU',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '133,00 mill. $',
        feeOrType: 'Mega-Traspaso a 4 Bandas',
      },
      {
        season: '21/22',
        date: '10/02/2022',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '68,00 mill. $',
        feeOrType: 'Traspaso (por Ben Simmons + Seth Curry + Andre Drummond)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '70,00 mill. $',
        feeOrType: 'Traspaso de Superestrella',
      },
    ],
    awards: [
      { icon: 'ribbon', name: 'MVP de la Temporada Regular de la NBA', count: 1, details: '2018 (Houston Rockets)' },
      { icon: 'star', name: '10x NBA All-Star', count: 10, details: '2013-2022' },
      { icon: 'albums', name: '6x 1er Equipo All-NBA', count: 6, details: '2014, 2015, 2017, 2018, 2019, 2020' },
      { icon: 'flame', name: '3x Máximo Anotador de la NBA (Scoring Champion)', count: 3, details: '2018 (30.4 ppp), 2019 (36.1 ppp), 2020 (34.3 ppp)' },
      { icon: 'sparkles', name: '2x Máximo Asistente de la NBA (Assists Leader)', count: 2, details: '2017 (11.2 app), 2023 (10.7 app)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Londres 2012' },
      { icon: 'medal', name: 'Campeón del Mundo FIBA', count: 1, details: 'España 2014' },
      { icon: 'trophy', name: 'Mejor Sexto Hombre de la NBA (6MOY)', count: 1, details: '2012 (Oklahoma City Thunder)' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
    ],
    seasonAverages: {
      pts: '16.6',
      reb: '5.1',
      ast: '8.5',
      stl: '1.1',
      blk: '0.6',
      fgPct: '42.8%',
      threePct: '38.1%',
      ftPct: '87.8%',
    },
  },

  'Evan Mobley': {
    tacticalRole: 'Ala-Pívot Defensivo Generacional & Ancla del Quinteto',
    specialty: 'Defensa en cambios 1 al 5, tapones laterales, IQ táctico superior y juego sobre el aro',
    playStyle: 'Defensor de élite absoluta con agilidad de alero y altura de pívot (2,11m)',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 3,
      teamName: 'Cleveland Cavaliers',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'USC Trojans',
    },
    draft: '2021 · Pick #3 (1ª Ronda por Cleveland Cavaliers)',
    experience: '4 Temporadas (Cleveland Cavaliers)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'USC Trojans',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '36,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '24/25',
        date: '20/07/2024',
        fromTeam: 'Cleveland Cavaliers',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Extensión Máxima Rookie (5 años / $224M)',
      },
    ],
    awards: [
      { icon: 'shield', name: '1er Equipo NBA All-Defensive', count: 1, details: '2023 (Finalista al DPOY)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2022 (2º en votación al ROTY)' },
      { icon: 'trophy', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2022 (All-Star Weekend)' },
    ],
    seasonAverages: {
      pts: '16.8',
      reb: '9.8',
      ast: '3.2',
      stl: '0.9',
      blk: '1.6',
      fgPct: '58.0%',
      threePct: '37.3%',
      ftPct: '71.9%',
    },
  },

  'Jarrett Allen': {
    tacticalRole: 'Pívot All-Star Protector de Aro & Finalizador de Pick-and-Roll (The Fro)',
    specialty: 'Tapones espectaculares en el aro, rebotes ofensivos y eficacia récord en tiros de campo',
    playStyle: 'Pívot defensivo dominante con presencia física inigualable en la pintura',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 22,
      teamName: 'Brooklyn Nets',
      teamAbbr: 'BKN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
      origin: 'Texas Longhorns',
    },
    draft: '2017 · Pick #22 (1ª Ronda por Brooklyn Nets)',
    experience: '8 Temporadas (Nets / Cavaliers)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Texas Longhorns',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '10,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 22)',
      },
      {
        season: '20/21',
        date: '14/01/2021',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Traspaso a 4 Bandas (Operación James Harden)',
      },
      {
        season: '24/25',
        date: '02/08/2024',
        fromTeam: 'Cleveland Cavaliers',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '91,00 mill. $',
        feeOrType: 'Extensión de Contrato (3 años / $91M)',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2022' },
      { icon: 'trophy', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2022' },
    ],
    seasonAverages: {
      pts: '16.5',
      reb: '10.5',
      ast: '2.7',
      stl: '0.7',
      blk: '1.1',
      fgPct: '63.4%',
      threePct: '0.0%',
      ftPct: '74.2%',
    },
  },

  'Thomas Bryant': {
    tacticalRole: 'Pívot Anotador de Pintura & Campeón de la NBA',
    specialty: 'Juego interior de gran intensidad, rebote ofensivo potente y tiro de media y larga distancia',
    playStyle: 'Pívot físico con energía desbordante y experiencia ganadora',
    draftInfo: {
      year: 2017,
      round: 2,
      pick: 42,
      teamName: 'Utah Jazz (Traspasado a Lakers)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Indiana Hoosiers',
    },
    draft: '2017 · Pick #42 (2ª Ronda por Utah Jazz)',
    experience: '8 Temporadas (Lakers / Wizards / Nuggets / Heat / Cavaliers)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Indiana Hoosiers',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '2,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 42)',
      },
      {
        season: '22/23',
        date: '09/02/2023',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '4,50 mill. $',
        feeOrType: 'Traspaso (por Davon Reed + 3 segundas rondas)',
      },
      {
        season: '24/25',
        date: '05/07/2024',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '6,00 mill. $',
        feeOrType: 'Agencia Libre',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets)' },
      { icon: 'sparkles', name: '1er Equipo All-G League', count: 1, details: '2018' },
    ],
    seasonAverages: {
      pts: '7.8',
      reb: '4.7',
      ast: '0.8',
      stl: '0.3',
      blk: '0.5',
      fgPct: '57.1%',
      threePct: '38.0%',
      ftPct: '83.3%',
    },
  },

  'Sam Merrill': {
    tacticalRole: 'Francotirador Especialista de 3 Puntos & Campeón de la NBA',
    specialty: 'Triples en movimiento a velocidad extrema, colocación de pantallas y spacing',
    playStyle: 'Tirador letal de élite con rango ilimitado',
    draftInfo: {
      year: 2020,
      round: 2,
      pick: 60,
      teamName: 'New Orleans Pelicans (Traspasado a Bucks)',
      teamAbbr: 'MIL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
      origin: 'Utah State Aggies',
    },
    draft: '2020 · Pick #60 (2ª Ronda / Mr. Irrelevant por New Orleans Pelicans)',
    experience: '5 Temporadas (Bucks / Grizzlies / Cavaliers)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Utah State',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '2,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 60)',
      },
      {
        season: '22/23',
        date: '03/03/2023',
        fromTeam: 'Cleveland Charge',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '5,00 mill. $',
        feeOrType: 'Contrato NBA Estándar',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2021 (Milwaukee Bucks)' },
      { icon: 'sparkles', name: 'Jugador del Año Mountain West', count: 1, details: '2019 (Utah State)' },
    ],
    seasonAverages: {
      pts: '8.0',
      reb: '2.0',
      ast: '1.8',
      stl: '0.4',
      blk: '0.1',
      fgPct: '40.2%',
      threePct: '40.4%',
      ftPct: '92.9%',
    },
  },

  'Peyton Watson': {
    tacticalRole: 'Alero Defensivo Versátil & Campeón de la NBA (P-Wat)',
    specialty: 'Tapones de lado ciego, envergadura de 2,13m, presión al balón y transiciones rápidas',
    playStyle: 'Especialista defensivo joven con instintos de taponador de élite',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 30,
      teamName: 'Oklahoma City Thunder (Traspasado a Nuggets)',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'UCLA Bruins',
    },
    draft: '2022 · Pick #30 (1ª Ronda por Oklahoma City Thunder)',
    experience: '3 Temporadas (Nuggets / Cavaliers)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'UCLA Bruins',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '11,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 30 / Traspasado con JaMychal Green)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Denver Nuggets',
        fromTeamAbbr: 'DEN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '14,00 mill. $',
        feeOrType: 'Traspaso de Joven Defensivo',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets)' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-19', count: 1, details: '2021 (Team USA)' },
    ],
    seasonAverages: {
      pts: '7.5',
      reb: '3.6',
      ast: '1.2',
      stl: '0.6',
      blk: '1.1',
      fgPct: '46.5%',
      threePct: '32.0%',
      ftPct: '68.0%',
    },
  },

  // ==========================================
  // DETROIT PISTONS (DET)
  // ==========================================
  'Cade Cunningham': {
    tacticalRole: 'Base Líder de Franquicia, Creador de Juego & Pick #1 del Draft',
    specialty: 'Control de ritmo magistral, anotación en tres niveles, pases milimétricos y tiros clutch',
    playStyle: 'Base superestrella completo de 2,01m con visión de juego privilegiada',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 1,
      teamName: 'Detroit Pistons',
      teamAbbr: 'DET',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
      origin: 'Oklahoma State Cowboys',
    },
    draft: '2021 · Pick #1 (1ª Ronda por Detroit Pistons)',
    experience: '4 Temporadas (Detroit Pistons)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Oklahoma State',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '45,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Contrato Rookie Escala)',
      },
      {
        season: '24/25',
        date: '09/07/2024',
        fromTeam: 'Detroit Pistons',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Extensión Máxima Designada (5 años / $224M)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2022' },
      { icon: 'sparkles', name: 'MVP del NBA Rising Stars Challenge', count: 1, details: '2022 (All-Star Weekend)' },
      { icon: 'albums', name: '1er Equipo Consensus All-American', count: 1, details: '2021 (Oklahoma State)' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-19', count: 1, details: '2019 (Team USA)' },
    ],
    seasonAverages: {
      pts: '23.8',
      reb: '4.8',
      ast: '8.2',
      stl: '1.0',
      blk: '0.4',
      fgPct: '45.8%',
      threePct: '36.5%',
      ftPct: '86.9%',
    },
  },

  'Jalen Duren': {
    tacticalRole: 'Pívot Físico Dominante, Titán del Rebote & Finalizador Aéreo',
    specialty: 'Rebotes ofensivos en tráfico, mates demoledores de alley-oop y protección de pintura',
    playStyle: 'Fuerza de la naturaleza atlética con facilidad para promediar dobles-dobles de 15+ rebotes',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 13,
      teamName: 'Charlotte Hornets (Traspasado a Pistons)',
      teamAbbr: 'DET',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
      origin: 'Memphis Tigers',
    },
    draft: '2022 · Pick #13 (1ª Ronda por Charlotte Hornets)',
    experience: '3 Temporadas (Detroit Pistons)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Memphis Tigers',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '20,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13 / Noche de Draft)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2023' },
      { icon: 'star', name: 'Rising Stars Challenge Participant', count: 2, details: '2023, 2024' },
      { icon: 'flame', name: 'Partidos con 20+ Rebotes en la NBA', count: 5, details: 'Uno de los reboteadores más jóvenes en la historia' },
    ],
    seasonAverages: {
      pts: '14.2',
      reb: '11.8',
      ast: '2.5',
      stl: '0.6',
      blk: '1.0',
      fgPct: '62.0%',
      threePct: '0.0%',
      ftPct: '79.0%',
    },
  },

  'Ausar Thompson': {
    tacticalRole: 'Alero Defensivo de Élite & Atleta Sobrenatural',
    specialty: 'Tapones como alero, robos en líneas de pase, rebote acrobático y defensa asfixiante',
    playStyle: 'Uno de los mejores y más versátiles defensores jóvenes del baloncesto mundial',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 5,
      teamName: 'Detroit Pistons',
      teamAbbr: 'DET',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
      origin: 'Overtime Elite (City Reapers)',
    },
    draft: '2023 · Pick #5 (1ª Ronda por Detroit Pistons)',
    experience: '2 Temporadas (Detroit Pistons)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Overtime Elite',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '36,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 5)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2024' },
      { icon: 'trophy', name: '2x Campeón de Overtime Elite (OTE)', count: 2, details: '2022, 2023' },
      { icon: 'sparkles', name: '2x MVP de las Finales de OTE', count: 2, details: '2022, 2023' },
    ],
    seasonAverages: {
      pts: '10.5',
      reb: '7.0',
      ast: '2.2',
      stl: '1.2',
      blk: '1.1',
      fgPct: '48.9%',
      threePct: '22.0%',
      ftPct: '61.0%',
    },
  },

  'John Collins': {
    tacticalRole: 'Ala-Pívot Atlético & Rematador de Pintura (The Baptist)',
    specialty: 'Mates estratosféricos en pick-and-roll, tiro exterior en catch-and-shoot y rebote',
    playStyle: 'Finalizador de alta potencia con tiro de 3 puntos fiable',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 19,
      teamName: 'Atlanta Hawks',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Wake Forest Demon Deacons',
    },
    draft: '2017 · Pick #19 (1ª Ronda por Atlanta Hawks)',
    experience: '8 Temporadas (Hawks / Jazz / Pistons)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Wake Forest',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '11,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 19)',
      },
      {
        season: '23/24',
        date: '07/07/2023',
        fromTeam: 'Atlanta Hawks',
        fromTeamAbbr: 'ATL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '75,00 mill. $',
        feeOrType: 'Traspaso (por Rudy Gay + 2ª ronda)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Utah Jazz',
        fromTeamAbbr: 'UTA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '26,00 mill. $',
        feeOrType: 'Traspaso de Veterano Titular',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2018' },
      { icon: 'sparkles', name: 'Finalista Conferencia Este', count: 1, details: '2021 (Atlanta Hawks)' },
    ],
    seasonAverages: {
      pts: '15.1',
      reb: '8.5',
      ast: '1.2',
      stl: '0.6',
      blk: '1.0',
      fgPct: '53.2%',
      threePct: '37.1%',
      ftPct: '79.5%',
    },
  },

  'Taurean Prince': {
    tacticalRole: 'Alero 3&D Experimentado & Campeón de la NBA Cup (The Prince)',
    specialty: 'Triples en transición, defensa física sobre aleros anotadores y veteranía',
    playStyle: 'Alero 3&D clásico y versátil con título de la NBA Cup',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 12,
      teamName: 'Utah Jazz (Traspasado a Hawks)',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Baylor Bears',
    },
    draft: '2016 · Pick #12 (1ª Ronda por Utah Jazz)',
    experience: '9 Temporadas (Hawks / Nets / Cavaliers / Timberwolves / Lakers / Bucks / Pistons)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Baylor Bears',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '13,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 12)',
      },
      {
        season: '23/24',
        date: '06/07/2023',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '4,50 mill. $',
        feeOrType: 'Agencia Libre (Titular en el título de NBA Cup)',
      },
      {
        season: '24/25',
        date: '08/07/2024',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '6,00 mill. $',
        feeOrType: 'Agencia Libre',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la 1ª NBA Cup (In-Season Tournament)', count: 1, details: '2023 (Los Angeles Lakers)' },
      { icon: 'albums', name: '1er Equipo All-Big 12', count: 1, details: '2016 (Baylor)' },
    ],
    seasonAverages: {
      pts: '8.9',
      reb: '3.0',
      ast: '1.5',
      stl: '0.7',
      blk: '0.4',
      fgPct: '44.2%',
      threePct: '39.6%',
      ftPct: '76.0%',
    },
  },

  'Duncan Robinson': {
    tacticalRole: 'Francotirador de Perímetro Histórico & 2x Finalista de la NBA',
    specialty: 'Triples en handoff ultrarrápidos, rango ilimitado de 3 puntos y gravedad espacial',
    playStyle: 'Uno de los tiradores puros más prolíficos y rápidos de la era moderna',
    draftInfo: {
      year: 2018,
      round: 0,
      pick: 0,
      teamName: 'Miami Heat (Undrafted)',
      teamAbbr: 'MIA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
      origin: 'Michigan Wolverines / Williams College (Div III)',
    },
    draft: '2018 · Agente Libre No Drafteado (Fichado por Miami Heat)',
    experience: '7 Temporadas (Miami Heat / Detroit Pistons)',
    transfers: [
      {
        season: '18/19',
        date: '10/07/2018',
        fromTeam: 'Michigan Wolverines',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Contrato Two-Way / Rookie No Drafteado',
      },
      {
        season: '21/22',
        date: '06/08/2021',
        fromTeam: 'Miami Heat',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Mayor Contrato en la Historia para un Jugador No Drafteado (5 años / $90M)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '38,00 mill. $',
        feeOrType: 'Traspaso de Especialista',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Finalista de la NBA', count: 2, details: '2020, 2023 (Miami Heat)' },
      { icon: 'flame', name: 'Jugador Más Rápido en la Historia NBA en Llegar a 1.000 Triples', count: 1, details: 'En solo 343 partidos' },
      { icon: 'sparkles', name: 'Récord de Triples de la Franquicia de Miami Heat', count: 1, details: 'Superando a Tim Hardaway' },
    ],
    seasonAverages: {
      pts: '12.9',
      reb: '2.5',
      ast: '2.8',
      stl: '0.7',
      blk: '0.2',
      fgPct: '45.0%',
      threePct: '39.5%',
      ftPct: '88.9%',
    },
  },

  // ==========================================
  // INDIANA PACERS (IND)
  // ==========================================
  'Tyrese Haliburton': {
    tacticalRole: 'Base Superestrella Generacional, Rey de las Asistencias & Oro Olímpico (Hali)',
    specialty: 'Pases sin mirar inverosímiles, tiro en step-back de tres puntos, ratio asistencias/pérdidas histórico y liderazgo clutch',
    playStyle: 'El mejor pasador y arquitecto ofensivo del baloncesto moderno',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 12,
      teamName: 'Sacramento Kings',
      teamAbbr: 'SAC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
      origin: 'Iowa State Cyclones',
    },
    draft: '2020 · Pick #12 (1ª Ronda por Sacramento Kings)',
    experience: '5 Temporadas (Kings / Pacers)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Iowa State',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '17,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 12)',
      },
      {
        season: '21/22',
        date: '08/02/2022',
        fromTeam: 'Sacramento Kings',
        fromTeamAbbr: 'SAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Traspaso Histórico (por Domantas Sabonis + Jeremy Lamb + Justin Holiday)',
      },
      {
        season: '24/25',
        date: '01/07/2023',
        fromTeam: 'Indiana Pacers',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '260,00 mill. $',
        feeOrType: 'Supermax Designated Rookie Extension (5 años / $260M)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024' },
      { icon: 'star', name: '2x NBA All-Star (Titular 2024)', count: 2, details: '2023, 2024' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2024' },
      { icon: 'sparkles', name: 'Máximo Asistente de la NBA (Assists Leader)', count: 1, details: '2023-24 (10.9 asistencias por partido)' },
      { icon: 'trophy', name: 'Finalista y All-Tournament Team de la 1ª NBA Cup', count: 1, details: '2023 (In-Season Tournament)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2021' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '20.1',
      reb: '3.9',
      ast: '10.9',
      stl: '1.2',
      blk: '0.7',
      fgPct: '47.7%',
      threePct: '36.4%',
      ftPct: '85.5%',
    },
  },

  'Pascal Siakam': {
    tacticalRole: 'Ala-Pívot All-NBA, Campeón de la NBA & Motor Inagotable (Spicy P)',
    specialty: 'Giro sobre el eje (spin move) imparable, contraataque a máxima velocidad, tiro de media distancia y defensa versátil',
    playStyle: 'Ala-pívot moderno total con anillo de campeón y experiencia estelar',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 27,
      teamName: 'Toronto Raptors',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'New Mexico State Aggies / Camerún',
    },
    draft: '2016 · Pick #27 (1ª Ronda por Toronto Raptors)',
    experience: '9 Temporadas (Raptors / Pacers)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'New Mexico State',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '6,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 27)',
      },
      {
        season: '23/24',
        date: '17/01/2024',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '136,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Bruce Brown + Jordan Nwora + 3 primeras rondas)',
      },
      {
        season: '24/25',
        date: '07/07/2024',
        fromTeam: 'Indiana Pacers',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '189,50 mill. $',
        feeOrType: 'Extensión Máxima (4 años / $189.5M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2019 (Toronto Raptors — Titular clave con 32 pts en el Game 1)' },
      { icon: 'star', name: '2x NBA All-Star (Titular 2020)', count: 2, details: '2020, 2023' },
      { icon: 'albums', name: '2x Seleccionado All-NBA (2º Equipo 2020, 3er Equipo 2022)', count: 2, details: '2020, 2022' },
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2019' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
      { icon: 'trophy', name: 'MVP de las Finales de la NBA G League', count: 1, details: '2017 (Raptors 905)' },
    ],
    seasonAverages: {
      pts: '21.7',
      reb: '7.1',
      ast: '4.3',
      stl: '0.8',
      blk: '0.4',
      fgPct: '53.6%',
      threePct: '38.6%',
      ftPct: '73.2%',
    },
  },

  'Ivica Zubac': {
    tacticalRole: 'Pívot Tradicional Fuerte & Máquina de Dobles-Dobles (Zu)',
    specialty: 'Juego de espaldas al aro, ganchos de derecha suaves, rebote defensivo y bloqueos rocosos',
    playStyle: 'Pívot puro europeo con gran presencia física en la pintura',
    draftInfo: {
      year: 2016,
      round: 2,
      pick: 32,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Mega Leks / Croacia',
    },
    draft: '2016 · Pick #32 (2ª Ronda por Los Angeles Lakers)',
    experience: '9 Temporadas (Lakers / Clippers / Pacers)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Mega Leks',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '3,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 32)',
      },
      {
        season: '18/19',
        date: '07/02/2019',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '33,00 mill. $',
        feeOrType: 'Traspaso Directo (por Mike Muscala)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '58,60 mill. $',
        feeOrType: 'Extensión y Traspaso (3 años / $58.6M)',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Partido Histórico de 31 Puntos y 29 Rebotes', count: 1, details: '27/11/2022 vs Indiana Pacers' },
      { icon: 'medal', name: 'Pívot Titular de la Selección de Croacia', count: 1, details: 'Torneos FIBA & Preolímpicos' },
    ],
    seasonAverages: {
      pts: '11.7',
      reb: '9.2',
      ast: '1.4',
      stl: '0.3',
      blk: '1.2',
      fgPct: '64.9%',
      threePct: '0.0%',
      ftPct: '72.3%',
    },
  },

  'Kelly Oubre Jr.': {
    tacticalRole: 'Alero Anotador Explosivo & Defensor Enérgico (Tsunami Papi)',
    specialty: 'Anotación en penetración, mates espectaculares, robos en primera línea y actitud aguerrida',
    playStyle: 'Alero rápido y dinámico con facilidad anotadora de 20+ puntos',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 15,
      teamName: 'Atlanta Hawks (Traspasado a Wizards)',
      teamAbbr: 'WAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
      origin: 'Kansas Jayhawks',
    },
    draft: '2015 · Pick #15 (1ª Ronda por Atlanta Hawks)',
    experience: '10 Temporadas (Wizards / Suns / Warriors / Hornets / 76ers / Pacers)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Kansas Jayhawks',
        toTeam: 'Washington Wizards',
        toTeamAbbr: 'WAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        marketValue: '9,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 15)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Philadelphia 76ers',
        fromTeamAbbr: 'PHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '16,30 mill. $',
        feeOrType: 'Agencia Libre (2 años / $16.3M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Big 12 All-Newcomer Team', count: 1, details: '2015 (Kansas)' },
      { icon: 'flame', name: 'Partido de 40 Puntos en la NBA', count: 1, details: '2021 (Golden State Warriors)' },
    ],
    seasonAverages: {
      pts: '15.4',
      reb: '5.0',
      ast: '1.5',
      stl: '1.1',
      blk: '0.7',
      fgPct: '44.1%',
      threePct: '33.5%',
      ftPct: '75.0%',
    },
  },

  'T.J. McConnell': {
    tacticalRole: 'Base Revulsivo de Élite, Ladrón Histórico & Ídolo Clutch',
    specialty: 'Robos desde atrás (back-tap), tiros de media distancia automáticos y energía contagiosa',
    playStyle: 'El mejor base de cambio de ritmo de la liga, determinante en series de playoffs',
    draftInfo: {
      year: 2015,
      round: 0,
      pick: 0,
      teamName: 'Philadelphia 76ers (Undrafted)',
      teamAbbr: 'PHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
      origin: 'Arizona Wildcats / Duquesne',
    },
    draft: '2015 · Agente Libre No Drafteado (Fichado por 76ers)',
    experience: '10 Temporadas (76ers / Pacers)',
    transfers: [
      {
        season: '15/16',
        date: '27/09/2015',
        fromTeam: 'Arizona Wildcats',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Agente Libre No Drafteado (Era The Process)',
      },
      {
        season: '19/20',
        date: '29/07/2019',
        fromTeam: 'Philadelphia 76ers',
        fromTeamAbbr: 'PHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '7,00 mill. $',
        feeOrType: 'Agencia Libre (2 años / $7M)',
      },
      {
        season: '24/25',
        date: '30/08/2024',
        fromTeam: 'Indiana Pacers',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '45,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $45M)',
      },
    ],
    awards: [
      { icon: 'shield', name: 'Récord Histórico de Robos en una Mitad en la NBA', count: 1, details: '9 robos en una primera parte (03/03/2021 vs Cavaliers)' },
      { icon: 'sparkles', name: 'Triple-Doble Histórico con Robos', count: 1, details: '16 pts, 13 ast, 10 robos saliendo desde el banquillo' },
      { icon: 'trophy', name: 'Finalista de la 1ª NBA Cup', count: 1, details: '2023 (Indiana Pacers)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '10.2',
      reb: '2.7',
      ast: '5.5',
      stl: '1.0',
      blk: '0.1',
      fgPct: '55.6%',
      threePct: '40.9%',
      ftPct: '79.0%',
    },
  },

  'Obi Toppin': {
    tacticalRole: 'Ala-Pívot Machacador Aéreo & Campeón de Mates de la NBA',
    specialty: 'Mates entre las piernas en carrera, transiciones supersónicas y triples en catch-and-shoot',
    playStyle: 'Atleta de altos vuelos y finalizador espectacular en pista abierta',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 8,
      teamName: 'New York Knicks',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Dayton Flyers',
    },
    draft: '2020 · Pick #8 (1ª Ronda por New York Knicks)',
    experience: '5 Temporadas (Knicks / Pacers)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Dayton Flyers',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '22,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 8)',
      },
      {
        season: '23/24',
        date: '07/07/2023',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '6,80 mill. $',
        feeOrType: 'Traspaso (por 2 segundas rondas)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Indiana Pacers',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $60M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón del Concurso de Mates NBA (Slam Dunk Contest)', count: 1, details: '2022' },
      { icon: 'sparkles', name: 'Jugador Universitario del Año en EE.UU. (Naismith Trophy & Wooden Award)', count: 1, details: '2020 (Dayton)' },
      { icon: 'trophy', name: 'Finalista de la 1ª NBA Cup', count: 1, details: '2023 (Indiana Pacers)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '10.3',
      reb: '3.9',
      ast: '1.6',
      stl: '0.6',
      blk: '0.5',
      fgPct: '57.3%',
      threePct: '40.3%',
      ftPct: '77.0%',
    },
  },

  'Andrew Nembhard': {
    tacticalRole: 'Base / Escolta Titular, Héroe Clutch & Defensor de Perímetro',
    specialty: 'Tiros ganadores en el último segundo, pick-and-roll paciente y defensa de choque',
    playStyle: 'Jugador de sangre fría con actuaciones históricas en playoffs',
    draftInfo: {
      year: 2022,
      round: 2,
      pick: 31,
      teamName: 'Indiana Pacers',
      teamAbbr: 'IND',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
      origin: 'Gonzaga Bulldogs / Florida / Canadá',
    },
    draft: '2022 · Pick #31 (2ª Ronda por Indiana Pacers)',
    experience: '3 Temporadas (Indiana Pacers)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Gonzaga Bulldogs',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '8,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 31 — Mayor contrato garantizado para un 2ª ronda)',
      },
      {
        season: '24/25',
        date: '26/07/2024',
        fromTeam: 'Indiana Pacers',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '59,00 mill. $',
        feeOrType: 'Extensión de Contrato (3 años / $59M)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2023' },
      { icon: 'sparkles', name: 'Triple Ganador sobre la Bocina vs Lakers', count: 1, details: '2022 (Crypto.com Arena)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
      { icon: 'medal', name: 'Estrella de la Selección de Canadá', count: 1, details: 'Juegos Olímpicos París 2024' },
    ],
    seasonAverages: {
      pts: '12.0',
      reb: '2.5',
      ast: '4.8',
      stl: '0.9',
      blk: '0.2',
      fgPct: '49.8%',
      threePct: '36.5%',
      ftPct: '80.4%',
    },
  },

  'Aaron Nesmith': {
    tacticalRole: 'Alero Titular Físico & Especialista 3&D Intenso',
    specialty: 'Defensa cuerpo a cuerpo asfixiante, 42%+ en triples y energía de rebote',
    playStyle: 'Guerrero defensivo y tirador exterior de alta fiabilidad',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 14,
      teamName: 'Boston Celtics',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Vanderbilt Commodores',
    },
    draft: '2020 · Pick #14 (1ª Ronda por Boston Celtics)',
    experience: '5 Temporadas (Celtics / Pacers)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Vanderbilt',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '16,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 14)',
      },
      {
        season: '22/23',
        date: '09/07/2022',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '33,00 mill. $',
        feeOrType: 'Traspaso (Operación Malcolm Brogdon)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Finalista de la 1ª NBA Cup', count: 1, details: '2023 (Indiana Pacers)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '12.2',
      reb: '3.8',
      ast: '1.5',
      stl: '0.9',
      blk: '0.7',
      fgPct: '49.6%',
      threePct: '41.9%',
      ftPct: '78.1%',
    },
  },

  // ==========================================
  // MILWAUKEE BUCKS (MIL)
  // ==========================================
  'Tyler Herro': {
    tacticalRole: 'Escolta Anotador Superestrella, Mejor Sexto Hombre & Francotirador Clutch (Boy Wonder)',
    specialty: 'Tiro tras bote letal en media distancia y triples, flotadoras en la pintura y sangre fría en finales de partido',
    playStyle: 'Uno de los tiradores y creadores de tiro más eléctricos y resolutivos de la NBA',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 13,
      teamName: 'Miami Heat',
      teamAbbr: 'MIA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
      origin: 'Kentucky Wildcats / Milwaukee, Wisconsin',
    },
    draft: '2019 · Pick #13 (1ª Ronda por Miami Heat)',
    experience: '6 Temporadas (Heat / Bucks)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '17,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13)',
      },
      {
        season: '23/24',
        date: '02/10/2022',
        fromTeam: 'Miami Heat',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '120,00 mill. $',
        feeOrType: 'Extensión de Contrato Rookie Máxima (4 años / $120M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '120,00 mill. $',
        feeOrType: 'Regreso Histórico a su Estado Natal (Milwaukee, Wisconsin)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Mejor Sexto Hombre de la NBA (6MOY)', count: 1, details: '2022 (Miami Heat — Récord anotador desde el banquillo)' },
      { icon: 'trophy', name: '2x Finalista de la NBA', count: 2, details: '2020, 2023 (Miami Heat)' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2020' },
      { icon: 'flame', name: 'Partido Histórico de 37 Puntos en Finales de Conferencia Este como Rookie', count: 1, details: '2020 vs Boston Celtics' },
    ],
    seasonAverages: {
      pts: '20.8',
      reb: '5.3',
      ast: '4.5',
      stl: '0.7',
      blk: '0.1',
      fgPct: '44.1%',
      threePct: '39.6%',
      ftPct: '85.6%',
    },
  },

  'Kyle Kuzma': {
    tacticalRole: 'Ala-Pívot Anotador Versátil & Campeón de la NBA (Kuz)',
    specialty: 'Anotación en aclarados, tiros en suspensión de media distancia, rebote y liderazgo veterano',
    playStyle: 'Anotador prolífico con anillo de campeón y gran presencia ofensiva',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 27,
      teamName: 'Brooklyn Nets (Traspasado a Lakers)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Utah Utes / Flint, Michigan',
    },
    draft: '2017 · Pick #27 (1ª Ronda por Brooklyn Nets)',
    experience: '8 Temporadas (Lakers / Wizards / Bucks)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Utah Utes',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '8,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 27 / Operación D\'Angelo Russell - Brook Lopez)',
      },
      {
        season: '21/22',
        date: '06/08/2021',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Washington Wizards',
        toTeamAbbr: 'WAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        marketValue: '39,00 mill. $',
        feeOrType: 'Mega-Traspaso (Operación Russell Westbrook)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Washington Wizards',
        fromTeamAbbr: 'WAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Traspaso de Franquicia Contender (4 años / $90M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2020 (Los Angeles Lakers)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2018' },
      { icon: 'sparkles', name: 'MVP del NBA Rising Stars Challenge', count: 1, details: '2019 (All-Star Weekend — 35 Puntos)' },
    ],
    seasonAverages: {
      pts: '22.2',
      reb: '6.6',
      ast: '4.2',
      stl: '0.5',
      blk: '0.7',
      fgPct: '46.3%',
      threePct: '33.6%',
      ftPct: '77.5%',
    },
  },

  'Myles Turner': {
    tacticalRole: 'Pívot Especialista 3&D de Pintura & 2x Máximo Taponador de la NBA',
    specialty: 'Tapones intimidatorios de élite, triples frontales en pick-and-pop y defensa de aro',
    playStyle: 'El pívot stretch-5 arquetípico definitivo: protector de aro legendario y amenaza de 3 puntos',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 11,
      teamName: 'Indiana Pacers',
      teamAbbr: 'IND',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
      origin: 'Texas Longhorns',
    },
    draft: '2015 · Pick #11 (1ª Ronda por Indiana Pacers)',
    experience: '10 Temporadas (Pacers / Bucks)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Texas Longhorns',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '10,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 11)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Indiana Pacers',
        fromTeamAbbr: 'IND',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Traspaso de Pívot Estrella',
      },
    ],
    awards: [
      { icon: 'shield', name: '2x Máximo Taponador de la NBA (Blocks Leader)', count: 2, details: '2019 (2.7 tpp), 2021 (3.4 tpp)' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2016' },
      { icon: 'trophy', name: 'Finalista de la 1ª NBA Cup', count: 1, details: '2023 (Indiana Pacers)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Este', count: 1, details: '2024 (Indiana Pacers)' },
    ],
    seasonAverages: {
      pts: '17.1',
      reb: '6.9',
      ast: '1.3',
      stl: '0.5',
      blk: '1.9',
      fgPct: '52.4%',
      threePct: '35.8%',
      ftPct: '77.3%',
    },
  },

  'Jaime Jaquez Jr.': {
    tacticalRole: 'Alero Técnico de Huella Mexicana & 1er Equipo All-Rookie (Triple J)',
    specialty: 'Juego de pies al poste bajo, pivotes de veterano, cortes al aro y dureza defensiva',
    playStyle: 'Alero todoterreno con mentalidad competitiva implacable y madurez táctica',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 18,
      teamName: 'Miami Heat',
      teamAbbr: 'MIA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
      origin: 'UCLA Bruins / México & EE.UU.',
    },
    draft: '2023 · Pick #18 (1ª Ronda por Miami Heat)',
    experience: '2 Temporadas (Heat / Bucks)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'UCLA Bruins',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '17,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 18)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '20,00 mill. $',
        feeOrType: 'Traspaso de Joven Estrella',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2024 (Miami Heat)' },
      { icon: 'ribbon', name: '2x Rookie del Mes de la Conferencia Este', count: 2, details: 'Octubre/Noviembre 2023, Diciembre 2023' },
      { icon: 'trophy', name: 'Participante en el NBA Slam Dunk Contest', count: 1, details: '2024 (All-Star Weekend)' },
      { icon: 'sparkles', name: 'Jugador del Año Pac-12', count: 1, details: '2023 (UCLA)' },
    ],
    seasonAverages: {
      pts: '11.9',
      reb: '3.8',
      ast: '2.6',
      stl: '1.1',
      blk: '0.3',
      fgPct: '48.9%',
      threePct: '32.2%',
      ftPct: '81.1%',
    },
  },

  'Caris LeVert': {
    tacticalRole: 'Escolta / Alero Creador con Balón & Microondas de Anotación',
    specialty: 'Crossovers con cambio de ritmo, tiro tras bote, asistencias en penetración y aclarados',
    playStyle: 'Anotador técnico con capacidad probada de noches de 40+ y 50+ puntos',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 20,
      teamName: 'Indiana Pacers (Traspasado a Nets)',
      teamAbbr: 'BKN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
      origin: 'Michigan Wolverines',
    },
    draft: '2016 · Pick #20 (1ª Ronda por Indiana Pacers)',
    experience: '9 Temporadas (Nets / Pacers / Cavaliers / Bucks)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Michigan Wolverines',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '7,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 20 / Traspasado por Thaddeus Young)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '32,00 mill. $',
        feeOrType: 'Traspaso de Sexto Hombre',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Partido Histórico de 51 Puntos en la NBA', count: 1, details: '03/03/2020 vs Boston Celtics' },
      { icon: 'sparkles', name: '2x Finalista a Mejor Sexto Hombre de la NBA (Top 5)', count: 2, details: '2023, 2024' },
    ],
    seasonAverages: {
      pts: '14.0',
      reb: '4.1',
      ast: '5.1',
      stl: '1.1',
      blk: '0.5',
      fgPct: '42.1%',
      threePct: '32.5%',
      ftPct: '76.6%',
    },
  },

  'Gary Trent Jr.': {
    tacticalRole: 'Escolta Francotirador 3&D de Racha',
    specialty: 'Triples en catch-and-shoot, robos con manos rápidas en primera línea y tiro exterior',
    playStyle: 'Anotador de rachas con gran instinto para robar balones y castigar desde el triple',
    draftInfo: {
      year: 2018,
      round: 2,
      pick: 37,
      teamName: 'Sacramento Kings (Traspasado a Blazers)',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'Duke Blue Devils',
    },
    draft: '2018 · Pick #37 (2ª Ronda por Sacramento Kings)',
    experience: '7 Temporadas (Blazers / Raptors / Bucks)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '3,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 37)',
      },
      {
        season: '20/21',
        date: '25/03/2021',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '54,00 mill. $',
        feeOrType: 'Traspaso (por Norman Powell)',
      },
      {
        season: '24/25',
        date: '20/07/2024',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '2,60 mill. $',
        feeOrType: 'Agencia Libre',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Racha Histórica de 5 Partidos Consecutivos con 30+ Puntos', count: 1, details: '2022 (Toronto Raptors — Récord de franquicia igualando a DeMar DeRozan)' },
      { icon: 'shield', name: 'Top 3 en Robos por Partido de la NBA', count: 1, details: '2021-22 (1.7 robos por partido)' },
    ],
    seasonAverages: {
      pts: '13.7',
      reb: '2.3',
      ast: '1.7',
      stl: '1.1',
      blk: '0.1',
      fgPct: '42.6%',
      threePct: '39.3%',
      ftPct: '77.1%',
    },
  },

  'Kevin Porter Jr.': {
    tacticalRole: 'Combo Guard Anotador con Manejo Virtuoso & Creador Ofensivo (KPJ)',
    specialty: 'Juego de 50 puntos y 11 asistencias histórico, manejo de balón impredecible y tiro en step-back',
    playStyle: 'Anotador dinámico de alto impacto con talento generacional con el balón',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 30,
      teamName: 'Milwaukee Bucks (Traspasado a Cavaliers)',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'USC Trojans',
    },
    draft: '2019 · Pick #30 (1ª Ronda por Milwaukee Bucks)',
    experience: '5 Temporadas (Cavaliers / Rockets / PAOK / Bucks / Clippers)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'USC Trojans',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '9,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 30)',
      },
      {
        season: '20/21',
        date: '28/01/2021',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '15,00 mill. $',
        feeOrType: 'Traspaso Directo',
      },
      {
        season: '24/25',
        date: '10/07/2024',
        fromTeam: 'PAOK Salónica',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '4,80 mill. $',
        feeOrType: 'Regreso a la NBA',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Jugador Más Joven en la Historia NBA en Lograr 50 Puntos y 10 Asistencias', count: 1, details: '20 años y 360 días (vs Milwaukee Bucks)' },
      { icon: 'sparkles', name: '1er Equipo All-G League', count: 1, details: '2021 (Líder Anotador de la G League)' },
    ],
    seasonAverages: {
      pts: '12.0',
      reb: '3.5',
      ast: '3.8',
      stl: '1.0',
      blk: '0.3',
      fgPct: '44.0%',
      threePct: '36.5%',
      ftPct: '78.0%',
    },
  },

  'Kel\'el Ware': {
    tacticalRole: 'Pívot Protector de Aro Moderno & Amenaza Aérea',
    specialty: 'Tapones con envergadura de 2,31m, alley-oops en pick-and-roll y tiro de 3 puntos',
    playStyle: 'Unicornio interior atlético con gran proyección defensiva y ofensiva',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 15,
      teamName: 'Miami Heat',
      teamAbbr: 'MIA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
      origin: 'Indiana Hoosiers / Oregon',
    },
    draft: '2024 · Pick #15 (1ª Ronda por Miami Heat)',
    experience: '2 Temporadas (Heat / Bucks)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'Indiana Hoosiers',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '20,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 15 — Traspaso en Noche de Draft)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón & 1er Equipo NBA Summer League', count: 1, details: 'Las Vegas 2024' },
      { icon: 'albums', name: '2º Equipo All-Big Ten & All-Defensive Team', count: 1, details: '2024 (Indiana)' },
    ],
    seasonAverages: {
      pts: '9.8',
      reb: '6.4',
      ast: '0.9',
      stl: '0.5',
      blk: '1.5',
      fgPct: '56.0%',
      threePct: '36.0%',
      ftPct: '70.0%',
    },
  },

  'AJ Green': {
    tacticalRole: 'Francotirador de Perímetro Especialista (Automatic Green)',
    specialty: 'Triples en salida de bloqueo indirecto, 41%+ de acierto exterior y defensa posicional disciplinada',
    playStyle: 'Tirador puro de élite que ensancha la cancha',
    draftInfo: {
      year: 2022,
      round: 0,
      pick: 0,
      teamName: 'Milwaukee Bucks (Undrafted)',
      teamAbbr: 'MIL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
      origin: 'Northern Iowa Panthers',
    },
    draft: '2022 · Agente Libre No Drafteado (Fichado por Milwaukee Bucks)',
    experience: '3 Temporadas (Milwaukee Bucks)',
    transfers: [
      {
        season: '22/23',
        date: '01/07/2022',
        fromTeam: 'Northern Iowa',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Two-Way Contract / Rookie Free Agent',
      },
      {
        season: '23/24',
        date: '07/07/2023',
        fromTeam: 'Milwaukee Bucks',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '6,30 mill. $',
        feeOrType: 'Contrato NBA Estándar Multianual',
      },
    ],
    awards: [
      { icon: 'sparkles', name: '2x Jugador del Año Conferencia MVC', count: 2, details: '2020, 2022 (Northern Iowa)' },
      { icon: 'flame', name: '41.5% en Triples en Carrera NBA', count: 1, details: 'Uno de los porcentajes más altos de la liga' },
    ],
    seasonAverages: {
      pts: '6.8',
      reb: '1.8',
      ast: '1.0',
      stl: '0.3',
      blk: '0.1',
      fgPct: '42.5%',
      threePct: '41.5%',
      ftPct: '89.5%',
    },
  },
};
