import { PlayerDossier } from './playerDossier';

export const SOUTHWEST_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // DALLAS MAVERICKS (DAL)
  // ==========================================
  'Kyrie Irving': {
    tacticalRole: 'El Mejor Manejador de Balón de la Historia, Campeón de la NBA & Clutch Legendario (Uncle Drew / Kai)',
    specialty: 'Manejo de balón circense sobrenatural, tiros con efecto imposibles contra tabla y triples ganadores en Finales',
    playStyle: 'El artista y mago ofensivo más deslumbrante que jamás haya pisado una cancha de baloncesto',
    draftInfo: {
      year: 2011,
      round: 1,
      pick: 1,
      teamName: 'Cleveland Cavaliers',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'Duke Blue Devils / Melbourne, Australia',
    },
    draft: '2011 · Pick #1 (1ª Ronda por Cleveland Cavaliers)',
    experience: '14 Temporadas (Cavaliers / Celtics / Nets / Mavericks)',
    transfers: [
      {
        season: '11/12',
        date: '23/06/2011',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '23,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1)',
      },
      {
        season: '22/23',
        date: '06/02/2023',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '126,00 mill. $',
        feeOrType: 'Traspaso (por Spencer Dinwiddie + Dorian Finney-Smith + rondas)',
      },
      {
        season: '23/24',
        date: '07/07/2023',
        fromTeam: 'Dallas Mavericks',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '126,00 mill. $',
        feeOrType: 'Extensión de Contrato (3 años / $126M — Finalista de la NBA 2024)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2016 (Cleveland Cavaliers — Triple legendario en la cara de Curry en el Game 7)' },
      { icon: 'trophy', name: 'Finalista de la NBA & Campeón Conferencia Oeste', count: 1, details: '2024 (Dallas Mavericks)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Río 2016' },
      { icon: 'medal', name: 'Campeón del Mundo FIBA & MVP del Mundial', count: 1, details: 'España 2014' },
      { icon: 'star', name: '8x NBA All-Star (MVP del All-Star Game 2014 con 31 Puntos)', count: 8, details: '2013, 2014, 2015, 2017, 2018, 2019, 2021, 2023' },
      { icon: 'albums', name: '3x Seleccionado All-NBA (2º Equipo 2019, 3er Equipo 2015, 2021)', count: 3, details: 'Club 50-40-90 en 2021' },
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2012' },
      { icon: 'trophy', name: 'Campeón del Concurso de Triples NBA All-Star', count: 1, details: '2013' },
    ],
    seasonAverages: {
      pts: '25.6',
      reb: '5.0',
      ast: '5.2',
      stl: '1.3',
      blk: '0.5',
      fgPct: '49.7%',
      threePct: '41.1%',
      ftPct: '90.5%',
    },
  },

  'Cooper Flagg': {
    tacticalRole: 'Fenómeno Generacional, Alero / Ala-Pívot Total & Futuro #1 del Draft',
    specialty: 'Defensa destructiva de ayuda y hombre a hombre, IQ táctico precoz y anotación en tres niveles',
    playStyle: 'El talento estadounidense más dominante y completo desde LeBron James',
    draftInfo: {
      year: 2025,
      round: 1,
      pick: 1,
      teamName: 'Dallas Mavericks (Consenso #1 Proyectado)',
      teamAbbr: 'DAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
      origin: 'Duke Blue Devils / Montverde Academy / Newport, Maine',
    },
    draft: '2025 · Pick #1 Consenso Proyectado',
    experience: '1 Temporada (Duke / Dallas Mavericks)',
    transfers: [
      {
        season: '24/25',
        date: '01/07/2024',
        fromTeam: 'Montverde Academy',
        toTeam: 'Duke Blue Devils',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '12,00 mill. $',
        feeOrType: 'Compromiso Universitario NCAA / Duke',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Estrella Destacada del USA Select Team vs Dream Team Olímpico París 2024', count: 1, details: 'Dominando con 17 años ante LeBron, Curry y Durant' },
      { icon: 'trophy', name: 'Gatorade National Player of the Year', count: 1, details: '2024' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-17 & MVP del Mundial', count: 1, details: '2022 (Team USA)' },
      { icon: 'sparkles', name: 'Naismith Prep Player of the Year', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '18.5',
      reb: '8.2',
      ast: '4.1',
      stl: '1.8',
      blk: '2.0',
      fgPct: '51.0%',
      threePct: '38.0%',
      ftPct: '82.0%',
    },
  },

  'Dereck Lively II': {
    tacticalRole: 'Pívot Protector de Aro Moderno & Finalizador Aéreo de Élite (D-Live)',
    specialty: 'Tapones espectaculares, alley-oops imparables en pick-and-roll y pase corto desde el tiro libre',
    playStyle: 'El ancla defensiva y aérea de las Finales de la NBA para Dallas',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 12,
      teamName: 'Oklahoma City Thunder (Traspasado a Mavericks)',
      teamAbbr: 'DAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
      origin: 'Duke Blue Devils / Philadelphia, Pennsylvania',
    },
    draft: '2023 · Pick #12 (1ª Ronda por Oklahoma City Thunder)',
    experience: '2 Temporadas (Dallas Mavericks)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '22,30 mill. $',
        feeOrType: 'Draft de la NBA (Pick 12 / Traspaso Davis Bertans)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2024' },
      { icon: 'trophy', name: 'Finalista de la NBA & Campeón Conferencia Oeste', count: 1, details: '2024 (Dallas Mavericks — Récord de 16/16 tiros en una serie de playoffs)' },
      { icon: 'shield', name: 'ACC All-Defensive Team & All-Freshman Team', count: 1, details: '2023 (Duke)' },
    ],
    seasonAverages: {
      pts: '8.8',
      reb: '6.9',
      ast: '1.1',
      stl: '0.7',
      blk: '1.4',
      fgPct: '74.7%',
      threePct: '0.0%',
      ftPct: '50.6%',
    },
  },

  // ==========================================
  // HOUSTON ROCKETS (HOU)
  // ==========================================
  'Kevin Durant': {
    tacticalRole: 'El Anotador Más Puro de la Historia, 2x Campeón NBA & 4x Medallista de Oro Olímpico (Easy Money Sniper / Slim Reaper)',
    specialty: 'Tiro en suspensión por elevación imparable a 2,11m, efectividad de tres niveles récord y defensa perimetral',
    playStyle: 'Anotador supremo irrepetible con cuatro medallas de oro olímpicas y dos MVP de Finales',
    draftInfo: {
      year: 2007,
      round: 1,
      pick: 2,
      teamName: 'Seattle SuperSonics',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Texas Longhorns / Washington, D.C.',
    },
    draft: '2007 · Pick #2 (1ª Ronda por Seattle SuperSonics)',
    experience: '18 Temporadas (Sonics / Thunder / Warriors / Nets / Suns / Rockets)',
    transfers: [
      {
        season: '07/08',
        date: '28/06/2007',
        fromTeam: 'Texas Longhorns',
        toTeam: 'Seattle SuperSonics',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '19,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 2)',
      },
      {
        season: '16/17',
        date: '07/07/2016',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '54,30 mill. $',
        feeOrType: 'Agencia Libre (2x Campeón y 2x MVP de Finales 2017, 2018)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '198,00 mill. $',
        feeOrType: 'Mega-Traspaso de Leyenda a Houston',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón de la NBA', count: 2, details: '2017, 2018 (Golden State Warriors)' },
      { icon: 'sparkles', name: '2x Consecutivo MVP de las Finales de la NBA (Bill Russell Trophy)', count: 2, details: '2017, 2018 (Triples icónicos en el Game 3 en Cleveland)' },
      { icon: 'ribbon', name: 'MVP de la Temporada Regular de la NBA', count: 1, details: '2014 (32.0 ppp — "You the real MVP" Speech)' },
      { icon: 'medal', name: '4x Medalla de Oro Olímpica (Team USA — Récord Absoluto)', count: 4, details: 'Londres 2012, Río 2016, Tokio 2020, París 2024 (Máximo anotador en la historia olímpica de EE.UU.)' },
      { icon: 'star', name: '14x NBA All-Star (2x MVP del All-Star Game)', count: 14, details: '2010-2024' },
      { icon: 'albums', name: '11x Seleccionado All-NBA (6x 1er Equipo, 5x 2º Equipo)', count: 11, details: '2010-2024' },
      { icon: 'flame', name: '4x Máximo Anotador de la NBA (Scoring Champion)', count: 4, details: '2010, 2011, 2012, 2014' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
      { icon: 'flame', name: '+29.000 Puntos Anotados en Carrera NBA', count: 1, details: 'Top 8 Histórico de la NBA' },
    ],
    seasonAverages: {
      pts: '27.1',
      reb: '6.6',
      ast: '5.0',
      stl: '0.9',
      blk: '1.2',
      fgPct: '52.3%',
      threePct: '41.3%',
      ftPct: '85.6%',
    },
  },

  'Alperen Sengun': {
    tacticalRole: 'Pívot All-Star Virtuoso, Mago del Pase al Poste & Eje Ofensivo (Baby Jokic)',
    specialty: 'Pases de espaldas sin mirar, juego de pies brillante en el poste bajo y anotación interior',
    playStyle: 'El pívot pasador turco más creativo de la liga con noches de 45 puntos',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 16,
      teamName: 'Oklahoma City Thunder (Traspasado a Rockets)',
      teamAbbr: 'HOU',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
      origin: 'Besiktas (Turquía) / Giresun',
    },
    draft: '2021 · Pick #16 (1ª Ronda por Oklahoma City Thunder)',
    experience: '4 Temporadas (Houston Rockets)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Besiktas',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '15,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 16 / Traspaso por 2 futuras primeras)',
      },
      {
        season: '24/25',
        date: '21/10/2024',
        fromTeam: 'Houston Rockets',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '185,00 mill. $',
        feeOrType: 'Extensión Rookie Máxima (5 años / $185M)',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Partido Histórico de 45 Puntos y 16 Rebotes en la NBA', count: 1, details: '05/03/2024 vs Victor Wembanyama y San Antonio Spurs' },
      { icon: 'sparkles', name: '3º en la Votación al Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2024' },
      { icon: 'trophy', name: 'MVP de la Superliga de Baloncesto de Turquía', count: 1, details: '2021 (Con solo 18 años)' },
    ],
    seasonAverages: {
      pts: '21.1',
      reb: '9.3',
      ast: '5.0',
      stl: '1.2',
      blk: '0.7',
      fgPct: '53.7%',
      threePct: '29.7%',
      ftPct: '69.3%',
    },
  },

  // ==========================================
  // NEW ORLEANS PELICANS (NOP)
  // ==========================================
  'Zion Williamson': {
    tacticalRole: 'Fuerza de la Naturaleza Imparable, 2x All-Star & Titán de la Pintura (Zanos)',
    specialty: 'Potencia de despegue descomunal con 130 kg de peso, finalizaciones zurdas acrobáticas y visión de pase',
    playStyle: 'El jugador interior más atlético y arrollador de su generación',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 1,
      teamName: 'New Orleans Pelicans',
      teamAbbr: 'NOP',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
      origin: 'Duke Blue Devils / Salisbury, North Carolina',
    },
    draft: '2019 · Pick #1 (1ª Ronda por New Orleans Pelicans)',
    experience: '6 Temporadas (New Orleans Pelicans)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '44,30 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Escala Rookie)',
      },
      {
        season: '22/23',
        date: '06/07/2022',
        fromTeam: 'New Orleans Pelicans',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '197,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $197M)',
      },
    ],
    awards: [
      { icon: 'star', name: '2x NBA All-Star (2x Titular)', count: 2, details: '2021, 2023' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2020' },
      { icon: 'sparkles', name: 'Jugador Universitario Nacional del Año (Naismith & Wooden Award)', count: 1, details: '2019 (Duke)' },
      { icon: 'flame', name: 'Promedio Histórico de 27.0 ppp al 61.1% en Tiros de Campo', count: 1, details: '2020-21 (El más joven en la historia con esa eficacia)' },
    ],
    seasonAverages: {
      pts: '22.9',
      reb: '5.8',
      ast: '5.0',
      stl: '1.1',
      blk: '0.7',
      fgPct: '57.0%',
      threePct: '33.3%',
      ftPct: '70.2%',
    },
  },

  // ==========================================
  // SAN ANTONIO SPURS (SAS)
  // ==========================================
  'Victor Wembanyama': {
    tacticalRole: 'El Unicornio Definitivo del Baloncesto Mundial, Rookie del Año & Taponador Histórico (The Alien / Wemby)',
    specialty: 'Envergadura extraterrestre de 2,44m, tapones imposibles (3.6 tpp), manejo de balón como escolta y triples tras drible',
    playStyle: 'El prospecto más dominante y revolucionario del deporte moderno, destinado a reescribir la historia de la NBA',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 1,
      teamName: 'San Antonio Spurs',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'Metropolitans 92 / Le Chesnay, Francia',
    },
    draft: '2023 · Pick #1 (1ª Ronda por San Antonio Spurs — Unanimous #1)',
    experience: '2 Temporadas (San Antonio Spurs)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Metropolitans 92',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '55,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Escala Rookie 4 años)',
      },
    ],
    awards: [
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY Unánime)', count: 1, details: '2024 (99 de 99 votos de primer lugar)' },
      { icon: 'shield', name: '1er Equipo NBA All-Defensive en su Año Rookie', count: 1, details: '2024 (Primer novato en toda la historia de la NBA en lograrlo)' },
      { icon: 'shield', name: '2º en la Votación a Mejor Defensor del Año (DPOY)', count: 1, details: '2024 (Con solo 20 años)' },
      { icon: 'flame', name: 'Máximo Taponador de la NBA (Blocks Leader)', count: 1, details: '2023-24 (3.6 tapones por partido — 254 tapones totales)' },
      { icon: 'medal', name: 'Medalla de Plata Olímpica (Francia)', count: 1, details: 'París 2024 (26 Puntos en la Final Olímpica vs Team USA — Mejor Joven del Torneo)' },
      { icon: 'sparkles', name: 'Múltiples Partidos Históricos 5x5 en la NBA', count: 2, details: '27 pts, 10 reb, 8 ast, 5 rob, 5 tap vs Lakers / 25 pts, 9 reb, 7 ast, 5 rob, 5 tap vs Jazz' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '21.4',
      reb: '10.6',
      ast: '3.9',
      stl: '1.2',
      blk: '3.6',
      fgPct: '46.5%',
      threePct: '32.5%',
      ftPct: '79.6%',
    },
  },

  'Stephon Castle': {
    tacticalRole: 'Base / Escolta Campeón de la NCAA, Defensor de Élite & Pick #4 del Draft',
    specialty: 'Defensa de perímetro física asfixiante, penetración con cambio de ritmo y pase en pick-and-roll',
    playStyle: 'Base bidireccional de campeonato con mentalidad de ganador absoluto',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 4,
      teamName: 'San Antonio Spurs',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'UConn Huskies / Covington, Georgia',
    },
    draft: '2024 · Pick #4 (1ª Ronda por San Antonio Spurs)',
    experience: '2 Temporadas (San Antonio Spurs)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'UConn Huskies',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '41,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4 — Escala Rookie)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA', count: 1, details: '2024 (UConn Huskies — 21 Puntos en la Final Four vs Alabama)' },
      { icon: 'sparkles', name: 'Big East Freshman of the Year', count: 1, details: '2024 (UConn)' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-18 Américas', count: 1, details: '2022 (Team USA)' },
    ],
    seasonAverages: {
      pts: '12.2',
      reb: '3.5',
      ast: '3.8',
      stl: '1.0',
      blk: '0.4',
      fgPct: '46.0%',
      threePct: '33.0%',
      ftPct: '78.0%',
    },
  },

  'De\'Aaron Fox': {
    tacticalRole: 'Base Supersónico All-NBA, Primer Rey del Clutch & Líder en Robos (Swipa)',
    specialty: 'La velocidad con balón más rápida de la NBA, tiros clutch en el último cuarto y robos en transición',
    playStyle: 'Anotador eléctrico letal de 25+ puntos y primer ganador del Jerry West Trophy',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 5,
      teamName: 'Sacramento Kings',
      teamAbbr: 'SAC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
      origin: 'Kentucky Wildcats / New Orleans, Louisiana',
    },
    draft: '2017 · Pick #5 (1ª Ronda por Sacramento Kings)',
    experience: '8 Temporadas (Kings / Spurs)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '24,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 5)',
      },
      {
        season: '20/21',
        date: '25/11/2020',
        fromTeam: 'Sacramento Kings',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '163,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $163M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Sacramento Kings',
        fromTeamAbbr: 'SAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '163,00 mill. $',
        feeOrType: 'Mega-Traspaso de Base Estrella para acompañar a Wembanyama',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Primer Ganador del Premio Clutch Player of the Year (Jerry West Trophy)', count: 1, details: '2023 (Récord de anotación en los últimos 5 minutos de partidos apretados)' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2023' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2023' },
      { icon: 'shield', name: 'Líder en Robos de la NBA (Steals Leader)', count: 1, details: '2023-24 (2.0 robos por partido — 150 robos totales)' },
      { icon: 'flame', name: 'Partido Histórico de 60 Puntos en la NBA', count: 1, details: '15/11/2024 vs Minnesota Timberwolves (Récord histórico de la franquicia de los Kings)' },
    ],
    seasonAverages: {
      pts: '26.6',
      reb: '4.6',
      ast: '5.6',
      stl: '2.0',
      blk: '0.4',
      fgPct: '46.5%',
      threePct: '36.9%',
      ftPct: '73.8%',
    },
  },

  'Luke Kornet': {
    tacticalRole: 'Pívot Protector de Pintura, Especialista en Tapón Eclipse & Campeón de la NBA (The Kornet Contest)',
    specialty: 'El famoso salto "Kornet Contest" para taponar visión de tiro, colocación de pantallas y rebote',
    playStyle: 'Pívot de 2,18m inteligente y factor defensivo de campeonato',
    draftInfo: {
      year: 2017,
      round: 0,
      pick: 0,
      teamName: 'New York Knicks (Undrafted)',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Vanderbilt Commodores',
    },
    draft: '2017 · Agente Libre No Drafteado (Fichado por New York Knicks)',
    experience: '8 Temporadas (Knicks / Bulls / Celtics / Spurs)',
    transfers: [
      {
        season: '17/18',
        date: '03/07/2017',
        fromTeam: 'Vanderbilt',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Contrato Two-Way / Rookie Free Agent',
      },
      {
        season: '23/24',
        date: '09/07/2022',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '4,50 mill. $',
        feeOrType: 'Contrato NBA Estándar (Campeón de la NBA 2024)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '6,00 mill. $',
        feeOrType: 'Traspaso de Pívot Campeón',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Anillo #18 histórico)' },
      { icon: 'shield', name: 'Inventor del "Kornet Contest"', count: 1, details: 'Técnica defensiva viral de salto desde la pintura para molestar el tiro de tres' },
      { icon: 'albums', name: '1er Equipo All-SEC & SEC All-Defensive Team', count: 1, details: '2017 (Vanderbilt)' },
    ],
    seasonAverages: {
      pts: '5.3',
      reb: '4.1',
      ast: '1.1',
      stl: '0.4',
      blk: '1.0',
      fgPct: '70.0%',
      threePct: '0.0%',
      ftPct: '90.7%',
    },
  },
};
