import { PlayerDossier } from './playerDossier';

export const NORTHWEST_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // DENVER NUGGETS (DEN)
  // ==========================================
  'Nikola Jokic': {
    tacticalRole: 'Pívot Superestrella Mundial, 3x MVP de la NBA & Creador Supremo (The Joker)',
    specialty: 'Visión de juego sobrenatural, pases de quarterback de costa a costa, tiro sombor shuffle y dominio histórico del triple-doble',
    playStyle: 'El mejor jugador de baloncesto del planeta y el pívot pasador más genial y eficiente de todos los tiempos',
    draftInfo: {
      year: 2014,
      round: 2,
      pick: 41,
      teamName: 'Denver Nuggets',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'Mega Basket (Serbia)',
    },
    draft: '2014 · Pick #41 (2ª Ronda por Denver Nuggets — Anunciado durante anuncio de Taco Bell)',
    experience: '10 Temporadas (Denver Nuggets)',
    transfers: [
      {
        season: '15/16',
        date: '28/07/2015',
        fromTeam: 'Mega Basket',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '5,50 mill. $',
        feeOrType: 'Contrato Rookie de la NBA (Pick 41)',
      },
      {
        season: '18/19',
        date: '09/07/2018',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '148,00 mill. $',
        feeOrType: 'Extensión Máxima (5 años / $148M)',
      },
      {
        season: '23/24',
        date: '01/07/2022',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '276,00 mill. $',
        feeOrType: 'Supermax Extension Histórica (5 años / $276M)',
      },
    ],
    awards: [
      { icon: 'ribbon', name: '3x MVP de la Temporada Regular de la NBA', count: 3, details: '2021, 2022, 2024' },
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets — Primer anillo en la historia de la franquicia)' },
      { icon: 'sparkles', name: 'MVP de las Finales de la NBA (Bill Russell Trophy)', count: 1, details: '2023 vs Miami Heat' },
      { icon: 'star', name: '6x NBA All-Star (Titular indiscutible)', count: 6, details: '2019, 2020, 2021, 2022, 2023, 2024' },
      { icon: 'albums', name: '4x 1er Equipo All-NBA & 2x 2º Equipo All-NBA', count: 6, details: '2019, 2021, 2022, 2024 (1º) / 2020, 2023 (2º)' },
      { icon: 'medal', name: '2x Medallista Olímpico (Serbia)', count: 2, details: 'Plata Río 2016, Bronce París 2024 (Triple-doble histórico olímpico vs Alemania)' },
      { icon: 'flame', name: '+130 Triples-Dobles en Temporada Regular', count: 1, details: '4º en la historia de la NBA' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2016' },
    ],
    seasonAverages: {
      pts: '26.4',
      reb: '12.4',
      ast: '9.0',
      stl: '1.4',
      blk: '0.9',
      fgPct: '58.3%',
      threePct: '35.9%',
      ftPct: '81.7%',
    },
  },

  'Jamal Murray': {
    tacticalRole: 'Base Anotador Superestrella, Campeón de la NBA & Asesino de Playoffs (Blue Arrow)',
    specialty: 'Anotación clutch en el clutch, tiros en suspensión imposibles, química perfecta con Jokic en pick-and-roll',
    playStyle: 'Anotador de sangre fría capaz de promediar 30+ puntos y múltiples partidos de 50 puntos en postemporada',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 7,
      teamName: 'Denver Nuggets',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'Kentucky Wildcats / Kitchener, Canadá',
    },
    draft: '2016 · Pick #7 (1ª Ronda por Denver Nuggets)',
    experience: '8 Temporadas (Denver Nuggets)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '14,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7)',
      },
      {
        season: '19/20',
        date: '24/07/2019',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '170,00 mill. $',
        feeOrType: 'Extensión Máxima (5 años / $170M)',
      },
      {
        season: '24/25',
        date: '07/09/2024',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '208,00 mill. $',
        feeOrType: 'Extensión Máxima (4 años / $208M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets — 21.4 ppp y 10.0 app en las Finales)' },
      { icon: 'sparkles', name: 'MVP del NBA Rising Stars Challenge', count: 1, details: '2017 (36 Puntos y 9 Triples)' },
      { icon: 'flame', name: '2x Partidos de 50 Puntos en una Misma Serie de Playoffs', count: 2, details: '2020 vs Utah Jazz (Burbuja de Orlando)' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2017' },
      { icon: 'medal', name: 'Medalla de Plata Panamericana', count: 1, details: '2015 (Canadá)' },
    ],
    seasonAverages: {
      pts: '21.2',
      reb: '4.1',
      ast: '6.5',
      stl: '1.0',
      blk: '0.4',
      fgPct: '48.1%',
      threePct: '42.5%',
      ftPct: '85.3%',
    },
  },

  'DeMar DeRozan': {
    tacticalRole: 'Escolta / Alero Leyenda del Tiro de Media Distancia (+23.000 Puntos)',
    specialty: 'Juego de pies al poste de nivel histórico, tiros en fadeaway desde 5 metros y clutch supremo',
    playStyle: 'Uno de los anotadores clásicos más puros, elegantes y consistentes de la historia moderna',
    draftInfo: {
      year: 2009,
      round: 1,
      pick: 9,
      teamName: 'Toronto Raptors',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'USC Trojans / Compton, California',
    },
    draft: '2009 · Pick #9 (1ª Ronda por Toronto Raptors)',
    experience: '16 Temporadas (Raptors / Spurs / Bulls / Kings / Nuggets)',
    transfers: [
      {
        season: '09/10',
        date: '25/06/2009',
        fromTeam: 'USC Trojans',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '10,70 mill. $',
        feeOrType: 'Draft de la NBA (Pick 9)',
      },
      {
        season: '18/19',
        date: '18/07/2018',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '83,00 mill. $',
        feeOrType: 'Mega-Traspaso Histórico (por Kawhi Leonard + Danny Green)',
      },
      {
        season: '21/22',
        date: '11/08/2021',
        fromTeam: 'San Antonio Spurs',
        fromTeamAbbr: 'SAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '82,00 mill. $',
        feeOrType: 'Sign & Trade (3 años / $82M)',
      },
      {
        season: '24/25',
        date: '08/07/2024',
        fromTeam: 'Sacramento Kings',
        fromTeamAbbr: 'SAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '74,00 mill. $',
        feeOrType: 'Traspaso a 3 Bandas de Veterano Estrella',
      },
    ],
    awards: [
      { icon: 'star', name: '6x NBA All-Star (3x Titular)', count: 6, details: '2014, 2016, 2017, 2018, 2022, 2023' },
      { icon: 'albums', name: '3x Seleccionado All-NBA (2º Equipo 2018, 2022; 3er Equipo 2017)', count: 3, details: '2017, 2018, 2022' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Río 2016' },
      { icon: 'medal', name: 'Campeón de la Copa del Mundo FIBA', count: 1, details: 'España 2014' },
      { icon: 'flame', name: 'Más de 23.000 Puntos Anotados en Carrera NBA', count: 1, details: 'Top 35 Histórico de Anotadores' },
      { icon: 'sparkles', name: 'Máximo Anotador Histórico de Toronto Raptors', count: 1, details: '13.296 Puntos con la franquicia canadiense' },
    ],
    seasonAverages: {
      pts: '24.0',
      reb: '4.3',
      ast: '5.3',
      stl: '1.1',
      blk: '0.6',
      fgPct: '48.0%',
      threePct: '33.3%',
      ftPct: '85.3%',
    },
  },

  'Aaron Gordon': {
    tacticalRole: 'Ala-Pívot Físico Dominante, Campeón de la NBA & Defensor Todoterreno (Air Gordon)',
    specialty: 'Mates de espaldas demoledores, defensa sobre estrellas exteriores (LeBron, Durant, Butler) y cortes sin balón',
    playStyle: 'El complemento atlético y táctico perfecto de Nikola Jokic con anillo de campeón',
    draftInfo: {
      year: 2014,
      round: 1,
      pick: 4,
      teamName: 'Orlando Magic',
      teamAbbr: 'ORL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
      origin: 'Arizona Wildcats',
    },
    draft: '2014 · Pick #4 (1ª Ronda por Orlando Magic)',
    experience: '11 Temporadas (Magic / Nuggets)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'Arizona Wildcats',
        toTeam: 'Orlando Magic',
        toTeamAbbr: 'ORL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        marketValue: '18,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4)',
      },
      {
        season: '20/21',
        date: '25/03/2021',
        fromTeam: 'Orlando Magic',
        fromTeamAbbr: 'ORL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '76,00 mill. $',
        feeOrType: 'Traspaso (por Gary Harris + R.J. Hampton + 1ª ronda)',
      },
      {
        season: '24/25',
        date: '21/10/2024',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '133,00 mill. $',
        feeOrType: 'Extensión Máxima (4 años / $133M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets — Pieza angular defensiva del anillo)' },
      { icon: 'sparkles', name: '2x Finalista Legendario del Concurso de Mates (Slam Dunk Contest)', count: 2, details: '2016 (Considerado el mejor concurso de la historia con Zach LaVine), 2020' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-19 & MVP del Torneo', count: 1, details: '2013 (Team USA)' },
      { icon: 'albums', name: '1er Equipo All-Pac-12', count: 1, details: '2014 (Arizona)' },
    ],
    seasonAverages: {
      pts: '13.9',
      reb: '6.5',
      ast: '3.5',
      stl: '0.8',
      blk: '0.6',
      fgPct: '55.6%',
      threePct: '29.0%',
      ftPct: '65.8%',
    },
  },

  'Christian Braun': {
    tacticalRole: 'Escolta Defensivo Intenso, Campeón de la NBA & Campeón NCAA',
    specialty: 'Defensa perimetral feroz, contraataques fulgurantes, mates en transición y mentalidad ganadora',
    playStyle: 'Ganador nato con campeonatos consecutivos de NCAA y NBA',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 21,
      teamName: 'Denver Nuggets',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'Kansas Jayhawks',
    },
    draft: '2022 · Pick #21 (1ª Ronda por Denver Nuggets)',
    experience: '3 Temporadas (Denver Nuggets)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Kansas Jayhawks',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '13,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 21)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets — 15 pts en el Game 3 de Finales)' },
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA', count: 1, details: '2022 (Kansas Jayhawks)' },
      { icon: 'sparkles', name: '5º Jugador en la Historia en Ganar NCAA y NBA en Años Consecutivos', count: 1, details: 'Uniéndose a Magic Johnson, Bill Russell, Henry Bibby y Billy Thompson' },
    ],
    seasonAverages: {
      pts: '14.5',
      reb: '4.8',
      ast: '2.3',
      stl: '1.2',
      blk: '0.8',
      fgPct: '54.5%',
      threePct: '40.0%',
      ftPct: '80.0%',
    },
  },

  // ==========================================
  // MINNESOTA TIMBERWOLVES (MIN)
  // ==========================================
  'Anthony Edwards': {
    tacticalRole: 'Escolta Superestrella Generacional, Oro Olímpico & Futura Cara de la NBA (Ant-Man)',
    specialty: 'Mates sobre rivales descomunales (posterizers), tiro tras step-back mortal, defensa 1v1 y carisma supremo',
    playStyle: 'Anotador implacable con explosividad física al nivel de Michael Jordan y Kobe Bryant',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 1,
      teamName: 'Minnesota Timberwolves',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'Georgia Bulldogs / Atlanta, Georgia',
    },
    draft: '2020 · Pick #1 (1ª Ronda por Minnesota Timberwolves)',
    experience: '5 Temporadas (Minnesota Timberwolves)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Georgia Bulldogs',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '44,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Escala Rookie)',
      },
      {
        season: '24/25',
        date: '03/07/2023',
        fromTeam: 'Minnesota Timberwolves',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '260,00 mill. $',
        feeOrType: 'Designated Rookie Supermax Extension (5 años / $260M)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024' },
      { icon: 'star', name: '2x NBA All-Star', count: 2, details: '2023, 2024' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2024' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Oeste', count: 1, details: '2024 (Minnesota Timberwolves)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2021' },
      { icon: 'flame', name: 'Máximo Anotador de Team USA en el Mundial FIBA', count: 1, details: '2023' },
    ],
    seasonAverages: {
      pts: '26.8',
      reb: '5.6',
      ast: '5.2',
      stl: '1.4',
      blk: '0.6',
      fgPct: '46.7%',
      threePct: '41.2%',
      ftPct: '83.6%',
    },
  },

  'Rudy Gobert': {
    tacticalRole: 'Pívot Protector de Pintura Histórico & 4x Mejor Defensor de la NBA (The Stifle Tower)',
    specialty: 'Intimidación de aro insuperable, bloqueo de tiros, rebote defensivo y bloqueos directos masivos',
    playStyle: 'El defensor interior más dominante de su era y ancla defensiva de calibre salón de la fama',
    draftInfo: {
      year: 2013,
      round: 1,
      pick: 27,
      teamName: 'Denver Nuggets (Traspasado a Jazz)',
      teamAbbr: 'UTA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
      origin: 'Cholet Basket / Francia',
    },
    draft: '2013 · Pick #27 (1ª Ronda por Denver Nuggets)',
    experience: '12 Temporadas (Jazz / Timberwolves)',
    transfers: [
      {
        season: '13/14',
        date: '27/06/2013',
        fromTeam: 'Cholet Basket',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '5,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 27 / Traspasado por Erick Green + dinero)',
      },
      {
        season: '22/23',
        date: '06/07/2022',
        fromTeam: 'Utah Jazz',
        fromTeamAbbr: 'UTA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '205,00 mill. $',
        feeOrType: 'Mega-Traspaso Histórico (por 5 primeras rondas + 4 jugadores)',
      },
      {
        season: '24/25',
        date: '23/10/2024',
        fromTeam: 'Minnesota Timberwolves',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '110,00 mill. $',
        feeOrType: 'Extensión de Contrato (3 años / $110M)',
      },
    ],
    awards: [
      { icon: 'shield', name: '4x Defensor del Año de la NBA (DPOY — Récord Histórico)', count: 4, details: '2018, 2019, 2021, 2024 (Empatado con Dikembe Mutombo y Ben Wallace)' },
      { icon: 'medal', name: '2x Medalla de Plata Olímpica (Francia)', count: 2, details: 'Tokio 2020, París 2024' },
      { icon: 'star', name: '3x NBA All-Star', count: 3, details: '2020, 2021, 2022' },
      { icon: 'shield', name: '7x 1er Equipo NBA All-Defensive', count: 7, details: '2017, 2018, 2019, 2020, 2021, 2022, 2024' },
      { icon: 'albums', name: '4x Seleccionado All-NBA (4x 3er Equipo)', count: 4, details: '2017, 2019, 2020, 2021' },
      { icon: 'sparkles', name: 'Máximo Taponador de la NBA (2017) & Máximo Reboteador (2022)', count: 2, details: 'Líder en ambas categorías' },
    ],
    seasonAverages: {
      pts: '13.7',
      reb: '12.9',
      ast: '1.3',
      stl: '0.7',
      blk: '2.1',
      fgPct: '65.7%',
      threePct: '0.0%',
      ftPct: '63.8%',
    },
  },

  'LaMelo Ball': {
    tacticalRole: 'Base Mago del Pase, All-Star & Espectáculo Puro',
    specialty: 'Pases sin mirar de espaldas, triples kilométricos desde el logo y manejo de balón acrobático',
    playStyle: 'Uno de los bases más creativos y espectaculares del baloncesto moderno',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 3,
      teamName: 'Charlotte Hornets',
      teamAbbr: 'CHA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
      origin: 'Illawarra Hawks (Australia / NBL)',
    },
    draft: '2020 · Pick #3 (1ª Ronda por Charlotte Hornets)',
    experience: '5 Temporadas (Hornets / Timberwolves)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Illawarra Hawks',
        toTeam: 'Charlotte Hornets',
        toTeamAbbr: 'CHA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        marketValue: '35,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Charlotte Hornets',
        fromTeamAbbr: 'CHA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '204,00 mill. $',
        feeOrType: 'Mega-Traspaso de Base Estrella',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2021' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2022' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2021' },
      { icon: 'ribbon', name: 'Rookie del Año de la NBL Australiana', count: 1, details: '2020' },
    ],
    seasonAverages: {
      pts: '23.9',
      reb: '5.1',
      ast: '8.0',
      stl: '1.4',
      blk: '0.3',
      fgPct: '43.5%',
      threePct: '37.8%',
      ftPct: '86.5%',
    },
  },

  'Donte DiVincenzo': {
    tacticalRole: 'Escolta Francotirador, Campeón de la NBA & 2x Campeón NCAA (The Big Ragù)',
    specialty: 'Récord histórico de triples, defensa agresiva de líneas de pase y energía incombustible',
    playStyle: 'Tirador letal de élite con pedigrí absoluto de campeón en todos los niveles',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 17,
      teamName: 'Milwaukee Bucks',
      teamAbbr: 'MIL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
      origin: 'Villanova Wildcats',
    },
    draft: '2018 · Pick #17 (1ª Ronda por Milwaukee Bucks)',
    experience: '7 Temporadas (Bucks / Kings / Warriors / Knicks / Timberwolves)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Villanova Wildcats',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '13,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 17)',
      },
      {
        season: '23/24',
        date: '08/07/2023',
        fromTeam: 'Golden State Warriors',
        fromTeamAbbr: 'GSW',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '50,00 mill. $',
        feeOrType: 'Agencia Libre (4 años / $50M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '50,00 mill. $',
        feeOrType: 'Mega-Traspaso (Operación Karl-Anthony Towns)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2021 (Milwaukee Bucks)' },
      { icon: 'trophy', name: '2x Campeón Nacional de la NCAA', count: 2, details: '2016, 2018 (Villanova)' },
      { icon: 'sparkles', name: 'Mejor Jugador de la Final Four de la NCAA (MOP)', count: 1, details: '2018 (31 Puntos en la Final)' },
      { icon: 'flame', name: 'Récord de Triples en una Temporada de los New York Knicks', count: 1, details: '2023-24 (283 triples anotados)' },
    ],
    seasonAverages: {
      pts: '15.5',
      reb: '3.7',
      ast: '2.7',
      stl: '1.3',
      blk: '0.4',
      fgPct: '44.3%',
      threePct: '40.1%',
      ftPct: '75.4%',
    },
  },

  'Jonathan Kuminga': {
    tacticalRole: 'Alero / Ala-Pívot Físico Imparable & Campeón de la NBA (The Kum Bucket)',
    specialty: 'Potencia demoledora en transiciones, mates espectaculares en tráfico y tiros de media distancia',
    playStyle: 'Fuerza física imparable con gran potencial de anotador estelar',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 7,
      teamName: 'Golden State Warriors',
      teamAbbr: 'GSW',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
      origin: 'NBA G League Ignite / R.D. Congo',
    },
    draft: '2021 · Pick #7 (1ª Ronda por Golden State Warriors)',
    experience: '4 Temporadas (Warriors / Timberwolves)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'G League Ignite',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '24,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Golden State Warriors',
        fromTeamAbbr: 'GSW',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '30,00 mill. $',
        feeOrType: 'Traspaso de Joven Estrella',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2022 (Golden State Warriors — Segundo campeón más joven de la historia)' },
      { icon: 'sparkles', name: 'Rising Stars Challenge Participant', count: 2, details: '2022, 2023' },
    ],
    seasonAverages: {
      pts: '16.1',
      reb: '4.8',
      ast: '2.2',
      stl: '0.7',
      blk: '0.5',
      fgPct: '52.9%',
      threePct: '32.1%',
      ftPct: '74.6%',
    },
  },

  // ==========================================
  // OKLAHOMA CITY THUNDER (OKC)
  // ==========================================
  'Shai Gilgeous-Alexander': {
    tacticalRole: 'Base / Escolta Superestrella Mundial, 1er Equipo All-NBA & Candidato al MVP (SGA)',
    specialty: 'Fintas y desaceleraciones imposibles, tiro de media distancia infalible, robos de balón y penetración letal',
    playStyle: 'Uno de los anotadores y defensores exteriores más dominantes e imparables del planeta',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 11,
      teamName: 'Charlotte Hornets (Traspasado a Clippers)',
      teamAbbr: 'LAC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
      origin: 'Kentucky Wildcats / Toronto, Canadá',
    },
    draft: '2018 · Pick #11 (1ª Ronda por Charlotte Hornets)',
    experience: '7 Temporadas (Clippers / Thunder)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '16,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 11 / Traspasado por Miles Bridges + 2 segundas)',
      },
      {
        season: '19/20',
        date: '10/07/2019',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '180,00 mill. $',
        feeOrType: 'Mega-Traspaso Histórico (por Paul George + 5 primeras rondas)',
      },
      {
        season: '22/23',
        date: '06/08/2021',
        fromTeam: 'Oklahoma City Thunder',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '179,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $179M)',
      },
    ],
    awards: [
      { icon: 'albums', name: '2x 1er Equipo All-NBA', count: 2, details: '2023, 2024' },
      { icon: 'ribbon', name: '2º en la Votación al MVP de la NBA', count: 1, details: '2024 (Solo detrás de Nikola Jokic)' },
      { icon: 'star', name: '2x NBA All-Star (Titular 2024)', count: 2, details: '2023, 2024' },
      { icon: 'shield', name: 'Líder en Robos de la NBA', count: 1, details: '2023-24 (2.0 robos por partido)' },
      { icon: 'medal', name: 'Medalla de Bronce en Copa del Mundo FIBA', count: 1, details: '2023 (Canadá — Miembro del Quinteto Ideal del Torneo)' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2019' },
    ],
    seasonAverages: {
      pts: '30.1',
      reb: '5.5',
      ast: '6.2',
      stl: '2.0',
      blk: '0.9',
      fgPct: '53.5%',
      threePct: '35.3%',
      ftPct: '87.4%',
    },
  },

  'Chet Holmgren': {
    tacticalRole: 'Pívot Unicornio Generacional, Ancla Defensiva & Estrella Joven',
    specialty: 'Tapones espectaculares con envergadura de 2,29m, triples en pick-and-pop y manejo de balón',
    playStyle: 'Pívot moderno revolucionario capaz de taponar como Bill Russell y tirar como Kevin Durant',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 2,
      teamName: 'Oklahoma City Thunder',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Gonzaga Bulldogs / Minneapolis, Minnesota',
    },
    draft: '2022 · Pick #2 (1ª Ronda por Oklahoma City Thunder)',
    experience: '3 Temporadas (Oklahoma City Thunder)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Gonzaga Bulldogs',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '44,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 2 — Escala Rookie)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2024 (2º en votación al ROTY)' },
      { icon: 'shield', name: '2º Máximo Taponador de la NBA en su Año Rookie', count: 1, details: '2023-24 (2.3 tapones por partido / 190 tapones totales)' },
      { icon: 'medal', name: 'Medalla de Oro FIBA Sub-19 & MVP del Torneo', count: 1, details: '2021 (Team USA)' },
      { icon: 'albums', name: '1er Equipo Consensus All-American', count: 1, details: '2022 (Gonzaga)' },
    ],
    seasonAverages: {
      pts: '16.5',
      reb: '7.9',
      ast: '2.4',
      stl: '0.6',
      blk: '2.3',
      fgPct: '53.0%',
      threePct: '37.0%',
      ftPct: '79.3%',
    },
  },

  'Jalen Williams': {
    tacticalRole: 'Alero / Creador Secundario All-Star en Ciernes & Estrella Bidireccional (J-Dub)',
    specialty: 'Envergadura descomunal (2,18m), tiros de media distancia quirúrgicos, defensa perimetral y pases',
    playStyle: 'Alero versátil total de élite, factor clave en la cima del Oeste de Oklahoma City',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 12,
      teamName: 'Oklahoma City Thunder',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Santa Clara Broncos',
    },
    draft: '2022 · Pick #12 (1ª Ronda por Oklahoma City Thunder)',
    experience: '3 Temporadas (Oklahoma City Thunder)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Santa Clara',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '21,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 12)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2023 (Finalista al Rookie del Año)' },
      { icon: 'sparkles', name: '2x Participante en el Rising Stars Challenge', count: 2, details: '2023, 2024' },
      { icon: 'albums', name: '1er Equipo All-WCC', count: 1, details: '2022 (Santa Clara)' },
    ],
    seasonAverages: {
      pts: '19.1',
      reb: '4.0',
      ast: '4.5',
      stl: '1.1',
      blk: '0.6',
      fgPct: '54.0%',
      threePct: '42.7%',
      ftPct: '81.4%',
    },
  },

  'Alex Caruso': {
    tacticalRole: 'Especialista Defensivo de Élite, Campeón de la NBA & Ladrón de Balones (The Carushow / Bald Mamba)',
    specialty: 'Defensa perimetral asfixiante, robos en salto, desvíos de balón y triples en momentos cumbre',
    playStyle: 'El mejor escolta defensivo puro de la NBA con impacto descomunal en el quinteto',
    draftInfo: {
      year: 2016,
      round: 0,
      pick: 0,
      teamName: 'Philadelphia 76ers / Lakers (Undrafted)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Texas A&M Aggies',
    },
    draft: '2016 · No Drafteado (Firmado por OKC Blue / Lakers)',
    experience: '8 Temporadas (Lakers / Bulls / Thunder)',
    transfers: [
      {
        season: '17/18',
        date: '13/07/2017',
        fromTeam: 'Oklahoma City Blue',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Primer Contrato Two-Way en la Historia de los Lakers',
      },
      {
        season: '21/22',
        date: '10/08/2021',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '37,00 mill. $',
        feeOrType: 'Agencia Libre (4 años / $37M)',
      },
      {
        season: '24/25',
        date: '21/06/2024',
        fromTeam: 'Chicago Bulls',
        fromTeamAbbr: 'CHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '40,00 mill. $',
        feeOrType: 'Traspaso Directo (por Josh Giddey)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2020 (Los Angeles Lakers — Titular en el Game 6 decisivo de las Finales)' },
      { icon: 'shield', name: '1er Equipo NBA All-Defensive', count: 1, details: '2023' },
      { icon: 'shield', name: '2º Equipo NBA All-Defensive', count: 1, details: '2024' },
      { icon: 'ribbon', name: 'NBA Hustle Award Winner', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '10.1',
      reb: '3.8',
      ast: '3.5',
      stl: '1.7',
      blk: '1.0',
      fgPct: '46.8%',
      threePct: '40.8%',
      ftPct: '76.0%',
    },
  },

  // ==========================================
  // PORTLAND TRAIL BLAZERS (POR)
  // ==========================================
  'Damian Lillard': {
    tacticalRole: 'Base Superestrella de Élite Histórica & Asesino en el Último Segundo (Dame Time)',
    specialty: 'Triples desde 10 metros, sangre fría absoluta en instantes decisivos y liderazgo legendario',
    playStyle: 'Uno de los tiradores y anotadores clutch más temidos y respetados en la historia de la NBA',
    draftInfo: {
      year: 2012,
      round: 1,
      pick: 6,
      teamName: 'Portland Trail Blazers',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'Weber State Wildcats / Oakland, California',
    },
    draft: '2012 · Pick #6 (1ª Ronda por Portland Trail Blazers)',
    experience: '13 Temporadas (Trail Blazers / Bucks / Trail Blazers)',
    transfers: [
      {
        season: '12/13',
        date: '28/06/2012',
        fromTeam: 'Weber State',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '13,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 6)',
      },
      {
        season: '23/24',
        date: '27/09/2023',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '216,00 mill. $',
        feeOrType: 'Mega-Traspaso a 3 Bandas',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Milwaukee Bucks',
        fromTeamAbbr: 'MIL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '122,00 mill. $',
        feeOrType: 'Regreso Histórico a Portland',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
      { icon: 'star', name: '8x NBA All-Star (MVP del All-Star Game 2024)', count: 8, details: '2014, 2015, 2018, 2019, 2020, 2021, 2023, 2024' },
      { icon: 'albums', name: '7x Seleccionado All-NBA (1er Equipo 2018, 4x 2º Equipo, 2x 3er Equipo)', count: 7, details: '2014-2023' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Tokio 2020' },
      { icon: 'trophy', name: '2x Campeón Concurso de Triples NBA All-Star (3-Point Contest)', count: 2, details: '2023, 2024' },
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY Unánime)', count: 1, details: '2013' },
      { icon: 'flame', name: 'Máximo Anotador Histórico de Portland Trail Blazers', count: 1, details: '+19.000 Puntos con la franquicia' },
    ],
    seasonAverages: {
      pts: '24.3',
      reb: '4.4',
      ast: '7.0',
      stl: '1.0',
      blk: '0.2',
      fgPct: '42.4%',
      threePct: '35.4%',
      ftPct: '92.0%',
    },
  },

  'Ja Morant': {
    tacticalRole: 'Base Superestrella Eléctrico & Atleta Acrobático Sobrenatural (G12)',
    specialty: 'Salto vertical estratosférico, penetraciones acrobáticas imposibles en el aro y pases en el aire',
    playStyle: 'Uno de los bases más explosivos y dinámicos que jamás haya pisado una cancha de la NBA',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 2,
      teamName: 'Memphis Grizzlies',
      teamAbbr: 'MEM',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
      origin: 'Murray State Racers',
    },
    draft: '2019 · Pick #2 (1ª Ronda por Memphis Grizzlies)',
    experience: '6 Temporadas (Grizzlies / Trail Blazers)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Murray State',
        toTeam: 'Memphis Grizzlies',
        toTeamAbbr: 'MEM',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        marketValue: '39,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 2)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Memphis Grizzlies',
        fromTeamAbbr: 'MEM',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '197,00 mill. $',
        feeOrType: 'Traspaso de Superestrella',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2020' },
      { icon: 'star', name: '2x NBA All-Star (Titular 2022)', count: 2, details: '2022, 2023' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2022' },
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2022' },
      { icon: 'flame', name: 'Partido de 52 Puntos en Temporada Regular', count: 1, details: '28/02/2022 vs San Antonio Spurs' },
    ],
    seasonAverages: {
      pts: '25.1',
      reb: '5.6',
      ast: '8.1',
      stl: '1.1',
      blk: '0.6',
      fgPct: '47.1%',
      threePct: '31.8%',
      ftPct: '81.3%',
    },
  },

  'Jrue Holiday': {
    tacticalRole: 'Base / Escolta 2x Campeón de la NBA & 2x Medallista de Oro Olímpico (The Kung Fu Jrue)',
    specialty: 'Defensa al hombre legendaria (elogiado por Durant y Lillard como el mejor defensor), triples clutch y pases',
    playStyle: 'El pegamento de campeonato definitivo: 2 anillos de la NBA con franquicias diferentes y 2 oros olímpicos',
    draftInfo: {
      year: 2009,
      round: 1,
      pick: 17,
      teamName: 'Philadelphia 76ers',
      teamAbbr: 'PHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
      origin: 'UCLA Bruins',
    },
    draft: '2009 · Pick #17 (1ª Ronda por Philadelphia 76ers)',
    experience: '16 Temporadas (76ers / Pelicans / Bucks / Celtics / Trail Blazers)',
    transfers: [
      {
        season: '09/10',
        date: '25/06/2009',
        fromTeam: 'UCLA Bruins',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '7,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 17)',
      },
      {
        season: '20/21',
        date: '24/11/2020',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '135,00 mill. $',
        feeOrType: 'Traspaso a 4 Bandas (Pieza clave del anillo 2021)',
      },
      {
        season: '23/24',
        date: '01/10/2023',
        fromTeam: 'Milwaukee Bucks',
        fromTeamAbbr: 'MIL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '135,00 mill. $',
        feeOrType: 'Traspaso (por Robert Williams + Malcolm Brogdon + 2 primeras)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '135,00 mill. $',
        feeOrType: 'Traspaso de Leyenda Defensiva',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón de la NBA', count: 2, details: '2021 (Milwaukee Bucks), 2024 (Boston Celtics — Anillo #18 histórico)' },
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Tokio 2020, París 2024' },
      { icon: 'star', name: '2x NBA All-Star', count: 2, details: '2013, 2023' },
      { icon: 'shield', name: '6x NBA All-Defensive Team (3x 1er Equipo, 3x 2º Equipo)', count: 6, details: '2018, 2021, 2023 (1º) / 2019, 2022, 2024 (2º)' },
      { icon: 'ribbon', name: '3x Premio Compañero del Año Twyman-Stokes', count: 3, details: '2020, 2022, 2023' },
    ],
    seasonAverages: {
      pts: '12.5',
      reb: '5.4',
      ast: '4.8',
      stl: '0.9',
      blk: '0.8',
      fgPct: '48.0%',
      threePct: '42.9%',
      ftPct: '83.3%',
    },
  },

  'Donovan Clingan': {
    tacticalRole: 'Pívot Gigante Protector de Aro & 2x Campeón Consecutivo de la NCAA (Big Cling)',
    specialty: 'Envergadura de 2,33m, tapones sin despegarse del suelo, colocación de pantallas y rebote',
    playStyle: 'Torre defensiva masiva con pedigrí inmaculado de campeón universitario',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 7,
      teamName: 'Portland Trail Blazers',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'UConn Huskies / Bristol, Connecticut',
    },
    draft: '2024 · Pick #7 (1ª Ronda por Portland Trail Blazers)',
    experience: '2 Temporadas (Portland Trail Blazers)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'UConn Huskies',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '31,30 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7 — Contrato Rookie Escala 4 años)',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón Consecutivo de la NCAA', count: 2, details: '2023, 2024 (UConn Huskies — Dominio histórico del torneo)' },
      { icon: 'shield', name: 'NCAA All-Tournament Team & East Regional MOP', count: 1, details: '2024' },
      { icon: 'albums', name: 'Big East All-Defensive Team', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '8.5',
      reb: '7.8',
      ast: '1.2',
      stl: '0.4',
      blk: '2.1',
      fgPct: '57.0%',
      threePct: '0.0%',
      ftPct: '60.0%',
    },
  },

  // ==========================================
  // UTAH JAZZ (UTA)
  // ==========================================
  'Jaren Jackson Jr.': {
    tacticalRole: 'Ala-Pívot / Pívot Defensor del Año de la NBA & Máximo Taponador (Trip J)',
    specialty: 'Tapones por doquier (líder de la NBA), triples frontales en pick-and-pop y defensa posicional',
    playStyle: 'El mejor taponador y defensor versátil de la liga con amenaza letal de tres puntos',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 4,
      teamName: 'Memphis Grizzlies',
      teamAbbr: 'MEM',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
      origin: 'Michigan State Spartans',
    },
    draft: '2018 · Pick #4 (1ª Ronda por Memphis Grizzlies)',
    experience: '7 Temporadas (Grizzlies / Jazz)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Michigan State',
        toTeam: 'Memphis Grizzlies',
        toTeamAbbr: 'MEM',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        marketValue: '29,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Memphis Grizzlies',
        fromTeamAbbr: 'MEM',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '105,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'shield', name: 'Mejor Defensor del Año de la NBA (DPOY)', count: 1, details: '2023' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2023' },
      { icon: 'shield', name: '2x 1er Equipo NBA All-Defensive', count: 2, details: '2022, 2023' },
      { icon: 'flame', name: '2x Máximo Taponador de la NBA (Blocks Leader)', count: 2, details: '2022 (2.3 tpp), 2023 (3.0 tpp)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2019' },
    ],
    seasonAverages: {
      pts: '22.5',
      reb: '5.5',
      ast: '2.3',
      stl: '1.2',
      blk: '1.6',
      fgPct: '44.4%',
      threePct: '32.0%',
      ftPct: '80.8%',
    },
  },

  'Lauri Markkanen': {
    tacticalRole: 'Ala-Pívot All-Star Francotirador & Jugador Más Mejorado (The Finnisher)',
    specialty: 'Triples en salida de bloqueo con 2,13m de altura, penetraciones contundentes y rebote',
    playStyle: 'Tirador de 7 pies imparable y líder absoluto de la ofensiva de Utah Jazz',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 7,
      teamName: 'Minnesota Timberwolves (Traspasado a Bulls)',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'Arizona Wildcats / Finlandia',
    },
    draft: '2017 · Pick #7 (1ª Ronda por Minnesota Timberwolves)',
    experience: '8 Temporadas (Bulls / Cavaliers / Jazz)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Arizona Wildcats',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '20,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7 / Traspaso Jimmy Butler)',
      },
      {
        season: '22/23',
        date: '01/09/2022',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '67,00 mill. $',
        feeOrType: 'Mega-Traspaso Donovan Mitchell',
      },
      {
        season: '24/25',
        date: '07/08/2024',
        fromTeam: 'Utah Jazz',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '238,00 mill. $',
        feeOrType: 'Extensión y Renegociación Histórica (5 años / $238M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2023 (Utah Jazz)' },
      { icon: 'star', name: 'NBA All-Star (Titular en Salt Lake City)', count: 1, details: '2023' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2018' },
      { icon: 'medal', name: 'Estrella de la Selección de Finlandia (Susijengi)', count: 1, details: 'EuroBasket / Mundial FIBA' },
    ],
    seasonAverages: {
      pts: '23.2',
      reb: '8.2',
      ast: '2.0',
      stl: '0.9',
      blk: '0.5',
      fgPct: '48.0%',
      threePct: '39.9%',
      ftPct: '89.9%',
    },
  },

  'Keyonte George': {
    tacticalRole: 'Base / Escolta Anotador con Rango Ilimitado & 2º Equipo All-Rookie',
    specialty: 'Tiro de tres tras bote en step-back, flotadoras y distribución en pick-and-roll',
    playStyle: 'Creador ofensivo moderno dinámico con gran instinto anotador',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 16,
      teamName: 'Utah Jazz',
      teamAbbr: 'UTA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
      origin: 'Baylor Bears',
    },
    draft: '2023 · Pick #16 (1ª Ronda por Utah Jazz)',
    experience: '2 Temporadas (Utah Jazz)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Baylor Bears',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '18,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 16)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2024' },
      { icon: 'sparkles', name: 'Big 12 Freshman of the Year', count: 1, details: '2023 (Baylor)' },
    ],
    seasonAverages: {
      pts: '13.0',
      reb: '2.8',
      ast: '4.4',
      stl: '0.5',
      blk: '0.1',
      fgPct: '39.1%',
      threePct: '33.4%',
      ftPct: '84.8%',
    },
  },

  'Svi Mykhailiuk': {
    tacticalRole: 'Escolta Tirador de Perímetro & Campeón de la NBA',
    specialty: 'Triples en carrera, tiro rápido de catch-and-shoot y circulación de balón',
    playStyle: 'Especialista en tiro exterior con anillo de campeón de Boston',
    draftInfo: {
      year: 2018,
      round: 2,
      pick: 47,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Kansas Jayhawks / Ucrania',
    },
    draft: '2018 · Pick #47 (2ª Ronda por Los Angeles Lakers)',
    experience: '7 Temporadas (Lakers / Pistons / Thunder / Raptors / Knicks / Hornets / Celtics / Jazz)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Kansas Jayhawks',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '4,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 47)',
      },
      {
        season: '23/24',
        date: '31/08/2023',
        fromTeam: 'Charlotte Hornets',
        fromTeamAbbr: 'CHA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '2,00 mill. $',
        feeOrType: 'Agencia Libre (Campeón de la NBA 2024)',
      },
      {
        season: '24/25',
        date: '13/08/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '15,00 mill. $',
        feeOrType: 'Agencia Libre (4 años / $15M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Anillo #18 histórico)' },
      { icon: 'albums', name: '2º Equipo All-Big 12', count: 1, details: '2018 (Kansas)' },
    ],
    seasonAverages: {
      pts: '7.0',
      reb: '1.8',
      ast: '1.2',
      stl: '0.4',
      blk: '0.1',
      fgPct: '42.0%',
      threePct: '39.0%',
      ftPct: '85.0%',
    },
  },

  'Jusuf Nurkic': {
    tacticalRole: 'Pívot Clásico Fuerte, Distribuidor desde el Poste & Protector Interior (The Bosnian Beast)',
    specialty: 'Pases desde la cabecera, pantallas rocosas, rebote contundente y anotación al poste',
    playStyle: 'Pívot dominante tradicional de la escuela balcánica',
    draftInfo: {
      year: 2014,
      round: 1,
      pick: 16,
      teamName: 'Chicago Bulls (Traspasado a Nuggets)',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'Cedevita Zagreb / Bosnia y Herzegovina',
    },
    draft: '2014 · Pick #16 (1ª Ronda por Chicago Bulls)',
    experience: '11 Temporadas (Nuggets / Trail Blazers / Suns / Jazz)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'Cedevita Zagreb',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '8,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 16 / Traspasado con Gary Harris por Doug McDermott)',
      },
      {
        season: '16/17',
        date: '13/02/2017',
        fromTeam: 'Denver Nuggets',
        fromTeamAbbr: 'DEN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '48,00 mill. $',
        feeOrType: 'Traspaso (por Mason Plumlee + 2ª ronda)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '70,00 mill. $',
        feeOrType: 'Traspaso de Pívot Titular',
      },
    ],
    awards: [
      { icon: 'flame', name: 'Partido Histórico 5x5 en la NBA', count: 1, details: '01/01/2019 (24 pts, 23 reb, 7 ast, 5 robos, 5 tapones)' },
      { icon: 'flame', name: 'Récord de Rebotes de los Phoenix Suns', count: 1, details: '31 rebotes en un solo partido (03/03/2024 vs OKC)' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2015' },
    ],
    seasonAverages: {
      pts: '11.0',
      reb: '11.0',
      ast: '4.0',
      stl: '1.1',
      blk: '1.1',
      fgPct: '51.0%',
      threePct: '24.4%',
      ftPct: '64.0%',
    },
  },
};
