import { PlayerDossier } from './playerDossier';

export const ATLANTIC_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // BOSTON CELTICS (BOS)
  // ==========================================
  'Jayson Tatum': {
    tacticalRole: 'Alero Superestrella & Creador Principal (Taco Jay)',
    specialty: 'Anotación en tres niveles, tiro tras bote en aclarado, rebote y defensa perimetral de élite',
    playStyle: 'Alero total moderno, 1er Equipo All-NBA indiscutible y líder del campeonato de los Celtics',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 3,
      teamName: 'Boston Celtics',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Duke Blue Devils',
    },
    draft: '2017 · Pick #3 (1ª Ronda por Boston Celtics)',
    experience: '8 Temporadas (Boston Celtics)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '30,07 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3 — 4 años / $30.1M)',
      },
      {
        season: '21/22',
        date: '22/11/2020',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '195,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $195M)',
      },
      {
        season: '25/26',
        date: '01/07/2024',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '314,00 mill. $',
        feeOrType: 'Supermax Extension Histórica (5 años / $314M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Anillo #18 histórico de la franquicia)' },
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Tokio 2020, París 2024' },
      { icon: 'ribbon', name: 'MVP de Finales de Conferencia Este (Larry Bird Trophy)', count: 1, details: '2022' },
      { icon: 'star', name: 'NBA All-Star', count: 5, details: '2020, 2021, 2022, 2023, 2024' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 3, details: '2022, 2023, 2024' },
      { icon: 'sparkles', name: 'MVP del All-Star Game (Récord Histórico de 55 Puntos)', count: 1, details: '2023 (Kobe Bryant MVP Trophy)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2018' },
    ],
    seasonAverages: {
      pts: '26.9',
      reb: '8.1',
      ast: '4.9',
      stl: '1.0',
      blk: '0.6',
      fgPct: '47.1%',
      threePct: '37.6%',
      ftPct: '83.3%',
    },
  },

  'Derrick White': {
    tacticalRole: 'Combo Guard Defensivo de Élite & Francotirador Clutch',
    specialty: 'Bloqueo defensivo perimetral, IQ táctico superior, tapones siendo guard y triples de esquina',
    playStyle: 'Factor X defensivo total, especialista en playoffs y pegamento táctico de campeonato',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 29,
      teamName: 'San Antonio Spurs',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'Colorado Buffaloes',
    },
    draft: '2017 · Pick #29 (1ª Ronda por San Antonio Spurs)',
    experience: '8 Temporadas (Spurs / Celtics)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Colorado Buffaloes',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '8,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 29)',
      },
      {
        season: '21/22',
        date: '10/02/2022',
        fromTeam: 'San Antonio Spurs',
        fromTeamAbbr: 'SAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '70,00 mill. $',
        feeOrType: 'Traspaso (por Josh Richardson + Romeo Langford + 1ª ronda)',
      },
      {
        season: '24/25',
        date: '01/07/2024',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '126,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $126M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024' },
      { icon: 'shield', name: '2x 2º Equipo All-Defensive de la NBA', count: 2, details: '2023, 2024' },
    ],
    seasonAverages: {
      pts: '15.2',
      reb: '4.2',
      ast: '5.2',
      stl: '1.0',
      blk: '1.2',
      fgPct: '46.1%',
      threePct: '39.6%',
      ftPct: '90.1%',
    },
  },

  'Paul George': {
    tacticalRole: 'Alero All-NBA Bidireccional de Élite (PG13)',
    specialty: 'Anotación en aclarados, crossover suave, tiro de tres puntos letal y robos en primera línea',
    playStyle: 'Alero legendario 3&D puro con capacidad anotadora de 25+ puntos por noche',
    draftInfo: {
      year: 2010,
      round: 1,
      pick: 10,
      teamName: 'Indiana Pacers',
      teamAbbr: 'IND',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
      origin: 'Fresno State Bulldogs',
    },
    draft: '2010 · Pick #10 (1ª Ronda por Indiana Pacers)',
    experience: '15 Temporadas (Pacers / Thunder / Clippers / Celtics)',
    transfers: [
      {
        season: '10/11',
        date: '24/06/2010',
        fromTeam: 'Fresno State',
        toTeam: 'Indiana Pacers',
        toTeamAbbr: 'IND',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        marketValue: '10,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10)',
      },
      {
        season: '17/18',
        date: '06/07/2017',
        fromTeam: 'Indiana Pacers',
        fromTeamAbbr: 'IND',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '137,00 mill. $',
        feeOrType: 'Traspaso (por Victor Oladipo + Domantas Sabonis)',
      },
      {
        season: '19/20',
        date: '10/07/2019',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '190,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Shai Gilgeous-Alexander + 5 primeras rondas)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '212,00 mill. $',
        feeOrType: 'Agencia Libre (Contrato Máximo 4 años / $212M)',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 9, details: '2013-2014, 2016-2019, 2021, 2023, 2024' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 1, details: '2019' },
      { icon: 'albums', name: 'Selecciones All-NBA Totales', count: 6, details: '2013, 2014, 2016, 2018, 2019, 2021' },
      { icon: 'shield', name: '1er Equipo All-Defensive de la NBA', count: 2, details: '2014, 2019' },
      { icon: 'flame', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2013 (Indiana Pacers)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Río 2016' },
    ],
    seasonAverages: {
      pts: '22.6',
      reb: '5.2',
      ast: '3.5',
      stl: '1.5',
      blk: '0.5',
      fgPct: '47.1%',
      threePct: '41.3%',
      ftPct: '90.7%',
    },
  },

  'Payton Pritchard': {
    tacticalRole: 'Microondas Anotador & Especialista en Tiros Lejanos (Fast PP)',
    specialty: 'Tiro de tres con rango ilimitado, buzzer-beaters desde media cancha y energía implacable',
    playStyle: 'Revolucionario de banquillo y 6º hombre de impacto inmediato',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 26,
      teamName: 'Boston Celtics',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Oregon Ducks',
    },
    draft: '2020 · Pick #26 (1ª Ronda por Boston Celtics)',
    experience: '5 Temporadas (Boston Celtics)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Oregon Ducks',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '10,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 26)',
      },
      {
        season: '23/24',
        date: '08/10/2023',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '30,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $30M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — 2 buzzer-beaters en las Finales)' },
      { icon: 'ribbon', name: '2x Campeón de Conferencia Este', count: 2, details: '2022, 2024' },
      { icon: 'sparkles', name: 'Premio Bob Cousy al Mejor Base Universitario', count: 1, details: '2020 (Oregon Ducks)' },
      { icon: 'albums', name: '1er Equipo All-American Consensus', count: 1, details: '2020' },
    ],
    seasonAverages: {
      pts: '14.1',
      reb: '3.2',
      ast: '3.4',
      stl: '0.8',
      blk: '0.1',
      fgPct: '46.8%',
      threePct: '41.2%',
      ftPct: '83.1%',
    },
  },

  'Mitchell Robinson': {
    tacticalRole: 'Pívot Protector del Aro & Monstruo del Rebote Ofensivo',
    specialty: 'Rebote ofensivo de élite histórica, tapones en ayudas y finalización de alley-oops por encima del aro',
    playStyle: 'Ancla interior de pintura y destructor de segundas oportunidades rivales',
    draftInfo: {
      year: 2018,
      round: 2,
      pick: 36,
      teamName: 'New York Knicks',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Chalmette High School (Luisiana)',
    },
    draft: '2018 · Pick #36 (2ª Ronda por New York Knicks)',
    experience: '7 Temporadas (Knicks / Celtics)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Chalmette HS',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '6,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 36)',
      },
      {
        season: '22/23',
        date: '08/07/2022',
        fromTeam: 'New York Knicks',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Renovación Multianual (4 años / $60M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: 'NBA All-Rookie 2º Equipo', count: 1, details: '2019' },
      { icon: 'flame', name: 'Récord Histórico NBA en % Tiros de Campo en una Temporada (74.2%)', count: 1, details: '2019-20 (Superando a Wilt Chamberlain)' },
    ],
    seasonAverages: {
      pts: '7.8',
      reb: '9.4',
      ast: '0.8',
      stl: '1.2',
      blk: '1.8',
      fgPct: '68.5%',
      threePct: '0.0%',
      ftPct: '58.4%',
    },
  },

  'Mike Conley': {
    tacticalRole: 'Director de Juego Veterano & Maestro del Pick and Roll (Mountain Mike)',
    specialty: 'Control del tempo, pase milimétrico, floater con la zurda y liderazgo intachable',
    playStyle: 'General en cancha respetado por toda la liga, cerebral y líder de vestuario',
    draftInfo: {
      year: 2007,
      round: 1,
      pick: 4,
      teamName: 'Memphis Grizzlies',
      teamAbbr: 'MEM',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
      origin: 'Ohio State Buckeyes',
    },
    draft: '2007 · Pick #4 (1ª Ronda por Memphis Grizzlies)',
    experience: '18 Temporadas (Grizzlies / Jazz / Timberwolves / Celtics)',
    transfers: [
      {
        season: '07/08',
        date: '28/06/2007',
        fromTeam: 'Ohio State',
        toTeam: 'Memphis Grizzlies',
        toTeamAbbr: 'MEM',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        marketValue: '15,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4)',
      },
      {
        season: '16/17',
        date: '14/07/2016',
        fromTeam: 'Memphis Grizzlies',
        toTeam: 'Memphis Grizzlies',
        toTeamAbbr: 'MEM',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        marketValue: '153,00 mill. $',
        feeOrType: 'Contrato Más Grande en la Historia NBA en su momento (5 años / $153M)',
      },
      {
        season: '19/20',
        date: '06/07/2019',
        fromTeam: 'Memphis Grizzlies',
        fromTeamAbbr: 'MEM',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '68,00 mill. $',
        feeOrType: 'Traspaso (por Jae Crowder + Kyle Korver + Grayson Allen)',
      },
      {
        season: '24/25',
        date: '05/07/2024',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '21,00 mill. $',
        feeOrType: 'Traspaso de Veterano',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2021 (Utah Jazz)' },
      { icon: 'shield', name: '2º Equipo All-Defensive de la NBA', count: 1, details: '2013 (Memphis Grizzlies Grit & Grind)' },
      { icon: 'sparkles', name: '4x Premio a la Deportividad NBA (Joe Dumars Trophy)', count: 4, details: '2014, 2016, 2019, 2023' },
      { icon: 'ribbon', name: '2x Premio Compañero del Año Twyman-Stokes', count: 2, details: '2019, 2024' },
    ],
    seasonAverages: {
      pts: '11.4',
      reb: '2.9',
      ast: '5.9',
      stl: '1.2',
      blk: '0.2',
      fgPct: '45.7%',
      threePct: '44.2%',
      ftPct: '91.1%',
    },
  },

  'Sam Hauser': {
    tacticalRole: 'Francotirador de Perímetro Especialista (Sniper Hauser)',
    specialty: 'Liberación ultra-rápida tras bloqueo indirecto, 40%+ en triples y defensa posicional disciplinada',
    playStyle: 'Tirador letal de élite absoluta y espaciador clave del quinteto de Boston',
    draftInfo: {
      year: 2021,
      round: 0,
      pick: 0,
      teamName: 'Boston Celtics (Undrafted)',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Virginia Cavaliers / Marquette',
    },
    draft: '2021 · Agente Libre No Drafteado (Fichado por Boston Celtics)',
    experience: '4 Temporadas (Boston Celtics)',
    transfers: [
      {
        season: '21/22',
        date: '13/08/2021',
        fromTeam: 'Virginia Cavaliers',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Two-Way Contract / Rookie Free Agent',
      },
      {
        season: '24/25',
        date: '21/07/2024',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '45,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $45M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics)' },
      { icon: 'ribbon', name: '2x Campeón de Conferencia Este', count: 2, details: '2022, 2024' },
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA', count: 1, details: '2019 (Virginia Cavaliers)' },
      { icon: 'sparkles', name: '1er Equipo All-ACC', count: 1, details: '2021 (Virginia)' },
    ],
    seasonAverages: {
      pts: '9.0',
      reb: '3.5',
      ast: '1.0',
      stl: '0.5',
      blk: '0.3',
      fgPct: '44.6%',
      threePct: '42.4%',
      ftPct: '89.5%',
    },
  },

  'Neemias Queta': {
    tacticalRole: 'Pívot Intimidador & Primer Jugador Portugués en la NBA',
    specialty: 'Presencia física imponente (2,13m), taponador nato, reboteador y finalizador cerca del aro',
    playStyle: 'Pívot clásico reboteador y bloqueador de gran energía',
    draftInfo: {
      year: 2021,
      round: 2,
      pick: 39,
      teamName: 'Sacramento Kings',
      teamAbbr: 'SAC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
      origin: 'Utah State Aggies',
    },
    draft: '2021 · Pick #39 (2ª Ronda por Sacramento Kings)',
    experience: '4 Temporadas (Kings / Celtics)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Utah State',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '4,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 39 — Primer portugués en ser drafteado)',
      },
      {
        season: '23/24',
        date: '19/09/2023',
        fromTeam: 'Sacramento Kings',
        fromTeamAbbr: 'SAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '7,20 mill. $',
        feeOrType: 'Agencia Libre / Two-Way a Contrato Estándar',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Primer portugués campeón en la historia de la NBA)' },
      { icon: 'shield', name: '2x Jugador Defensivo del Año Mountain West', count: 2, details: '2019, 2021 (Utah State)' },
    ],
    seasonAverages: {
      pts: '5.5',
      reb: '4.4',
      ast: '0.7',
      stl: '0.5',
      blk: '0.8',
      fgPct: '64.4%',
      threePct: '0.0%',
      ftPct: '71.4%',
    },
  },

  'Jordan Walsh': {
    tacticalRole: 'Alero Defensivo Energético & Campeón NBA',
    specialty: 'Defensa con 2,18m de envergadura, versatilidad en cambios defensivos y rebote',
    playStyle: 'Especialista defensivo joven de alta intensidad',
    draftInfo: {
      year: 2023,
      round: 2,
      pick: 38,
      teamName: 'Sacramento Kings (Traspasado a Celtics)',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'Arkansas Razorbacks',
    },
    draft: '2023 · Pick #38 (2ª Ronda por Boston Celtics)',
    experience: '2 Temporadas (Boston Celtics)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Arkansas Razorbacks',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '7,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 38)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics)' },
      { icon: 'sparkles', name: 'McDonald\'s All-American', count: 1, details: '2022' },
    ],
    seasonAverages: {
      pts: '4.2',
      reb: '2.3',
      ast: '0.6',
      stl: '0.5',
      blk: '0.3',
      fgPct: '43.0%',
      threePct: '33.0%',
      ftPct: '75.0%',
    },
  },

  'Luka Garza': {
    tacticalRole: 'Pívot Anotador de Pintura & Mejor Jugador Universitario 2021',
    specialty: 'Anotación al poste, ganchos de ambas manos, rebote ofensivo y tiro exterior',
    playStyle: 'Pívot clásico anotador con dominio prolífico en la pintura',
    draftInfo: {
      year: 2021,
      round: 2,
      pick: 52,
      teamName: 'Detroit Pistons',
      teamAbbr: 'DET',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
      origin: 'Iowa Hawkeyes / Bosnia y Herzegovina',
    },
    draft: '2021 · Pick #52 (2ª Ronda por Detroit Pistons)',
    experience: '4 Temporadas (Pistons / Timberwolves / Celtics)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Iowa Hawkeyes',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '2,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 52)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '4,50 mill. $',
        feeOrType: 'Contrato Multianual',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Jugador Nacional del Año Universitario (Naismith / Wooden / AP)', count: 1, details: '2021 (Iowa Hawkeyes — Dominador unánime de la NCAA)' },
      { icon: 'sparkles', name: 'MVP del All-Star Game de la NBA G-League', count: 1, details: '2023' },
      { icon: 'trophy', name: 'Premio Kareem Abdul-Jabbar al Mejor Pívot Universitario', count: 2, details: '2020, 2021' },
      { icon: 'albums', name: '2x 1er Equipo All-American Unánime', count: 2, details: '2020, 2021' },
    ],
    seasonAverages: {
      pts: '7.5',
      reb: '3.8',
      ast: '0.6',
      stl: '0.3',
      blk: '0.4',
      fgPct: '54.5%',
      threePct: '34.8%',
      ftPct: '79.2%',
    },
  },

  // ==========================================
  // BROOKLYN NETS (BKN)
  // ==========================================
  'Michael Porter Jr.': {
    tacticalRole: 'Alero Anotador Letal de 2,08m (MPJ)',
    specialty: 'Tiro exterior incontestable por altura, anotación catch-and-shoot de calibre élite y rebote',
    playStyle: 'Tirador puro de élite mundial con estatura de pívot y campeón NBA',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 14,
      teamName: 'Denver Nuggets',
      teamAbbr: 'DEN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
      origin: 'Missouri Tigers',
    },
    draft: '2018 · Pick #14 (1ª Ronda por Denver Nuggets)',
    experience: '7 Temporadas (Nuggets / Nets)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Missouri Tigers',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '15,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 14)',
      },
      {
        season: '22/23',
        date: '29/09/2021',
        fromTeam: 'Denver Nuggets',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '179,00 mill. $',
        feeOrType: 'Designated Max Rookie Extension (5 años / $179M)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Denver Nuggets',
        fromTeamAbbr: 'DEN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '179,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2023 (Denver Nuggets — Primer anillo en la historia de la franquicia)' },
      { icon: 'ribbon', name: 'Campeón de la Conferencia Oeste', count: 1, details: '2023' },
      { icon: 'sparkles', name: 'Naismith Prep Player of the Year', count: 1, details: '2017 (Mejor Jugador de High School de USA)' },
      { icon: 'medal', name: 'MVP del McDonald\'s All-American Game', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '17.8',
      reb: '7.0',
      ast: '1.5',
      stl: '0.6',
      blk: '0.7',
      fgPct: '48.4%',
      threePct: '40.7%',
      ftPct: '83.6%',
    },
  },

  'Julius Randle': {
    tacticalRole: 'Ala-Pívot Físico & Creador Principal (Don Julio)',
    specialty: 'Juego al poste bajo, fuerza en penetración, tiro de media distancia y generación de juego',
    playStyle: 'Bully ball moderno, 2x All-NBA y referente interior de alto impacto',
    draftInfo: {
      year: 2014,
      round: 1,
      pick: 7,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2014 · Pick #7 (1ª Ronda por Los Angeles Lakers)',
    experience: '11 Temporadas (Lakers / Pelicans / Knicks / Nets)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '13,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7)',
      },
      {
        season: '19/20',
        date: '09/07/2019',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '62,00 mill. $',
        feeOrType: 'Agencia Libre (3 años / $62M)',
      },
      {
        season: '22/23',
        date: '01/07/2022',
        fromTeam: 'New York Knicks',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '117,00 mill. $',
        feeOrType: 'Extensión Multianual (4 años / $117M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '117,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 3, details: '2021, 2023, 2024' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2021' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2023' },
      { icon: 'flame', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2021 (New York Knicks)' },
    ],
    seasonAverages: {
      pts: '24.0',
      reb: '9.2',
      ast: '5.0',
      stl: '0.6',
      blk: '0.3',
      fgPct: '47.2%',
      threePct: '33.8%',
      ftPct: '81.1%',
    },
  },

  'Moritz Wagner': {
    tacticalRole: 'Pívot Pasional & Campeón del Mundo FIBA (Mo Wagner)',
    specialty: 'Provocar faltas en ataque, pick-and-pop letal, intensidad enérgica y juego físico',
    playStyle: 'Pívot agitador que cambia el ritmo del partido desde la pintura',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 25,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Michigan Wolverines / Alemania',
    },
    draft: '2018 · Pick #25 (1ª Ronda por Los Angeles Lakers)',
    experience: '7 Temporadas (Lakers / Wizards / Celtics / Magic / Nets)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Michigan Wolverines',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '9,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 25)',
      },
      {
        season: '21/22',
        date: '27/04/2021',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Orlando Magic',
        toTeamAbbr: 'ORL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        marketValue: '16,00 mill. $',
        feeOrType: 'Agente Libre (2 años / $16M)',
      },
      {
        season: '24/25',
        date: '02/07/2024',
        fromTeam: 'Orlando Magic',
        fromTeamAbbr: 'ORL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '22,00 mill. $',
        feeOrType: 'Contrato Multianual (2 años / $22M)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Campeón de la Copa del Mundo FIBA (Oro Histórico con Alemania)', count: 1, details: 'Manila 2023 (Récord Invictos 8-0)' },
      { icon: 'sparkles', name: 'MVP del Torneo Big Ten NCAA', count: 1, details: '2018 (Michigan Wolverines)' },
      { icon: 'trophy', name: 'Final Four NCAA', count: 1, details: '2018 (Finalista Nacional con Michigan)' },
    ],
    seasonAverages: {
      pts: '10.9',
      reb: '4.3',
      ast: '1.2',
      stl: '0.5',
      blk: '0.3',
      fgPct: '60.1%',
      threePct: '33.0%',
      ftPct: '81.4%',
    },
  },

  'Ben Saraf': {
    tacticalRole: 'Base Creador Prodigio & MVP Europeo',
    specialty: 'Visión de juego magistral, anotación compulsiva en penetración y pick and roll de élite',
    playStyle: 'Joya europea del baloncesto internacional con techo de superestrella',
    draftInfo: {
      year: 2025,
      round: 1,
      pick: 15,
      teamName: 'Brooklyn Nets',
      teamAbbr: 'BKN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
      origin: 'Ratiopharm Ulm / Israel',
    },
    draft: '2025 · Pick de 1ª Ronda por Brooklyn Nets',
    experience: '1 Temporada (Ratiopharm Ulm / Nets)',
    transfers: [
      {
        season: '24/25',
        date: '01/07/2024',
        fromTeam: 'Elitzur Netanya',
        toTeam: 'Ratiopharm Ulm',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '3,50 mill. $',
        feeOrType: 'Fichaje Internacional',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'MVP del EuroBasket Sub-18 FIBA', count: 1, details: '2024 (Tampere — Máximo anotador con 28.1 pts/partido)' },
      { icon: 'flame', name: 'Máximo Anotador del EuroBasket U18', count: 1, details: '2024 (Partido histórico de 40 puntos en semifinales)' },
    ],
    seasonAverages: {
      pts: '13.5',
      reb: '3.8',
      ast: '4.8',
      stl: '1.3',
      blk: '0.2',
      fgPct: '47.5%',
      threePct: '34.2%',
      ftPct: '78.0%',
    },
  },

  // ==========================================
  // NEW YORK KNICKS (NYK)
  // ==========================================
  'Jalen Brunson': {
    tacticalRole: 'Base Superestrella & Capitán de la Gran Manzana (Brunson Burner)',
    specialty: 'Juego de pies inigualable en la pintura, tiro en suspensión tras freno, triples clutch y liderazgo',
    playStyle: 'Anotador implacable de playoffs, 40+ puntos constantes en postemporada y héroe del Madison Square Garden',
    draftInfo: {
      year: 2018,
      round: 2,
      pick: 33,
      teamName: 'Dallas Mavericks',
      teamAbbr: 'DAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
      origin: 'Villanova Wildcats',
    },
    draft: '2018 · Pick #33 (2ª Ronda por Dallas Mavericks)',
    experience: '7 Temporadas (Mavericks / Knicks)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Villanova Wildcats',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '6,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 33)',
      },
      {
        season: '22/23',
        date: '12/07/2022',
        fromTeam: 'Dallas Mavericks',
        fromTeamAbbr: 'DAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '104,00 mill. $',
        feeOrType: 'Agencia Libre (4 años / $104M — Fichaje Histórico)',
      },
      {
        season: '24/25',
        date: '12/07/2024',
        fromTeam: 'New York Knicks',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '156,50 mill. $',
        feeOrType: 'Extensión Descuento Pro-Equipo (4 años / $156.5M para armar equipo contendiente)',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2024 (Titular de la Conferencia Este)' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2024' },
      { icon: 'trophy', name: '2x Campeón Nacional de la NCAA', count: 2, details: '2016, 2018 (Villanova Wildcats)' },
      { icon: 'ribbon', name: 'Jugador Nacional del Año Universitario (Naismith / Wooden / AP)', count: 1, details: '2018' },
      { icon: 'flame', name: 'Récord de Playoffs: 4 Partidos Consecutivos de 40+ Puntos', count: 1, details: 'Playoffs 2024 (Igualando a Michael Jordan y Bernard King)' },
      { icon: 'sparkles', name: 'Capitán Oficial de los New York Knicks', count: 1, details: 'Primer capitán nombrado desde 2019' },
    ],
    seasonAverages: {
      pts: '28.7',
      reb: '3.6',
      ast: '6.7',
      stl: '0.9',
      blk: '0.2',
      fgPct: '47.9%',
      threePct: '40.1%',
      ftPct: '84.7%',
    },
  },

  'Karl-Anthony Towns': {
    tacticalRole: 'Pívot All-Star Francotirador & Gigante Perimetral (KAT)',
    specialty: 'El mejor pívot tirador de triples de la historia, juego al poste alto y rebote defensivo',
    playStyle: 'Pívot ofensivo moderno definitivo, campeón de concurso de triples y 4x All-Star',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 1,
      teamName: 'Minnesota Timberwolves',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2015 · Pick #1 (1ª Ronda por Minnesota Timberwolves)',
    experience: '10 Temporadas (Timberwolves / Knicks)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '25,70 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Rookie del Año Unánime)',
      },
      {
        season: '19/20',
        date: '22/09/2018',
        fromTeam: 'Minnesota Timberwolves',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '190,00 mill. $',
        feeOrType: 'Designated Supermax Rookie Extension (5 años / $190M)',
      },
      {
        season: '24/25',
        date: '27/09/2024',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Mega-Traspaso Bombazo (por Julius Randle + Donte DiVincenzo + 1ª ronda)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY Unánime)', count: 1, details: '2016 (Minnesota Timberwolves)' },
      { icon: 'star', name: 'NBA All-Star', count: 4, details: '2018, 2019, 2022, 2024' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 2, details: '2018, 2022' },
      { icon: 'flame', name: 'Campeón del Concurso de Triples de la NBA', count: 1, details: '2022 (Primer pívot en ganarlo)' },
      { icon: 'trophy', name: 'Campeón del Concurso de Habilidades de la NBA', count: 1, details: '2016' },
      { icon: 'medal', name: '2x Partidos de 60+ Puntos en la NBA', count: 2, details: '60 pts vs Spurs (2022), 62 pts vs Hornets (2024)' },
    ],
    seasonAverages: {
      pts: '22.0',
      reb: '10.8',
      ast: '3.0',
      stl: '0.7',
      blk: '0.9',
      fgPct: '50.4%',
      threePct: '41.6%',
      ftPct: '87.3%',
    },
  },

  'OG Anunoby': {
    tacticalRole: 'Alero Defensor de Élite & Especialista 3&D (The Stopper)',
    specialty: 'Defensa asfixiante individual a estrellas rivales, manos rápidas para robos y triples desde la esquina',
    playStyle: 'El defensor perimetral más versátil y dominante de la NBA',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 23,
      teamName: 'Toronto Raptors',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'Indiana Hoosiers / Reino Unido',
    },
    draft: '2017 · Pick #23 (1ª Ronda por Toronto Raptors)',
    experience: '8 Temporadas (Raptors / Knicks)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Indiana Hoosiers',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '9,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 23)',
      },
      {
        season: '23/24',
        date: '30/12/2023',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '72,00 mill. $',
        feeOrType: 'Traspaso Estelar (por RJ Barrett + Immanuel Quickley)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'New York Knicks',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '212,50 mill. $',
        feeOrType: 'Renovación Máxima (5 años / $212.5M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2019 (Toronto Raptors)' },
      { icon: 'shield', name: '2º Equipo All-Defensive de la NBA', count: 1, details: '2023' },
      { icon: 'flame', name: 'Líder en Robos de Balón de la NBA', count: 1, details: '2023 (1.9 Robos por partido)' },
    ],
    seasonAverages: {
      pts: '16.0',
      reb: '4.5',
      ast: '2.3',
      stl: '1.8',
      blk: '0.8',
      fgPct: '48.9%',
      threePct: '38.2%',
      ftPct: '78.5%',
    },
  },

  'Mikal Bridges': {
    tacticalRole: 'Alero Bidireccional de Hierro (The Iron Man)',
    specialty: 'Récord de más de 500 partidos jugados consecutivos sin faltar jamás, defensa individual y tiro de tres',
    playStyle: 'Durabilidad sobrehumana y excelencia bidireccional en ambos lados de la pista',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 10,
      teamName: 'Philadelphia 76ers (Traspasado a Suns)',
      teamAbbr: 'PHX',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
      origin: 'Villanova Wildcats',
    },
    draft: '2018 · Pick #10 (1ª Ronda por Philadelphia, traspasado a Phoenix Suns)',
    experience: '7 Temporadas (Suns / Nets / Knicks)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Villanova Wildcats',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '17,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10 por Zhaire Smith + 1ª ronda)',
      },
      {
        season: '22/23',
        date: '09/02/2023',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Kevin Durant)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '90,00 mill. $',
        feeOrType: 'Traspaso Histórico entre Rivales de NY (por 5 primeras rondas de Draft)',
      },
    ],
    awards: [
      { icon: 'shield', name: '1er Equipo All-Defensive de la NBA', count: 1, details: '2022' },
      { icon: 'ribbon', name: '2º Lugar en Votación a Defensor del Año (DPOY)', count: 1, details: '2022' },
      { icon: 'trophy', name: '2x Campeón Nacional de la NCAA', count: 2, details: '2016, 2018 (Villanova Wildcats)' },
      { icon: 'ribbon', name: 'Campeón de la Conferencia Oeste', count: 1, details: '2021 (Phoenix Suns)' },
      { icon: 'sparkles', name: 'Racha Activa de Iron Man de la NBA (500+ Partidos Consecutivos)', count: 1, details: 'Líder absoluto de partidos consecutivos sin descansar' },
    ],
    seasonAverages: {
      pts: '19.6',
      reb: '4.5',
      ast: '3.6',
      stl: '1.0',
      blk: '0.4',
      fgPct: '45.8%',
      threePct: '37.2%',
      ftPct: '88.3%',
    },
  },

  'Josh Hart': {
    tacticalRole: 'Guard Todoterreno & Máquina de Triples-Dobles (The Engine)',
    specialty: 'Reboteador insaciable para su posición, contraataque a máxima velocidad, robos y corazón competitivo',
    playStyle: 'Motor inagotable de los Knicks jugando 48 minutos seguidos en playoffs sin descansar',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 30,
      teamName: 'Utah Jazz (Traspasado a Lakers)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Villanova Wildcats',
    },
    draft: '2017 · Pick #30 (1ª Ronda por Utah, traspasado a LA Lakers)',
    experience: '8 Temporadas (Lakers / Pelicans / Trail Blazers / Knicks)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Villanova Wildcats',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '8,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 30)',
      },
      {
        season: '19/20',
        date: '06/07/2019',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '38,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Anthony Davis)',
      },
      {
        season: '22/23',
        date: '08/02/2023',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '81,00 mill. $',
        feeOrType: 'Traspaso por Cam Reddish + 1ª ronda',
      },
      {
        season: '24/25',
        date: '10/08/2023',
        fromTeam: 'New York Knicks',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '81,00 mill. $',
        feeOrType: 'Extensión Multianual (4 años / $81M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA', count: 1, details: '2016 (Villanova Wildcats)' },
      { icon: 'sparkles', name: 'MVP de la NBA Summer League', count: 1, details: '2018 (Las Vegas)' },
      { icon: 'medal', name: 'Líder en Triples-Dobles entre Escoltas', count: 6, details: 'Temporada 2023-24 con los Knicks' },
      { icon: 'trophy', name: 'Julius Erving Award (Mejor Alero Universitario)', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '11.8',
      reb: '8.3',
      ast: '4.6',
      stl: '1.2',
      blk: '0.3',
      fgPct: '46.4%',
      threePct: '33.2%',
      ftPct: '79.1%',
    },
  },

  'Jordan Clarkson': {
    tacticalRole: 'Sexto Hombre Letal & Desatascador Ofensivo (Flamethrower)',
    specialty: 'Anotación en ráfaga instantánea, crossovers alocados, triples en step-back y floaters',
    playStyle: 'El microondas definitivo capaz de anotar 20 puntos en un solo cuarto',
    draftInfo: {
      year: 2014,
      round: 2,
      pick: 46,
      teamName: 'Washington Wizards (Traspasado a Lakers)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Missouri Tigers / Filipinas',
    },
    draft: '2014 · Pick #46 (2ª Ronda por Washington Wizards, traspasado a LA Lakers)',
    experience: '11 Temporadas (Lakers / Cavaliers / Jazz / Knicks)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'Missouri Tigers',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '5,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 46)',
      },
      {
        season: '19/20',
        date: '24/12/2019',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Utah Jazz',
        toTeamAbbr: 'UTA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        marketValue: '52,00 mill. $',
        feeOrType: 'Traspaso por Dante Exum',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Utah Jazz',
        fromTeamAbbr: 'UTA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/uta.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '28,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Mejor Sexto Hombre de la NBA (Sixth Man of the Year 6MOY)', count: 1, details: '2021 (Utah Jazz — Ganador Absoluto)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2015' },
    ],
    seasonAverages: {
      pts: '17.1',
      reb: '3.4',
      ast: '5.0',
      stl: '0.6',
      blk: '0.1',
      fgPct: '42.0%',
      threePct: '32.5%',
      ftPct: '88.1%',
    },
  },

  // ==========================================
  // PHILADELPHIA 76ERS (PHI)
  // ==========================================
  'Tyrese Maxey': {
    tacticalRole: 'Base Eléctrico & Francotirador a Máxima Velocidad (The Franchise)',
    specialty: 'Velocidad punta imparable en transición, step-back en triple, floaters y ética de trabajo legendaria',
    playStyle: 'Estrella All-Star de presente y futuro de los Sixers, anotador letal de 25+ puntos',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 21,
      teamName: 'Philadelphia 76ers',
      teamAbbr: 'PHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2020 · Pick #21 (1ª Ronda por Philadelphia 76ers)',
    experience: '5 Temporadas (Philadelphia 76ers)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '12,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick 21 — El mayor robo del Draft 2020)',
      },
      {
        season: '24/25',
        date: '07/07/2024',
        fromTeam: 'Philadelphia 76ers',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '204,00 mill. $',
        feeOrType: 'Designated Maximum Contract Extension (5 años / $204M)',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2024 (Indiana)' },
      { icon: 'flame', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2024 (Philadelphia 76ers)' },
      { icon: 'sparkles', name: 'Premio a la Deportividad de la NBA (Joe Dumars Trophy)', count: 1, details: '2024' },
      { icon: 'medal', name: '3x Partidos de 50+ Puntos en una Temporada', count: 3, details: '50 pts vs Pacers, 51 pts vs Jazz, 52 pts vs Spurs (2023-24)' },
    ],
    seasonAverages: {
      pts: '26.1',
      reb: '3.8',
      ast: '6.4',
      stl: '1.0',
      blk: '0.5',
      fgPct: '45.8%',
      threePct: '37.8%',
      ftPct: '87.1%',
    },
  },

  'Jaylen Brown': {
    tacticalRole: 'Escolta/Alero Atlético Dominante & MVP de Finales (JB)',
    specialty: 'Mates devastadores, tiro en media distancia imparable, defensa perimetral sobre la estrella rival',
    playStyle: 'Superestrella campeona de la NBA, MVP de las Finales 2024 y anotador atlético supremo',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 3,
      teamName: 'Boston Celtics',
      teamAbbr: 'BOS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
      origin: 'California Golden Bears',
    },
    draft: '2016 · Pick #3 (1ª Ronda por Boston Celtics)',
    experience: '9 Temporadas (Celtics / 76ers)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'California',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '21,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '23/24',
        date: '25/07/2023',
        fromTeam: 'Boston Celtics',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '304,00 mill. $',
        feeOrType: 'Supermax Extension Más Grande en la Historia de la NBA (5 años / $304M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '304,00 mill. $',
        feeOrType: 'Mega-Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics)' },
      { icon: 'sparkles', name: 'MVP de las Finales de la NBA (Bill Russell Trophy)', count: 1, details: '2024 vs Dallas Mavericks' },
      { icon: 'ribbon', name: 'MVP de Finales de Conferencia Este (Larry Bird Trophy)', count: 1, details: '2024 vs Indiana Pacers' },
      { icon: 'star', name: 'NBA All-Star', count: 3, details: '2021, 2023, 2024' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 1, details: '2023' },
      { icon: 'shield-checkmark', name: 'NBA All-Rookie 2º Equipo', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '23.4',
      reb: '5.5',
      ast: '3.7',
      stl: '1.2',
      blk: '0.6',
      fgPct: '49.9%',
      threePct: '35.4%',
      ftPct: '73.8%',
    },
  },

  'Joel Embiid': {
    tacticalRole: 'Pívot Dominante, MVP de la NBA & Fuerza Histórica (The Process)',
    specialty: 'Juego de espaldas y cara al aro, fadeaway de media distancia imposible, tiro libre y protección de aro',
    playStyle: 'El pívot más imparable en anotación individual desde Shaquille O’Neal',
    draftInfo: {
      year: 2014,
      round: 1,
      pick: 3,
      teamName: 'Philadelphia 76ers',
      teamAbbr: 'PHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
      origin: 'Kansas Jayhawks / Camerún',
    },
    draft: '2014 · Pick #3 (1ª Ronda por Philadelphia 76ers)',
    experience: '11 Temporadas (Philadelphia 76ers)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'Kansas Jayhawks',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '19,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3 — El icono del Process)',
      },
      {
        season: '23/24',
        date: '17/08/2021',
        fromTeam: 'Philadelphia 76ers',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '196,00 mill. $',
        feeOrType: 'Supermax Extension (4 años / $196M)',
      },
      {
        season: '24/25',
        date: '20/09/2024',
        fromTeam: 'Philadelphia 76ers',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '193,00 mill. $',
        feeOrType: 'Extensión Máxima (3 años / $193M hasta 2029)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'MVP de la NBA (Most Valuable Player)', count: 1, details: '2023 (Michael Jordan Trophy)' },
      { icon: 'flame', name: '2x Máximo Anotador de la NBA', count: 2, details: '2022 (30.6 Pts), 2023 (33.1 Pts)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024' },
      { icon: 'star', name: 'NBA All-Star', count: 7, details: '2018, 2019, 2020, 2021, 2022, 2023, 2024' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 1, details: '2023' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 4, details: '2018, 2019, 2021, 2022' },
      { icon: 'shield', name: '2º Equipo All-Defensive de la NBA', count: 3, details: '2018, 2019, 2021' },
      { icon: 'sparkles', name: 'Partido Histórico de 70 Puntos (Récord de Franquicia)', count: 1, details: '22/01/2024 vs San Antonio Spurs' },
    ],
    seasonAverages: {
      pts: '33.1',
      reb: '10.8',
      ast: '5.7',
      stl: '1.2',
      blk: '1.7',
      fgPct: '52.9%',
      threePct: '38.8%',
      ftPct: '88.3%',
    },
  },

  'LeBron James': {
    tacticalRole: 'El Rey del Baloncesto Mundial & Máximo Anotador Histórico (King James / GOAT)',
    specialty: 'IQ baloncestístico supremo, visión de pase sobrenatural, potencia física imparable hacia el aro y longevidad eterna',
    playStyle: 'La figura más dominante e influyente del siglo XXI en el deporte mundial',
    draftInfo: {
      year: 2003,
      round: 1,
      pick: 1,
      teamName: 'Cleveland Cavaliers',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'St. Vincent-St. Mary High School (Akron, Ohio)',
    },
    draft: '2003 · Pick #1 (1ª Ronda por Cleveland Cavaliers — The Chosen One)',
    experience: '22 Temporadas (Cavaliers / Heat / Lakers / 76ers)',
    transfers: [
      {
        season: '03/04',
        date: '26/06/2003',
        fromTeam: 'St. Vincent-St. Mary',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '18,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1)',
      },
      {
        season: '10/11',
        date: '08/07/2010',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '110,00 mill. $',
        feeOrType: 'The Decision / Sign & Trade (6 años / $110M)',
      },
      {
        season: '14/15',
        date: '12/07/2014',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'I\'m Coming Home (Regreso Histórico a Cleveland)',
      },
      {
        season: '18/19',
        date: '09/07/2018',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '154,00 mill. $',
        feeOrType: 'Agencia Libre (4 años / $154M)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '104,00 mill. $',
        feeOrType: 'Agencia Libre y Traspaso de Leyenda',
      },
    ],
    awards: [
      { icon: 'trophy', name: '4x Campeón de la NBA', count: 4, details: '2012, 2013 (Miami), 2016 (Cleveland), 2020 (Lakers)' },
      { icon: 'sparkles', name: '4x MVP de las Finales de la NBA', count: 4, details: '2012, 2013, 2016, 2020 (Único jugador con 3 equipos distintos)' },
      { icon: 'ribbon', name: '4x MVP de la Temporada Regular de la NBA', count: 4, details: '2009, 2010, 2012, 2013' },
      { icon: 'medal', name: '3x Medalla de Oro Olímpica & MVP Olímpico (Team USA)', count: 3, details: 'Pekín 2008, Londres 2012, París 2024' },
      { icon: 'trophy', name: 'Campeón y MVP del NBA In-Season Tournament (NBA Cup)', count: 1, details: '2023' },
      { icon: 'flame', name: 'Máximo Anotador Histórico de la NBA (+40.000 Puntos)', count: 1, details: 'Superando el récord legendario de Kareem Abdul-Jabbar' },
      { icon: 'star', name: '20x Seleccionado al NBA All-Star Game (Récord Absoluto)', count: 20, details: '2005-2024 (20 años consecutivos como titular)' },
      { icon: 'albums', name: '20x Seleccionado en los Equipos All-NBA (13x 1er Equipo)', count: 20, details: 'Récord histórico de la NBA' },
      { icon: 'shield', name: '6x All-Defensive Team (5x 1er Equipo)', count: 6, details: '2009, 2010, 2011, 2012, 2013' },
    ],
    seasonAverages: {
      pts: '25.7',
      reb: '7.3',
      ast: '8.3',
      stl: '1.2',
      blk: '0.5',
      fgPct: '54.0%',
      threePct: '41.0%',
      ftPct: '75.0%',
    },
  },

  'Kentavious Caldwell-Pope': {
    tacticalRole: 'Escolta 3&D 2-Veces Campeón de la NBA (KCP)',
    specialty: 'Defensa de perímetro asfixiante sobre anotadores rivales, triples en transición y tiros abiertos',
    playStyle: 'El escolta 3&D definitivo, pieza clave en los anillos de Lakers (2020) y Nuggets (2023)',
    draftInfo: {
      year: 2013,
      round: 1,
      pick: 8,
      teamName: 'Detroit Pistons',
      teamAbbr: 'DET',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
      origin: 'Georgia Bulldogs',
    },
    draft: '2013 · Pick #8 (1ª Ronda por Detroit Pistons)',
    experience: '12 Temporadas (Pistons / Lakers / Wizards / Nuggets / 76ers)',
    transfers: [
      {
        season: '13/14',
        date: '27/06/2013',
        fromTeam: 'Georgia Bulldogs',
        toTeam: 'Detroit Pistons',
        toTeamAbbr: 'DET',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        marketValue: '11,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 8)',
      },
      {
        season: '17/18',
        date: '13/07/2017',
        fromTeam: 'Detroit Pistons',
        fromTeamAbbr: 'DET',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/det.png',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '18,00 mill. $',
        feeOrType: 'Agencia Libre (1 año / $18M)',
      },
      {
        season: '22/23',
        date: '06/07/2022',
        fromTeam: 'Washington Wizards',
        fromTeamAbbr: 'WAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        toTeam: 'Denver Nuggets',
        toTeamAbbr: 'DEN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        marketValue: '30,00 mill. $',
        feeOrType: 'Traspaso por Will Barton y Monte Morris',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Denver Nuggets',
        fromTeamAbbr: 'DEN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/den.png',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '66,00 mill. $',
        feeOrType: 'Agencia Libre (3 años / $66M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón de la NBA', count: 2, details: '2020 (Los Angeles Lakers), 2023 (Denver Nuggets)' },
      { icon: 'ribbon', name: '2x Campeón de Conferencia Oeste', count: 2, details: '2020, 2023' },
    ],
    seasonAverages: {
      pts: '10.1',
      reb: '2.4',
      ast: '2.4',
      stl: '1.3',
      blk: '0.5',
      fgPct: '46.0%',
      threePct: '40.6%',
      ftPct: '89.4%',
    },
  },

  'Anfernee Simons': {
    tacticalRole: 'Base Anotador Explosivo & Campeón de Mates (Ant)',
    specialty: 'Salto vertical descomunal (41.5 pulgadas), triples tras bote en racha y velocidad',
    playStyle: 'Anotador eléctrico de alto vuelo capaz de anotar 40+ puntos',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 24,
      teamName: 'Portland Trail Blazers',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'IMG Academy (Florida)',
    },
    draft: '2018 · Pick #24 (1ª Ronda por Portland Trail Blazers)',
    experience: '7 Temporadas (Trail Blazers / 76ers)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'IMG Academy',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '10,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 24)',
      },
      {
        season: '22/23',
        date: '06/07/2022',
        fromTeam: 'Portland Trail Blazers',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Extensión Multianual (4 años / $100M)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón del Concurso de Mates de la NBA (Slam Dunk Contest)', count: 1, details: '2021 (All-Star en Atlanta)' },
      { icon: 'flame', name: 'Partido de 45 Puntos en la NBA', count: 1, details: '2022 vs Utah Jazz' },
    ],
    seasonAverages: {
      pts: '22.6',
      reb: '3.6',
      ast: '5.5',
      stl: '0.5',
      blk: '0.1',
      fgPct: '43.0%',
      threePct: '38.5%',
      ftPct: '91.6%',
    },
  },

  // ==========================================
  // TORONTO RAPTORS (TOR)
  // ==========================================
  'Scottie Barnes': {
    tacticalRole: 'Alero Point-Forward Franquicia (Scottie B)',
    specialty: 'Visión de juego magistral, defensa multiposicional del 1 al 5, rebote ofensivo e intensidad',
    playStyle: 'Novato del Año y All-Star moderno sobre el que gira el futuro de Toronto Raptors',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 4,
      teamName: 'Toronto Raptors',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'Florida State Seminoles',
    },
    draft: '2021 · Pick #4 (1ª Ronda por Toronto Raptors)',
    experience: '4 Temporadas (Toronto Raptors)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Florida State',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '33,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4 — Novato del Año ROTY)',
      },
      {
        season: '24/25',
        date: '07/07/2024',
        fromTeam: 'Toronto Raptors',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '225,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension Histórica (5 años / $225M hasta $270M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2022 (Toronto Raptors)' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2024 (Indiana)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2022' },
      { icon: 'medal', name: '1er Quinteto All-Rising Stars', count: 2, details: '2022, 2023' },
    ],
    seasonAverages: {
      pts: '19.9',
      reb: '8.2',
      ast: '6.1',
      stl: '1.3',
      blk: '1.5',
      fgPct: '47.5%',
      threePct: '34.1%',
      ftPct: '78.1%',
    },
  },

  'Brandon Ingram': {
    tacticalRole: 'Alero Anotador Letal de Media Distancia (B-Ingram)',
    specialty: 'Envergadura de 2,21m, tiro en suspensión por encima del defensor, manejo fluido y creación para otros',
    playStyle: 'Anotador puro All-Star con arsenal ofensivo fluido y elegante',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 2,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Duke Blue Devils',
    },
    draft: '2016 · Pick #2 (1ª Ronda por Los Angeles Lakers)',
    experience: '9 Temporadas (Lakers / Pelicans / Raptors)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '23,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 2)',
      },
      {
        season: '19/20',
        date: '06/07/2019',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '158,00 mill. $',
        feeOrType: 'Mega-Traspaso por Anthony Davis',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '158,00 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2020 (New Orleans Pelicans)' },
      { icon: 'flame', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2020' },
      { icon: 'shield-checkmark', name: 'NBA All-Rookie 2º Equipo', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '21.5',
      reb: '5.1',
      ast: '5.7',
      stl: '0.8',
      blk: '0.4',
      fgPct: '49.2%',
      threePct: '36.5%',
      ftPct: '80.0%',
    },
  },

  'RJ Barrett': {
    tacticalRole: 'Escolta/Alero Físico & Orgullo Canadiense (Maple Mamba)',
    specialty: 'Ataque frontal a la canasta con potencia, finalización con la zurda y tiro tras pase',
    playStyle: 'Anotador potente de 20+ puntos y líder de la selección nacional de Canadá',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 3,
      teamName: 'New York Knicks',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Duke Blue Devils / Canadá',
    },
    draft: '2019 · Pick #3 (1ª Ronda por New York Knicks)',
    experience: '6 Temporadas (Knicks / Raptors)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '35,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '23/24',
        date: '30/12/2023',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '107,00 mill. $',
        feeOrType: 'Mega-Traspaso (Regreso a su país natal Canadá por OG Anunoby)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Medalla de Bronce en Mundial FIBA (Canadá Histórico)', count: 1, details: '2023 (Clasificación a Juegos Olímpicos)' },
      { icon: 'shield-checkmark', name: 'NBA All-Rookie 2º Equipo', count: 1, details: '2020' },
      { icon: 'trophy', name: 'Jerry West Award (Mejor Escolta Universitario)', count: 1, details: '2019 (Duke Blue Devils)' },
      { icon: 'medal', name: 'Campeón y MVP del Mundial FIBA U19', count: 1, details: 'El Cairo 2017 (Oro Histórico para Canadá)' },
    ],
    seasonAverages: {
      pts: '21.8',
      reb: '6.4',
      ast: '4.1',
      stl: '0.6',
      blk: '0.4',
      fgPct: '55.3%',
      threePct: '39.2%',
      ftPct: '71.1%',
    },
  },

  'Immanuel Quickley': {
    tacticalRole: 'Base Anotador Dinámico & Especialista en Floaters (IQ)',
    specialty: 'Floater letal en carrera, tiro de tres tras drible, cambios de ritmo y energía eléctrica',
    playStyle: 'Base titular anotador moderno con rango exterior ilimitado',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 25,
      teamName: 'Oklahoma City Thunder (Traspasado a Knicks)',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2020 · Pick #25 (1ª Ronda por Oklahoma City, traspasado a New York Knicks)',
    experience: '5 Temporadas (Knicks / Raptors)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '11,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 25)',
      },
      {
        season: '23/24',
        date: '30/12/2023',
        fromTeam: 'New York Knicks',
        fromTeamAbbr: 'NYK',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '175,00 mill. $',
        feeOrType: 'Traspaso por OG Anunoby',
      },
      {
        season: '24/25',
        date: '07/07/2024',
        fromTeam: 'Toronto Raptors',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '175,00 mill. $',
        feeOrType: 'Renovación Máxima Multianual (5 años / $175M)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: 'NBA All-Rookie 2º Equipo', count: 1, details: '2021' },
      { icon: 'flame', name: '2º en Votación a Mejor Sexto Hombre de la NBA (6MOY)', count: 1, details: '2023 (New York Knicks)' },
      { icon: 'sparkles', name: 'Jugador del Año de la SEC', count: 1, details: '2020 (Kentucky Wildcats)' },
    ],
    seasonAverages: {
      pts: '18.6',
      reb: '4.8',
      ast: '6.8',
      stl: '0.9',
      blk: '0.2',
      fgPct: '43.8%',
      threePct: '39.5%',
      ftPct: '85.4%',
    },
  },

  'Andre Jackson Jr.': {
    tacticalRole: 'Escolta Defensivo Atlético & Campeón NCAA 2023',
    specialty: 'Salto vertical explosivo, cortes agresivos al aro, defensa perimetral y pases en transición',
    playStyle: 'Especialista defensivo y campeón nacional colegial',
    draftInfo: {
      year: 2023,
      round: 2,
      pick: 36,
      teamName: 'Orlando Magic (Traspasado a Bucks)',
      teamAbbr: 'MIL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
      origin: 'UConn Huskies',
    },
    draft: '2023 · Pick #36 (2ª Ronda por Orlando Magic, traspasado a Milwaukee Bucks)',
    experience: '2 Temporadas (Bucks / Raptors)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'UConn Huskies',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '7,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 36)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Milwaukee Bucks',
        fromTeamAbbr: 'MIL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '7,60 mill. $',
        feeOrType: 'Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA', count: 1, details: '2023 (UConn Huskies — Titular Indiscutido)' },
      { icon: 'sparkles', name: 'Capitán de UConn Huskies Campeón', count: 1, details: '2023' },
    ],
    seasonAverages: {
      pts: '4.8',
      reb: '3.1',
      ast: '1.9',
      stl: '0.8',
      blk: '0.4',
      fgPct: '50.0%',
      threePct: '37.0%',
      ftPct: '72.7%',
    },
  },

  'Jamal Shead': {
    tacticalRole: 'Base Defensivo del Año & Perro de Presa (The Pitbull)',
    specialty: 'El mejor defensor exterior de la NCAA en 2024, presión sobre el balón, IQ táctico y visión de pase',
    playStyle: 'Líder defensivo y general en pista premiado a nivel nacional',
    draftInfo: {
      year: 2024,
      round: 2,
      pick: 45,
      teamName: 'Sacramento Kings (Traspasado a Raptors)',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'Houston Cougars',
    },
    draft: '2024 · Pick #45 (2ª Ronda por Toronto Raptors)',
    experience: '1 Temporada (Toronto Raptors)',
    transfers: [
      {
        season: '24/25',
        date: '27/06/2024',
        fromTeam: 'Houston Cougars',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '6,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 45)',
      },
    ],
    awards: [
      { icon: 'shield', name: 'Naismith Defensive Player of the Year (Mejor Defensor de la NCAA)', count: 1, details: '2024 (Houston Cougars)' },
      { icon: 'trophy', name: 'Jugador del Año de la Conferencia Big 12', count: 1, details: '2024' },
      { icon: 'albums', name: '1er Equipo All-American Unánime', count: 1, details: '2024' },
      { icon: 'shield', name: 'Jugador Defensivo del Año Big 12', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '7.2',
      reb: '2.0',
      ast: '4.8',
      stl: '1.5',
      blk: '0.2',
      fgPct: '42.0%',
      threePct: '33.3%',
      ftPct: '80.0%',
    },
  },

  'Ja\'Kobe Walter': {
    tacticalRole: 'Escolta Anotador & Freshman del Año',
    specialty: 'Tiro de tres tras bloqueo, agresividad atacando el aro y tiro libre fiable',
    playStyle: 'Promesa anotadora de primera ronda con proyección All-Star',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 19,
      teamName: 'Toronto Raptors',
      teamAbbr: 'TOR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
      origin: 'Baylor Bears',
    },
    draft: '2024 · Pick #19 (1ª Ronda por Toronto Raptors)',
    experience: '1 Temporada (Toronto Raptors)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'Baylor Bears',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '17,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 19 — 4 años / $17.2M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Freshman del Año de la Conferencia Big 12', count: 1, details: '2024 (Baylor Bears)' },
      { icon: 'albums', name: '3er Equipo All-Big 12', count: 1, details: '2024' },
      { icon: 'medal', name: 'McDonald\'s All-American', count: 1, details: '2023' },
    ],
    seasonAverages: {
      pts: '9.8',
      reb: '2.8',
      ast: '1.4',
      stl: '0.9',
      blk: '0.2',
      fgPct: '42.8%',
      threePct: '36.5%',
      ftPct: '84.0%',
    },
  },
};
