import { PlayerDossier } from './playerDossier';

export const SOUTHEAST_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // ATLANTA HAWKS (ATL)
  // ==========================================
  'Jalen Johnson': {
    tacticalRole: 'Ala-Pívot Creador Todoterreno & Estrella Emergente de Atlanta',
    specialty: 'Contraataques de costa a costa, pases en carrera, rebote agresivo y mates de alta potencia',
    playStyle: 'Alero / Ala-pívot moderno versátil con visión de base y atletismo de élite',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 20,
      teamName: 'Atlanta Hawks',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Duke Blue Devils / Milwaukee, Wisconsin',
    },
    draft: '2021 · Pick #20 (1ª Ronda por Atlanta Hawks)',
    experience: '4 Temporadas (Atlanta Hawks)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '12,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 20)',
      },
      {
        season: '24/25',
        date: '21/10/2024',
        fromTeam: 'Atlanta Hawks',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '150,00 mill. $',
        feeOrType: 'Extensión Rookie Máxima (5 años / $150M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Finalista a Jugador Más Mejorado de la NBA (MIP Top 5)', count: 1, details: '2024 (Salto a 16.0 ppp, 8.7 rpp, 3.6 app)' },
      { icon: 'flame', name: 'Múltiples Triples-Dobles en la NBA', count: 1, details: 'Incluyendo 28 pts, 14 reb, 11 ast vs Pistons' },
    ],
    seasonAverages: {
      pts: '16.0',
      reb: '8.7',
      ast: '3.6',
      stl: '1.2',
      blk: '0.8',
      fgPct: '51.1%',
      threePct: '35.5%',
      ftPct: '72.8%',
    },
  },

  'CJ McCollum': {
    tacticalRole: 'Escolta Anotador Virtuoso, Jugador Más Mejorado & Presidente de la NBPA',
    specialty: 'Tiros en suspensión tras bote, flotadoras elegantes de seda, tiro de tres puntos y clutch',
    playStyle: 'Anotador técnico implacable con más de 14.000 puntos en su carrera NBA',
    draftInfo: {
      year: 2013,
      round: 1,
      pick: 10,
      teamName: 'Portland Trail Blazers',
      teamAbbr: 'POR',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
      origin: 'Lehigh Mountain Hawks / Canton, Ohio',
    },
    draft: '2013 · Pick #10 (1ª Ronda por Portland Trail Blazers)',
    experience: '12 Temporadas (Blazers / Pelicans / Hawks)',
    transfers: [
      {
        season: '13/14',
        date: '27/06/2013',
        fromTeam: 'Lehigh',
        toTeam: 'Portland Trail Blazers',
        toTeamAbbr: 'POR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        marketValue: '10,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10)',
      },
      {
        season: '21/22',
        date: '08/02/2022',
        fromTeam: 'Portland Trail Blazers',
        fromTeamAbbr: 'POR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/por.png',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Traspaso a 4 Bandas',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '64,00 mill. $',
        feeOrType: 'Traspaso de Veterano Estrella (2 años / $64M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2016 (Portland Trail Blazers — 20.8 ppp)' },
      { icon: 'flame', name: '+14.000 Puntos Anotados en Carrera NBA', count: 1, details: '8 Temporadas consecutivas con 20+ ppp' },
      { icon: 'ribbon', name: 'Presidente del Sindicato de Jugadores de la NBA (NBPA)', count: 1, details: 'Líder gremial histórico' },
    ],
    seasonAverages: {
      pts: '20.0',
      reb: '4.3',
      ast: '4.6',
      stl: '0.9',
      blk: '0.6',
      fgPct: '45.9%',
      threePct: '42.9%',
      ftPct: '82.7%',
    },
  },

  'Dyson Daniels': {
    tacticalRole: 'Base / Escolta Ladrón Supremo & Defensor Perimetral de Élite (The Great Barrier Thief)',
    specialty: 'Desvíos de balón insuperables (líder de la NBA), robos en primera línea y visión de pase',
    playStyle: 'Especialista defensivo absoluto con instinto sobrenatural para robar balones',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 8,
      teamName: 'New Orleans Pelicans',
      teamAbbr: 'NOP',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
      origin: 'G League Ignite / Bendigo, Australia',
    },
    draft: '2022 · Pick #8 (1ª Ronda por New Orleans Pelicans)',
    experience: '3 Temporadas (Pelicans / Hawks)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'G League Ignite',
        toTeam: 'New Orleans Pelicans',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '25,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 8)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '30,00 mill. $',
        feeOrType: 'Traspaso (Operación Dejounte Murray)',
      },
    ],
    awards: [
      { icon: 'shield', name: 'Líder en Robos y Deflexiones de la NBA', count: 1, details: '2024-25 (Promediando más de 3.0 robos por noche)' },
      { icon: 'medal', name: 'Estrella de los Boomers de Australia', count: 1, details: 'Juegos Olímpicos París 2024' },
      { icon: 'sparkles', name: 'Rising Stars Challenge Participant', count: 2, details: '2023, 2024' },
    ],
    seasonAverages: {
      pts: '14.0',
      reb: '4.8',
      ast: '3.5',
      stl: '3.1',
      blk: '0.8',
      fgPct: '46.8%',
      threePct: '32.5%',
      ftPct: '68.0%',
    },
  },

  // ==========================================
  // CHARLOTTE HORNETS (CHA)
  // ==========================================
  'Brandon Miller': {
    tacticalRole: 'Alero Anotador Suave, Francotirador de Élite & 1er Equipo All-Rookie',
    specialty: 'Tiro tras bote fluido con 2,06m, anotación en tres niveles y salto vertical',
    playStyle: 'Alero anotador moderno con comparaciones directas a Paul George y Kevin Durant',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 2,
      teamName: 'Charlotte Hornets',
      teamAbbr: 'CHA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
      origin: 'Alabama Crimson Tide / Nashville, Tennessee',
    },
    draft: '2023 · Pick #2 (1ª Ronda por Charlotte Hornets)',
    experience: '2 Temporadas (Charlotte Hornets)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Alabama Crimson Tide',
        toTeam: 'Charlotte Hornets',
        toTeamAbbr: 'CHA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        marketValue: '49,40 mill. $',
        feeOrType: 'Draft de la NBA (Pick 2 — Escala Rookie)',
      },
    ],
    awards: [
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2024 (3º en la votación al ROTY)' },
      { icon: 'ribbon', name: '3x Consecutivo Rookie del Mes de la Conferencia Este', count: 3, details: 'Enero, Febrero, Marzo 2024' },
      { icon: 'sparkles', name: 'Jugador del Año de la SEC & Freshman of the Year', count: 1, details: '2023 (Alabama)' },
      { icon: 'albums', name: '1er Equipo Consensus All-American', count: 1, details: '2023' },
    ],
    seasonAverages: {
      pts: '17.3',
      reb: '4.3',
      ast: '2.4',
      stl: '0.9',
      blk: '0.6',
      fgPct: '44.0%',
      threePct: '37.3%',
      ftPct: '82.0%',
    },
  },

  'Naz Reid': {
    tacticalRole: 'Pívot Anotador de Perímetro, Mejor Sexto Hombre de la NBA & Ídolo de Culto (Naz Reid)',
    specialty: 'Manejo de balón como base siendo pívot, triples frontales en transición y finalizaciones con ambas manos',
    playStyle: 'El mejor sexto hombre interior de la liga y fenómeno de masas absoluto',
    draftInfo: {
      year: 2019,
      round: 0,
      pick: 0,
      teamName: 'Minnesota Timberwolves (Undrafted)',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'LSU Tigers / Asbury Park, New Jersey',
    },
    draft: '2019 · No Drafteado (Agente Libre Rookie)',
    experience: '6 Temporadas (Timberwolves / Hornets)',
    transfers: [
      {
        season: '19/20',
        date: '05/07/2019',
        fromTeam: 'LSU Tigers',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '1,50 mill. $',
        feeOrType: 'Contrato Two-Way / Rookie No Drafteado',
      },
      {
        season: '23/24',
        date: '25/06/2023',
        fromTeam: 'Minnesota Timberwolves',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '42,00 mill. $',
        feeOrType: 'Extensión de Contrato (3 años / $42M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Charlotte Hornets',
        toTeamAbbr: 'CHA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        marketValue: '42,00 mill. $',
        feeOrType: 'Traspaso de Pívot Estrella',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Mejor Sexto Hombre de la NBA (6MOY)', count: 1, details: '2024 (Minnesota Timberwolves — 13.5 ppp y 41.4% 3PT desde el banquillo)' },
      { icon: 'ribbon', name: 'Finalista de Conferencia Oeste', count: 1, details: '2024 (Minnesota Timberwolves)' },
      { icon: 'flame', name: 'Tercer Jugador No Drafteado en la Historia en Ganar el 6MOY', count: 1, details: 'Junto a John Starks y Darrell Armstrong' },
    ],
    seasonAverages: {
      pts: '13.5',
      reb: '5.2',
      ast: '1.3',
      stl: '0.8',
      blk: '0.9',
      fgPct: '47.7%',
      threePct: '41.4%',
      ftPct: '73.6%',
    },
  },

  'Dennis Schroder': {
    tacticalRole: 'Base Líder Mundial, Campeón del Mundo & MVP de la Copa del Mundo FIBA (Dennis the Menace)',
    specialty: 'Velocidad de penetración endiablada, defensa en toda la pista, flotadoras y liderazgo internacional',
    playStyle: 'El gran capitán que llevó a Alemania a ser campeona del mundo invicta',
    draftInfo: {
      year: 2013,
      round: 1,
      pick: 17,
      teamName: 'Atlanta Hawks',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Phantoms Braunschweig / Alemania',
    },
    draft: '2013 · Pick #17 (1ª Ronda por Atlanta Hawks)',
    experience: '12 Temporadas (Hawks / Thunder / Lakers / Celtics / Rockets / Raptors / Nets / Hornets)',
    transfers: [
      {
        season: '13/14',
        date: '27/06/2013',
        fromTeam: 'Braunschweig',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '7,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 17)',
      },
      {
        season: '23/24',
        date: '08/02/2024',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '25,00 mill. $',
        feeOrType: 'Traspaso (por Spencer Dinwiddie)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Charlotte Hornets',
        toTeamAbbr: 'CHA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cha.png',
        marketValue: '26,00 mill. $',
        feeOrType: 'Traspaso de Base Titular',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la Copa del Mundo FIBA & MVP del Mundial', count: 1, details: '2023 (Alemania invicta 8-0 — 28 pts en la Final vs Serbia)' },
      { icon: 'medal', name: 'Semifinalista en los Juegos Olímpicos París 2024', count: 1, details: 'Quinteto Ideal del Torneo Olímpico' },
      { icon: 'medal', name: 'Medalla de Bronce en el EuroBasket', count: 1, details: '2022 (Alemania)' },
      { icon: 'sparkles', name: '2º Puesto en la Votación a Mejor Sexto Hombre de la NBA', count: 1, details: '2020 (Oklahoma City Thunder)' },
    ],
    seasonAverages: {
      pts: '14.0',
      reb: '3.0',
      ast: '6.1',
      stl: '0.9',
      blk: '0.2',
      fgPct: '43.5%',
      threePct: '37.5%',
      ftPct: '83.6%',
    },
  },

  // ==========================================
  // MIAMI HEAT (MIA)
  // ==========================================
  'Giannis Antetokounmpo': {
    tacticalRole: 'La Fuerza Más Dominante del Planeta, Campeón de la NBA & 2x MVP (The Greek Freak)',
    specialty: 'Eurostep imparable de costa a costa, mates demoledores, tapones en recuperación y potencia pura',
    playStyle: 'El titán físico definitivo del baloncesto moderno y leyenda viva de la NBA',
    draftInfo: {
      year: 2013,
      round: 1,
      pick: 15,
      teamName: 'Milwaukee Bucks',
      teamAbbr: 'MIL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
      origin: 'Filathlitikos / Atenas, Grecia',
    },
    draft: '2013 · Pick #15 (1ª Ronda por Milwaukee Bucks)',
    experience: '12 Temporadas (Bucks / Heat)',
    transfers: [
      {
        season: '13/14',
        date: '27/06/2013',
        fromTeam: 'Filathlitikos',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '8,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 15)',
      },
      {
        season: '20/21',
        date: '15/12/2020',
        fromTeam: 'Milwaukee Bucks',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '228,00 mill. $',
        feeOrType: 'Supermax Extension Histórica (5 años / $228M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Milwaukee Bucks',
        fromTeamAbbr: 'MIL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '250,00 mill. $',
        feeOrType: 'Mega-Traspaso Generacional de la NBA a Miami',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2021 (Milwaukee Bucks — Anillo tras 50 años de sequía)' },
      { icon: 'sparkles', name: 'MVP de las Finales de la NBA (Bill Russell Trophy)', count: 1, details: '2021 (Histórico partido de 50 Puntos, 14 Rebotes y 5 Tapones en el Game 6)' },
      { icon: 'ribbon', name: '2x Consecutivo MVP de la Temporada Regular de la NBA', count: 2, details: '2019, 2020' },
      { icon: 'shield', name: 'Mejor Defensor del Año de la NBA (DPOY)', count: 1, details: '2020 (Uno de los 3 únicos jugadores en ganar MVP y DPOY el mismo año con Jordan y Olajuwon)' },
      { icon: 'star', name: '8x NBA All-Star (MVP del All-Star Game 2021 con 16/16 tiros)', count: 8, details: '2017-2024' },
      { icon: 'albums', name: '8x Seleccionado All-NBA (6x 1er Equipo, 2x 2º Equipo)', count: 8, details: '2017-2024' },
      { icon: 'shield', name: '5x 1er Equipo NBA All-Defensive', count: 5, details: '2019-2024' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2017' },
    ],
    seasonAverages: {
      pts: '30.4',
      reb: '11.5',
      ast: '6.5',
      stl: '1.2',
      blk: '1.1',
      fgPct: '61.1%',
      threePct: '27.4%',
      ftPct: '65.7%',
    },
  },

  'Bam Adebayo': {
    tacticalRole: 'Pívot All-Star Defensivo Supremo & 2x Medallista de Oro Olímpico (Bam Bam)',
    specialty: 'Defensa de cambio 1 al 5 insuperable, tapones de poster en playoffs, pases desde el codo y tiros de media distancia',
    playStyle: 'El mejor pívot defensor de perímetro y ancla de la Heat Culture',
    draftInfo: {
      year: 2017,
      round: 1,
      pick: 14,
      teamName: 'Miami Heat',
      teamAbbr: 'MIA',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
      origin: 'Kentucky Wildcats / Newark, New Jersey',
    },
    draft: '2017 · Pick #14 (1ª Ronda por Miami Heat)',
    experience: '8 Temporadas (Miami Heat)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '14,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 14 — One Club Man de Miami)',
      },
      {
        season: '20/21',
        date: '28/11/2020',
        fromTeam: 'Miami Heat',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '163,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $163M)',
      },
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'Miami Heat',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '166,00 mill. $',
        feeOrType: 'Extensión Máxima (3 años / $166M)',
      },
    ],
    awards: [
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Tokio 2020, París 2024' },
      { icon: 'shield', name: '1er Equipo NBA All-Defensive', count: 1, details: '2024 (5x All-Defensive Total)' },
      { icon: 'star', name: '3x NBA All-Star', count: 3, details: '2020, 2023, 2024' },
      { icon: 'trophy', name: '2x Finalista de la NBA & Campeón Conferencia Este', count: 2, details: '2020, 2023 (Miami Heat)' },
      { icon: 'trophy', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2020 (All-Star Weekend)' },
    ],
    seasonAverages: {
      pts: '19.3',
      reb: '10.4',
      ast: '3.9',
      stl: '1.1',
      blk: '0.9',
      fgPct: '52.1%',
      threePct: '35.7%',
      ftPct: '75.5%',
    },
  },

  // ==========================================
  // ORLANDO MAGIC (ORL)
  // ==========================================
  'Paolo Banchero': {
    tacticalRole: 'Alero Superestrella Generacional, Rookie del Año & Líder de Orlando (El Capo)',
    specialty: 'Potencia física inamovible hacia el aro, tiros en aclarado, visión de creador y clutch',
    playStyle: 'Alero dominante con cuerpo de pívot y habilidades de base, el futuro de la NBA',
    draftInfo: {
      year: 2022,
      round: 1,
      pick: 1,
      teamName: 'Orlando Magic',
      teamAbbr: 'ORL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
      origin: 'Duke Blue Devils / Seattle, Washington',
    },
    draft: '2022 · Pick #1 (1ª Ronda por Orlando Magic)',
    experience: '3 Temporadas (Orlando Magic)',
    transfers: [
      {
        season: '22/23',
        date: '23/06/2022',
        fromTeam: 'Duke Blue Devils',
        toTeam: 'Orlando Magic',
        toTeamAbbr: 'ORL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        marketValue: '50,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — Escala Rookie)',
      },
    ],
    awards: [
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY Casi Unánime)', count: 1, details: '2023 (98 de 100 votos)' },
      { icon: 'star', name: 'NBA All-Star (Con solo 21 años)', count: 1, details: '2024' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2023' },
      { icon: 'flame', name: 'Partido Histórico de 50 Puntos en la NBA', count: 1, details: '2024 vs Indiana Pacers (50 pts, 13 reb, 9 ast)' },
    ],
    seasonAverages: {
      pts: '23.0',
      reb: '7.0',
      ast: '5.4',
      stl: '0.9',
      blk: '0.6',
      fgPct: '46.0%',
      threePct: '34.0%',
      ftPct: '72.5%',
    },
  },

  'Franz Wagner': {
    tacticalRole: 'Alero All-Star Alemán, Campeón del Mundo FIBA & Francotirador Versátil',
    specialty: 'Penetraciones fluidas en cambio de dirección, tiros exteriores, lectura de pase y defensa',
    playStyle: 'Alero completo europeo y héroe del oro mundial alemán',
    draftInfo: {
      year: 2021,
      round: 1,
      pick: 8,
      teamName: 'Orlando Magic',
      teamAbbr: 'ORL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
      origin: 'Michigan Wolverines / Berlín, Alemania',
    },
    draft: '2021 · Pick #8 (1ª Ronda por Orlando Magic)',
    experience: '4 Temporadas (Orlando Magic)',
    transfers: [
      {
        season: '21/22',
        date: '29/07/2021',
        fromTeam: 'Michigan Wolverines',
        toTeam: 'Orlando Magic',
        toTeamAbbr: 'ORL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        marketValue: '22,70 mill. $',
        feeOrType: 'Draft de la NBA (Pick 8)',
      },
      {
        season: '24/25',
        date: '05/07/2024',
        fromTeam: 'Orlando Magic',
        toTeam: 'Orlando Magic',
        toTeamAbbr: 'ORL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/orl.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Extensión Máxima Designada (5 años / $224M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la Copa del Mundo FIBA & All-Tournament Team', count: 1, details: '2023 (Alemania invicta)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2022' },
      { icon: 'medal', name: 'Medalla de Bronce en EuroBasket', count: 1, details: '2022 (Alemania)' },
      { icon: 'medal', name: 'Semifinalista Olímpico París 2024', count: 1, details: 'Alemania' },
    ],
    seasonAverages: {
      pts: '20.0',
      reb: '5.3',
      ast: '4.0',
      stl: '1.1',
      blk: '0.4',
      fgPct: '48.2%',
      threePct: '32.0%',
      ftPct: '85.0%',
    },
  },

  // ==========================================
  // WASHINGTON WIZARDS (WAS)
  // ==========================================
  'Anthony Davis': {
    tacticalRole: 'Pívot / Ala-Pívot Superestrella Histórico, Campeón NBA, Campeón NBA Cup & 2x Oro Olímpico (The Brow)',
    specialty: 'Defensa de aro impenetrable (líder en tapones), anotación al poste, rebotes colosales y tiros de media distancia',
    playStyle: 'Uno de los interiores más dominantes y completos de la historia del baloncesto',
    draftInfo: {
      year: 2012,
      round: 1,
      pick: 1,
      teamName: 'New Orleans Hornets',
      teamAbbr: 'NOP',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
      origin: 'Kentucky Wildcats / Chicago, Illinois',
    },
    draft: '2012 · Pick #1 (1ª Ronda por New Orleans Hornets)',
    experience: '13 Temporadas (Pelicans / Lakers / Wizards)',
    transfers: [
      {
        season: '12/13',
        date: '28/06/2012',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'New Orleans Hornets',
        toTeamAbbr: 'NOP',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        marketValue: '23,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1)',
      },
      {
        season: '19/20',
        date: '06/07/2019',
        fromTeam: 'New Orleans Pelicans',
        fromTeamAbbr: 'NOP',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/no.png',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '190,00 mill. $',
        feeOrType: 'Mega-Traspaso Histórico (Campeón del Anillo 2020)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Washington Wizards',
        toTeamAbbr: 'WAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        marketValue: '186,00 mill. $',
        feeOrType: 'Mega-Traspaso de Franquicia',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2020 (Los Angeles Lakers — 27.7 ppp y 9.7 rpp en Playoffs)' },
      { icon: 'trophy', name: 'Campeón de la 1ª NBA Cup (In-Season Tournament)', count: 1, details: '2023 (Los Angeles Lakers — Monstruosa actuación de 41 Puntos y 20 Rebotes en la Final)' },
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Londres 2012, París 2024 (Protector de aro clave en la medalla de oro)' },
      { icon: 'star', name: '9x NBA All-Star (MVP del All-Star Game 2017 con 52 Puntos Récord)', count: 9, details: '2014-2021, 2024' },
      { icon: 'albums', name: '4x 1er Equipo All-NBA & 1x 2º Equipo All-NBA', count: 5, details: '2015, 2017, 2018, 2020 (1º) / 2024 (2º)' },
      { icon: 'shield', name: '5x NBA All-Defensive Team (3x 1er Equipo, 2x 2º Equipo)', count: 5, details: '2015, 2017, 2018, 2020, 2024' },
      { icon: 'flame', name: '3x Máximo Taponador de la NBA (Blocks Leader)', count: 3, details: '2014, 2015, 2018' },
      { icon: 'trophy', name: 'Campeón Nacional de la NCAA & MOP de la Final Four', count: 1, details: '2012 (Kentucky Wildcats)' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
    ],
    seasonAverages: {
      pts: '24.7',
      reb: '12.6',
      ast: '3.5',
      stl: '1.2',
      blk: '2.3',
      fgPct: '55.6%',
      threePct: '27.1%',
      ftPct: '81.6%',
    },
  },

  'Trae Young': {
    tacticalRole: 'Base Superestrella Mago del Pase & Francotirador Letal (Ice Trae)',
    specialty: 'Triples kilométricos desde 11 metros, flotadoras altas sobre pívots y pases de fantasía de alley-oop',
    playStyle: 'El único jugador moderno en liderar la NBA en puntos totales y asistencias en la misma temporada',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 5,
      teamName: 'Dallas Mavericks (Traspasado a Hawks)',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Oklahoma Sooners / Lubbock, Texas',
    },
    draft: '2018 · Pick #5 (1ª Ronda por Dallas Mavericks)',
    experience: '7 Temporadas (Hawks / Wizards)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Oklahoma Sooners',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '26,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 5 / Traspaso Luka Doncic)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Atlanta Hawks',
        fromTeamAbbr: 'ATL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        toTeam: 'Washington Wizards',
        toTeamAbbr: 'WAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        marketValue: '215,00 mill. $',
        feeOrType: 'Mega-Traspaso de Base Estrella',
      },
    ],
    awards: [
      { icon: 'star', name: '3x NBA All-Star (2x Titular)', count: 3, details: '2020, 2022, 2024' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2022' },
      { icon: 'flame', name: 'Líder en Puntos Totales y Asistencias Totales de la NBA', count: 1, details: '2021-22 (2.155 pts y 737 ast — Hito histórico)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2019' },
      { icon: 'sparkles', name: 'Finalista Conferencia Este', count: 1, details: '2021 (Atlanta Hawks)' },
    ],
    seasonAverages: {
      pts: '25.7',
      reb: '2.8',
      ast: '10.8',
      stl: '1.3',
      blk: '0.2',
      fgPct: '43.0%',
      threePct: '37.3%',
      ftPct: '85.5%',
    },
  },
};
