import { PlayerDossier } from './playerDossier';

export const PACIFIC_DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {
  // ==========================================
  // GOLDEN STATE WARRIORS (GSW)
  // ==========================================
  'Stephen Curry': {
    tacticalRole: 'El Mejor Tirador de la Historia del Baloncesto Mundial, 4x Campeón & Oro Olímpico (Chef Curry / Baby-Faced Assassin)',
    specialty: 'Triples imposibles desde cualquier distancia (+3.700 triples), movimiento sin balón inagotable, manejo de balón y clutch divino',
    playStyle: 'Revolucionó para siempre el deporte del baloncesto, el jugador ofensivo más influyente del siglo XXI',
    draftInfo: {
      year: 2009,
      round: 1,
      pick: 7,
      teamName: 'Golden State Warriors',
      teamAbbr: 'GSW',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
      origin: 'Davidson Wildcats / Akron, Ohio',
    },
    draft: '2009 · Pick #7 (1ª Ronda por Golden State Warriors)',
    experience: '16 Temporadas (Golden State Warriors)',
    transfers: [
      {
        season: '09/10',
        date: '25/06/2009',
        fromTeam: 'Davidson Wildcats',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '12,70 mill. $',
        feeOrType: 'Draft de la NBA (Pick 7 — One Club Man de Leyenda)',
      },
      {
        season: '17/18',
        date: '01/07/2017',
        fromTeam: 'Golden State Warriors',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '201,00 mill. $',
        feeOrType: 'Primer Supermax Contract de $200M+ en la Historia NBA (5 años / $201M)',
      },
      {
        season: '24/25',
        date: '29/08/2024',
        fromTeam: 'Golden State Warriors',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '62,60 mill. $',
        feeOrType: 'Extensión de Contrato Histórica (1 año / $62.6M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: '4x Campeón de la NBA', count: 4, details: '2015, 2017, 2018, 2022 (Golden State Warriors Dynasty)' },
      { icon: 'sparkles', name: 'MVP de las Finales de la NBA (Bill Russell Trophy)', count: 1, details: '2022 vs Boston Celtics (31.2 ppp y 5.2 triples por noche)' },
      { icon: 'ribbon', name: '2x MVP de la Temporada Regular de la NBA', count: 2, details: '2015, 2016 (Único MVP Unánime en la Historia de la NBA - 131 de 131 votos)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024 (Ráfaga legendaria de 8 triples en semis vs Serbia y 4 triples clutch en la Final vs Francia - Nuit Nuit)' },
      { icon: 'flame', name: 'Máximo Triplista de la Historia del Baloncesto (+3.700 Triples)', count: 1, details: 'Superando el récord histórico de Ray Allen' },
      { icon: 'star', name: '10x NBA All-Star (MVP del All-Star Game 2022 con 16 Triples)', count: 10, details: '2014-2024' },
      { icon: 'albums', name: '10x Seleccionado All-NBA (4x 1er Equipo, 5x 2º Equipo, 1x 3er Equipo)', count: 10, details: '2014-2024' },
      { icon: 'flame', name: '2x Máximo Anotador de la NBA (Scoring Champion)', count: 2, details: '2016 (30.1 ppp / Club 50-40-90), 2021 (32.0 ppp)' },
      { icon: 'trophy', name: '2x Campeón Concurso de Triples NBA All-Star', count: 2, details: '2015, 2021' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
    ],
    seasonAverages: {
      pts: '26.4',
      reb: '4.5',
      ast: '5.1',
      stl: '0.7',
      blk: '0.4',
      fgPct: '45.0%',
      threePct: '40.8%',
      ftPct: '92.3%',
    },
  },

  'Jimmy Butler III': {
    tacticalRole: 'Alero Superestrella Guerrero, 2x Finalista de la NBA & Clutch de Élite (Jimmy Buckets / Playoff Jimmy)',
    specialty: 'Competitividad salvaje, provocación de faltas en penetración, defensa de élite sobre la estrella rival y liderazgo',
    playStyle: 'Uno de los competidores más feroces y determinantes de la historia moderna de los playoffs',
    draftInfo: {
      year: 2011,
      round: 1,
      pick: 30,
      teamName: 'Chicago Bulls',
      teamAbbr: 'CHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
      origin: 'Marquette Golden Eagles / Tomball, Texas',
    },
    draft: '2011 · Pick #30 (1ª Ronda por Chicago Bulls)',
    experience: '14 Temporadas (Bulls / Timberwolves / 76ers / Heat / Warriors)',
    transfers: [
      {
        season: '11/12',
        date: '23/06/2011',
        fromTeam: 'Marquette Golden Eagles',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '5,30 mill. $',
        feeOrType: 'Draft de la NBA (Pick 30)',
      },
      {
        season: '19/20',
        date: '06/07/2019',
        fromTeam: 'Philadelphia 76ers',
        fromTeamAbbr: 'PHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        toTeam: 'Miami Heat',
        toTeamAbbr: 'MIA',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        marketValue: '142,00 mill. $',
        feeOrType: 'Sign & Trade a 4 Bandas (Era Dorada de Miami)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Miami Heat',
        fromTeamAbbr: 'MIA',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mia.png',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '98,00 mill. $',
        feeOrType: 'Mega-Traspaso de Franquicia para pelear el anillo junto a Curry',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Finalista de la NBA como Líder Absoluto', count: 2, details: '2020, 2023 (Miami Heat — Eliminando a Bucks y Celtics)' },
      { icon: 'ribbon', name: 'MVP de Finales de Conferencia Este (Larry Bird Trophy)', count: 1, details: '2023 (Miami Heat)' },
      { icon: 'star', name: '6x NBA All-Star', count: 6, details: '2015, 2016, 2017, 2018, 2020, 2022' },
      { icon: 'albums', name: '5x Seleccionado All-NBA (1x 2º Equipo, 4x 3er Equipo)', count: 5, details: '2017, 2018, 2020, 2021, 2023' },
      { icon: 'shield', name: '5x 2º Equipo NBA All-Defensive', count: 5, details: '2014, 2015, 2016, 2018, 2021' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Río 2016' },
      { icon: 'sparkles', name: 'Jugador Más Mejorado de la NBA (MIP)', count: 1, details: '2015' },
      { icon: 'flame', name: 'Líder en Robos de la NBA', count: 1, details: '2020-21 (2.1 robos por partido)' },
    ],
    seasonAverages: {
      pts: '20.8',
      reb: '5.3',
      ast: '5.0',
      stl: '1.3',
      blk: '0.3',
      fgPct: '49.9%',
      threePct: '41.4%',
      ftPct: '85.8%',
    },
  },

  'Kristaps Porzingis': {
    tacticalRole: 'Pívot Gigante Stretch-5, Campeón de la NBA & Protector de Pintura (The Unicorn)',
    specialty: 'Triples desde 9 metros con 2,18m de altura, tapones intimidatorios de aro y anotación al poste',
    playStyle: 'Unicornio letal en ataque y muro infranqueable en defensa con anillo de campeón',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 4,
      teamName: 'New York Knicks',
      teamAbbr: 'NYK',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
      origin: 'Baloncesto Sevilla / Letonia',
    },
    draft: '2015 · Pick #4 (1ª Ronda por New York Knicks)',
    experience: '9 Temporadas (Knicks / Mavericks / Wizards / Celtics / Warriors)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Baloncesto Sevilla',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '18,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 4)',
      },
      {
        season: '23/24',
        date: '23/06/2023',
        fromTeam: 'Washington Wizards',
        fromTeamAbbr: 'WAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Traspaso a 3 Bandas (Campeón de la NBA 2024)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '60,00 mill. $',
        feeOrType: 'Traspaso de Estrella Campeona',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Actuación colosal en el Game 1 de las Finales)' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2018' },
      { icon: 'trophy', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2017 (All-Star Weekend)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2016' },
      { icon: 'sparkles', name: 'EuroCup Rising Star', count: 1, details: '2015' },
    ],
    seasonAverages: {
      pts: '20.1',
      reb: '7.2',
      ast: '2.0',
      stl: '0.7',
      blk: '1.9',
      fgPct: '51.6%',
      threePct: '37.5%',
      ftPct: '85.8%',
    },
  },

  'Al Horford': {
    tacticalRole: 'Pívot Campeón de la NBA, Leyenda Dominicana & Maestro Táctico (Big Al)',
    specialty: 'Defensa posicional sobre gigantes (Embiid, Jokic, Giannis), triples de esquina automáticos y liderazgo',
    playStyle: 'Veterano con IQ de Salón de la Fama y primer dominicano campeón de la NBA',
    draftInfo: {
      year: 2007,
      round: 1,
      pick: 3,
      teamName: 'Atlanta Hawks',
      teamAbbr: 'ATL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
      origin: 'Florida Gators / Puerto Plata, República Dominicana',
    },
    draft: '2007 · Pick #3 (1ª Ronda por Atlanta Hawks)',
    experience: '18 Temporadas (Hawks / Celtics / 76ers / Thunder / Warriors)',
    transfers: [
      {
        season: '07/08',
        date: '28/06/2007',
        fromTeam: 'Florida Gators',
        toTeam: 'Atlanta Hawks',
        toTeamAbbr: 'ATL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/atl.png',
        marketValue: '17,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '21/22',
        date: '18/06/2021',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'Boston Celtics',
        toTeamAbbr: 'BOS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        marketValue: '54,00 mill. $',
        feeOrType: 'Regreso a Boston (Campeón del Anillo 2024)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Boston Celtics',
        fromTeamAbbr: 'BOS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bos.png',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '19,00 mill. $',
        feeOrType: 'Traspaso de Veterano Campeón',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2024 (Boston Celtics — Primer dominicano en la historia en ganar el anillo)' },
      { icon: 'trophy', name: '2x Campeón Consecutivo de la NCAA', count: 2, details: '2006, 2007 (Florida Gators)' },
      { icon: 'star', name: '5x NBA All-Star', count: 5, details: '2010, 2011, 2015, 2016, 2018' },
      { icon: 'albums', name: '3er Equipo All-NBA (2011) & 2º Equipo All-Defensive (2018)', count: 2, details: 'Reconocimiento élite' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2008' },
    ],
    seasonAverages: {
      pts: '8.6',
      reb: '6.4',
      ast: '2.6',
      stl: '0.6',
      blk: '1.0',
      fgPct: '51.1%',
      threePct: '41.9%',
      ftPct: '86.7%',
    },
  },

  'Draymond Green': {
    tacticalRole: 'Ala-Pívot Director Defensivo, 4x Campeón de la NBA & Mejor Defensor del Año (Dray)',
    specialty: 'Dirección de la defensa en voz alta, visión de pase en contraataques para Curry, pantallas y dureza mental',
    playStyle: 'El cerebro defensivo y pasador de la dinastía de los Warriors',
    draftInfo: {
      year: 2012,
      round: 2,
      pick: 35,
      teamName: 'Golden State Warriors',
      teamAbbr: 'GSW',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
      origin: 'Michigan State Spartans / Saginaw, Michigan',
    },
    draft: '2012 · Pick #35 (2ª Ronda por Golden State Warriors)',
    experience: '13 Temporadas (Golden State Warriors)',
    transfers: [
      {
        season: '12/13',
        date: '28/06/2012',
        fromTeam: 'Michigan State',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '2,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 35 — One Club Man de Leyenda)',
      },
      {
        season: '23/24',
        date: '08/07/2023',
        fromTeam: 'Golden State Warriors',
        toTeam: 'Golden State Warriors',
        toTeamAbbr: 'GSW',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/gs.png',
        marketValue: '100,00 mill. $',
        feeOrType: 'Extensión de Contrato (4 años / $100M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: '4x Campeón de la NBA', count: 4, details: '2015, 2017, 2018, 2022 (Golden State Warriors)' },
      { icon: 'shield', name: 'Mejor Defensor del Año de la NBA (DPOY)', count: 1, details: '2017' },
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Río 2016, Tokio 2020' },
      { icon: 'star', name: '4x NBA All-Star', count: 4, details: '2016, 2017, 2018, 2022' },
      { icon: 'shield', name: '8x NBA All-Defensive Team (4x 1er Equipo, 4x 2º Equipo)', count: 8, details: '2015-2023' },
      { icon: 'albums', name: '2x Seleccionado All-NBA (2º Equipo 2016, 3er Equipo 2017)', count: 2, details: '2016, 2017' },
      { icon: 'flame', name: 'Líder en Robos de la NBA', count: 1, details: '2016-17 (2.0 robos por partido)' },
    ],
    seasonAverages: {
      pts: '8.6',
      reb: '7.2',
      ast: '6.0',
      stl: '1.0',
      blk: '0.9',
      fgPct: '49.7%',
      threePct: '39.5%',
      ftPct: '73.0%',
    },
  },

  // ==========================================
  // LA CLIPPERS (LAC)
  // ==========================================
  'Kawhi Leonard': {
    tacticalRole: 'Alero Superestrella 2x Campeón de la NBA, 2x MVP de Finales & Asesino Silencioso (The Klaw)',
    specialty: 'Manos gigantescas (28cm), defensa de balón destructiva, tiro en suspensión de media distancia y frialdad',
    playStyle: 'Uno de los jugadores más dominantes en ambos lados de la cancha en la historia del baloncesto',
    draftInfo: {
      year: 2011,
      round: 1,
      pick: 15,
      teamName: 'Indiana Pacers (Traspasado a Spurs)',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'San Diego State Aztecs / Los Ángeles, California',
    },
    draft: '2011 · Pick #15 (1ª Ronda por Indiana Pacers)',
    experience: '13 Temporadas (Spurs / Raptors / Clippers)',
    transfers: [
      {
        season: '11/12',
        date: '23/06/2011',
        fromTeam: 'San Diego State',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '8,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 15 / Traspaso por George Hill)',
      },
      {
        season: '18/19',
        date: '18/07/2018',
        fromTeam: 'San Antonio Spurs',
        fromTeamAbbr: 'SAS',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        toTeam: 'Toronto Raptors',
        toTeamAbbr: 'TOR',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        marketValue: '94,00 mill. $',
        feeOrType: 'Mega-Traspaso Histórico (Campeón y Anillo Histórico con Toronto 2019)',
      },
      {
        season: '19/20',
        date: '10/07/2019',
        fromTeam: 'Toronto Raptors',
        fromTeamAbbr: 'TOR',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/tor.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '103,00 mill. $',
        feeOrType: 'Agencia Libre (3 años / $103M)',
      },
      {
        season: '24/25',
        date: '10/01/2024',
        fromTeam: 'LA Clippers',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '153,00 mill. $',
        feeOrType: 'Extensión de Contrato Máxima (3 años / $153M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón de la NBA con Franquicias Distintas', count: 2, details: '2014 (San Antonio Spurs), 2019 (Toronto Raptors)' },
      { icon: 'sparkles', name: '2x MVP de las Finales de la NBA (Bill Russell Trophy)', count: 2, details: '2014 (Secando a LeBron), 2019 (Tiro sobre la bocina histórico del Game 7 vs 76ers)' },
      { icon: 'shield', name: '2x Defensor del Año de la NBA (DPOY Consecutivo)', count: 2, details: '2015, 2016' },
      { icon: 'star', name: '6x NBA All-Star (MVP del All-Star Game 2020 - Kobe Bryant Trophy)', count: 6, details: '2016, 2017, 2019, 2020, 2021, 2024' },
      { icon: 'albums', name: '6x Seleccionado All-NBA (3x 1er Equipo, 3x 2º Equipo)', count: 6, details: '2016, 2017, 2021 (1º) / 2019, 2020, 2024 (2º)' },
      { icon: 'shield', name: '7x NBA All-Defensive Team (3x 1er Equipo, 4x 2º Equipo)', count: 7, details: '2015-2021' },
      { icon: 'sparkles', name: 'Miembro del Equipo del 75 Aniversario de la NBA', count: 1, details: 'Top 75 Histórico' },
    ],
    seasonAverages: {
      pts: '23.7',
      reb: '6.1',
      ast: '3.6',
      stl: '1.6',
      blk: '0.9',
      fgPct: '52.5%',
      threePct: '41.7%',
      ftPct: '88.5%',
    },
  },

  'Darius Garland': {
    tacticalRole: 'Base All-Star Mago del Dribling & Francotirador (DG The Florist)',
    specialty: 'Crossovers con cambio de dirección letal, triples en pull-up y pases picados de alley-oop',
    playStyle: 'Base superestrella puro de gran visión anotadora y organizadora',
    draftInfo: {
      year: 2019,
      round: 1,
      pick: 5,
      teamName: 'Cleveland Cavaliers',
      teamAbbr: 'CLE',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
      origin: 'Vanderbilt Commodores',
    },
    draft: '2019 · Pick #5 (1ª Ronda por Cleveland Cavaliers)',
    experience: '6 Temporadas (Cavaliers / Clippers)',
    transfers: [
      {
        season: '19/20',
        date: '20/06/2019',
        fromTeam: 'Vanderbilt',
        toTeam: 'Cleveland Cavaliers',
        toTeamAbbr: 'CLE',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        marketValue: '29,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 5)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Cleveland Cavaliers',
        fromTeamAbbr: 'CLE',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/cle.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '197,00 mill. $',
        feeOrType: 'Mega-Traspaso de Base Estrella',
      },
    ],
    awards: [
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2022' },
      { icon: 'flame', name: 'Partido Histórico de 51 Puntos en la NBA', count: 1, details: '13/11/2022 vs Minnesota Timberwolves' },
      { icon: 'sparkles', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2022' },
    ],
    seasonAverages: {
      pts: '18.0',
      reb: '2.7',
      ast: '6.5',
      stl: '1.3',
      blk: '0.1',
      fgPct: '44.6%',
      threePct: '37.1%',
      ftPct: '83.4%',
    },
  },

  'Bradley Beal': {
    tacticalRole: 'Escolta Anotador de 30+ Puntos & 3x All-Star (Big Panda)',
    specialty: 'Anotación fluida en tres niveles, salida de bloqueos indirectos y tiros en suspensión clutch',
    playStyle: 'Uno de los escoltas anotadores más prolíficos y elegantes de la década',
    draftInfo: {
      year: 2012,
      round: 1,
      pick: 3,
      teamName: 'Washington Wizards',
      teamAbbr: 'WAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
      origin: 'Florida Gators / St. Louis, Missouri',
    },
    draft: '2012 · Pick #3 (1ª Ronda por Washington Wizards)',
    experience: '13 Temporadas (Wizards / Suns / Clippers)',
    transfers: [
      {
        season: '12/13',
        date: '28/06/2012',
        fromTeam: 'Florida Gators',
        toTeam: 'Washington Wizards',
        toTeamAbbr: 'WAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/was.png',
        marketValue: '18,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '150,00 mill. $',
        feeOrType: 'Traspaso de Superestrella Anotadora',
      },
    ],
    awards: [
      { icon: 'star', name: '3x NBA All-Star (Titular 2021)', count: 3, details: '2018, 2019, 2021' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2021 (31.3 ppp)' },
      { icon: 'flame', name: '2x Temporadas Consecutivas de 30+ Puntos por Partido', count: 2, details: '2019-20 (30.5 ppp), 2020-21 (31.3 ppp)' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2013' },
    ],
    seasonAverages: {
      pts: '18.2',
      reb: '4.4',
      ast: '5.0',
      stl: '1.0',
      blk: '0.5',
      fgPct: '51.3%',
      threePct: '43.0%',
      ftPct: '81.3%',
    },
  },

  'Brook Lopez': {
    tacticalRole: 'Pívot Campeón de la NBA, Stretch-5 Legendario & Máximo Taponador (Splash Mountain)',
    specialty: 'Tapones verticales con 2,16m, triples frontales y anotación de espaldas al aro',
    playStyle: 'Pívot que reinventó su carrera de clásico al poste a francotirador y ancla defensiva de campeonato',
    draftInfo: {
      year: 2008,
      round: 1,
      pick: 10,
      teamName: 'New Jersey Nets',
      teamAbbr: 'BKN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
      origin: 'Stanford Cardinal',
    },
    draft: '2008 · Pick #10 (1ª Ronda por New Jersey Nets)',
    experience: '17 Temporadas (Nets / Lakers / Bucks / Clippers)',
    transfers: [
      {
        season: '08/09',
        date: '26/06/2008',
        fromTeam: 'Stanford Cardinal',
        toTeam: 'New Jersey Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '10,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 10)',
      },
      {
        season: '18/19',
        date: '17/07/2018',
        fromTeam: 'Los Angeles Lakers',
        fromTeamAbbr: 'LAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        toTeam: 'Milwaukee Bucks',
        toTeamAbbr: 'MIL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        marketValue: '3,40 mill. $',
        feeOrType: 'Agencia Libre (Campeón de la NBA 2021)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Milwaukee Bucks',
        fromTeamAbbr: 'MIL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mil.png',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '48,00 mill. $',
        feeOrType: 'Traspaso de Pívot Campeón',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la NBA', count: 1, details: '2021 (Milwaukee Bucks)' },
      { icon: 'star', name: 'NBA All-Star', count: 1, details: '2013' },
      { icon: 'shield', name: '2x 1er Equipo NBA All-Defensive', count: 2, details: '2020, 2023 (Finalista al DPOY)' },
      { icon: 'flame', name: 'Máximo Anotador Histórico de Brooklyn Nets', count: 1, details: '10.444 Puntos con la franquicia' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2009' },
    ],
    seasonAverages: {
      pts: '12.5',
      reb: '5.2',
      ast: '1.6',
      stl: '0.5',
      blk: '2.4',
      fgPct: '48.5%',
      threePct: '36.6%',
      ftPct: '82.1%',
    },
  },

  // ==========================================
  // LOS ANGELES LAKERS (LAL)
  // ==========================================
  'Luka Doncic': {
    tacticalRole: 'El Genio del Baloncesto Mundial, Finalista de la NBA & Máximo Anotador (Luka Magic)',
    specialty: 'Pases de fantasía sin mirar, step-back triple imparable, dobles y triples-dobles de 40+ puntos y visión de juego',
    playStyle: 'El creador y anotador más virtuoso del planeta, 5 veces 1er Equipo All-NBA antes de los 26 años',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 3,
      teamName: 'Atlanta Hawks (Traspasado a Mavericks)',
      teamAbbr: 'DAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
      origin: 'Real Madrid Baloncesto / Eslovenia',
    },
    draft: '2018 · Pick #3 (1ª Ronda por Atlanta Hawks)',
    experience: '7 Temporadas (Real Madrid / Mavericks / Lakers)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Real Madrid Baloncesto',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '32,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 3 / Traspasado por Trae Young + 1ª ronda)',
      },
      {
        season: '22/23',
        date: '10/08/2021',
        fromTeam: 'Dallas Mavericks',
        toTeam: 'Dallas Mavericks',
        toTeamAbbr: 'DAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        marketValue: '215,00 mill. $',
        feeOrType: 'Designated Rookie Supermax Extension (5 años / $215M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Dallas Mavericks',
        fromTeamAbbr: 'DAL',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/dal.png',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '215,00 mill. $',
        feeOrType: 'Mega-Traspaso Generacional de Franquicia a Los Angeles Lakers',
      },
    ],
    awards: [
      { icon: 'albums', name: '5x Consecutivo 1er Equipo All-NBA', count: 5, details: '2020, 2021, 2022, 2023, 2024 (Récord histórico de precocidad)' },
      { icon: 'trophy', name: 'Finalista de la NBA & Campeón de la Conferencia Oeste', count: 1, details: '2024 (Dallas Mavericks — MVP de Finales del Oeste Magic Johnson Trophy)' },
      { icon: 'flame', name: 'Máximo Anotador de la NBA (Scoring Champion)', count: 1, details: '2023-24 (33.9 puntos por partido)' },
      { icon: 'star', name: '5x NBA All-Star (4x Titular)', count: 5, details: '2020, 2021, 2022, 2023, 2024' },
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2019' },
      { icon: 'flame', name: 'Partido Histórico de 73 Puntos en la NBA', count: 1, details: '26/01/2024 vs Atlanta Hawks (4ª mayor anotación de todos los tiempos)' },
      { icon: 'trophy', name: 'Campeón & MVP de la Euroliga', count: 1, details: '2018 (Real Madrid — Jugador más joven en ganar el MVP con 19 años)' },
      { icon: 'medal', name: 'Campeón del EuroBasket', count: 1, details: '2017 (Eslovenia invicta)' },
    ],
    seasonAverages: {
      pts: '33.9',
      reb: '9.2',
      ast: '9.8',
      stl: '1.4',
      blk: '0.5',
      fgPct: '48.7%',
      threePct: '38.2%',
      ftPct: '78.6%',
    },
  },

  'Austin Reaves': {
    tacticalRole: 'Escolta Creador Clutch, Campeón de la NBA Cup & Estrella de Los Ángeles (Hillbilly Kobe / AR-15)',
    specialty: 'Provocación de faltas en contacto, tiros clutch en finales apretados, pick-and-roll inteligente y tiro exterior',
    playStyle: 'Ídolo absoluto de la afición de Lakers y uno de los jugadores no drafteados de mayor impacto en la NBA moderna',
    draftInfo: {
      year: 2021,
      round: 0,
      pick: 0,
      teamName: 'Los Angeles Lakers (Undrafted)',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Oklahoma Sooners / Wichita State',
    },
    draft: '2021 · Agente Libre No Drafteado (Fichado por Los Angeles Lakers)',
    experience: '4 Temporadas (Los Angeles Lakers)',
    transfers: [
      {
        season: '21/22',
        date: '03/08/2021',
        fromTeam: 'Oklahoma Sooners',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '2,50 mill. $',
        feeOrType: 'Two-Way a Contrato Estándar NBA',
      },
      {
        season: '23/24',
        date: '06/07/2023',
        fromTeam: 'Los Angeles Lakers',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '56,00 mill. $',
        feeOrType: 'Extensión de Contrato Multianual (4 años / $56M)',
      },
    ],
    awards: [
      { icon: 'trophy', name: 'Campeón de la 1ª NBA Cup (In-Season Tournament)', count: 1, details: '2023 (Los Angeles Lakers — 28 pts en la Final vs Pacers con gripe)' },
      { icon: 'medal', name: 'Estrella de Team USA en el Mundial FIBA', count: 1, details: '2023' },
      { icon: 'sparkles', name: 'Finalista Conferencia Oeste', count: 1, details: '2023 (Los Angeles Lakers)' },
      { icon: 'flame', name: 'Partido de 45 Puntos y Triple Ganador sobre la Bocina', count: 1, details: 'Vs Dallas Mavericks' },
    ],
    seasonAverages: {
      pts: '16.9',
      reb: '4.5',
      ast: '5.8',
      stl: '0.9',
      blk: '0.3',
      fgPct: '48.6%',
      threePct: '36.7%',
      ftPct: '85.3%',
    },
  },

  'Dalton Knecht': {
    tacticalRole: 'Francotirador de Perímetro Eléctrico & Sensación Anotadora de Lakers',
    specialty: 'Triples en rachas incendiarias (múltiples triples seguidos), salto para machacar en carrera y anotación en transición',
    playStyle: 'Anotador implacable con rango NBA inmediato',
    draftInfo: {
      year: 2024,
      round: 1,
      pick: 17,
      teamName: 'Los Angeles Lakers',
      teamAbbr: 'LAL',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
      origin: 'Tennessee Volunteers / Northern Colorado',
    },
    draft: '2024 · Pick #17 (1ª Ronda por Los Angeles Lakers)',
    experience: '2 Temporadas (Los Angeles Lakers)',
    transfers: [
      {
        season: '24/25',
        date: '26/06/2024',
        fromTeam: 'Tennessee Volunteers',
        toTeam: 'Los Angeles Lakers',
        toTeamAbbr: 'LAL',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lal.png',
        marketValue: '18,50 mill. $',
        feeOrType: 'Draft de la NBA (Pick 17 — Escala Rookie)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Jugador del Año de la SEC', count: 1, details: '2024 (Tennessee Volunteers)' },
      { icon: 'albums', name: '1er Equipo Consensus All-American', count: 1, details: '2024' },
      { icon: 'flame', name: 'Premio Julius Erving al Mejor Alero Universitario', count: 1, details: '2024' },
    ],
    seasonAverages: {
      pts: '14.2',
      reb: '3.6',
      ast: '1.8',
      stl: '0.7',
      blk: '0.3',
      fgPct: '47.0%',
      threePct: '41.5%',
      ftPct: '83.0%',
    },
  },

  // ==========================================
  // PHOENIX SUNS (PHX)
  // ==========================================
  'Devin Booker': {
    tacticalRole: 'Escolta Superestrella Anotador de 70 Puntos & 2x Medallista de Oro Olímpico (Book)',
    specialty: 'Tiro de media distancia automático, juego en aclarado imparable, triples clutch y lectura como base',
    playStyle: 'Uno de los escoltas anotadores más letales, técnicos y letales del planeta',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 13,
      teamName: 'Phoenix Suns',
      teamAbbr: 'PHX',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
      origin: 'Kentucky Wildcats / Grandville, Michigan',
    },
    draft: '2015 · Pick #13 (1ª Ronda por Phoenix Suns)',
    experience: '10 Temporadas (Phoenix Suns)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '9,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13 — One Club Man de Phoenix)',
      },
      {
        season: '18/19',
        date: '07/07/2018',
        fromTeam: 'Phoenix Suns',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '158,00 mill. $',
        feeOrType: 'Extensión Máxima (5 años / $158M)',
      },
      {
        season: '24/25',
        date: '07/07/2022',
        fromTeam: 'Phoenix Suns',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Supermax Extension (4 años / $224M)',
      },
    ],
    awards: [
      { icon: 'medal', name: '2x Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Tokio 2020, París 2024 (Titular indiscutible y pegamento táctico)' },
      { icon: 'flame', name: 'Partido Histórico de 70 Puntos en la NBA', count: 1, details: '24/03/2017 vs Boston Celtics (Jugador más joven de la historia en lograrlo)' },
      { icon: 'trophy', name: 'Finalista de la NBA & Campeón de la Conferencia Oeste', count: 1, details: '2021 (Phoenix Suns)' },
      { icon: 'star', name: '4x NBA All-Star', count: 4, details: '2020, 2021, 2022, 2024' },
      { icon: 'albums', name: '1er Equipo All-NBA (2022) & 3er Equipo All-NBA (2024)', count: 2, details: 'Reconocimiento élite' },
      { icon: 'trophy', name: 'Campeón del Concurso de Triples NBA All-Star (3-Point Contest)', count: 1, details: '2018' },
      { icon: 'shield-checkmark', name: '1er Equipo NBA All-Rookie', count: 1, details: '2016' },
    ],
    seasonAverages: {
      pts: '27.1',
      reb: '4.5',
      ast: '6.9',
      stl: '0.9',
      blk: '0.4',
      fgPct: '49.2%',
      threePct: '36.4%',
      ftPct: '88.6%',
    },
  },

  'Dillon Brooks': {
    tacticalRole: 'Especialista Defensivo Perimetral & Provocador de Élite (The Villain)',
    specialty: 'Defensa cuerpo a cuerpo destructiva, presión psicológica constante, triples y carácter',
    playStyle: 'Defensor de choque implacable y medallista mundial',
    draftInfo: {
      year: 2017,
      round: 2,
      pick: 45,
      teamName: 'Houston Rockets (Traspasado a Grizzlies)',
      teamAbbr: 'MEM',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
      origin: 'Oregon Ducks / Mississauga, Canadá',
    },
    draft: '2017 · Pick #45 (2ª Ronda por Houston Rockets)',
    experience: '8 Temporadas (Grizzlies / Rockets / Suns)',
    transfers: [
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Oregon Ducks',
        toTeam: 'Memphis Grizzlies',
        toTeamAbbr: 'MEM',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        marketValue: '3,80 mill. $',
        feeOrType: 'Draft de la NBA (Pick 45)',
      },
      {
        season: '23/24',
        date: '08/07/2023',
        fromTeam: 'Memphis Grizzlies',
        fromTeamAbbr: 'MEM',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/mem.png',
        toTeam: 'Houston Rockets',
        toTeamAbbr: 'HOU',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        marketValue: '86,00 mill. $',
        feeOrType: 'Sign & Trade (4 años / $86M)',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Houston Rockets',
        fromTeamAbbr: 'HOU',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/hou.png',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '86,00 mill. $',
        feeOrType: 'Traspaso de Perro de Presa Defensivo',
      },
    ],
    awards: [
      { icon: 'shield', name: '2º Equipo NBA All-Defensive', count: 1, details: '2023' },
      { icon: 'medal', name: 'Mejor Defensor de la Copa del Mundo FIBA & Medalla de Bronce', count: 1, details: '2023 (Canadá — 39 puntos en el partido por el bronce vs Team USA)' },
      { icon: 'sparkles', name: 'Jugador del Año de la Pac-12', count: 1, details: '2017 (Oregon)' },
    ],
    seasonAverages: {
      pts: '13.0',
      reb: '3.6',
      ast: '1.7',
      stl: '0.9',
      blk: '0.2',
      fgPct: '42.8%',
      threePct: '36.0%',
      ftPct: '84.0%',
    },
  },

  // ==========================================
  // SACRAMENTO KINGS (SAC)
  // ==========================================
  'Domantas Sabonis': {
    tacticalRole: 'Pívot All-NBA Titán del Rebote & Máquina Histórica de Triples-Dobles (Domas)',
    specialty: 'Rebotes en tráfico (líder de la NBA), pases de fantasía desde el poste alto, pantallas de granito y ganchos',
    playStyle: 'El sucesor moderno del juego total de su padre Arvydas Sabonis',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 11,
      teamName: 'Orlando Magic (Traspasado a Thunder)',
      teamAbbr: 'OKC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
      origin: 'Gonzaga Bulldogs / Lituania',
    },
    draft: '2016 · Pick #11 (1ª Ronda por Orlando Magic)',
    experience: '9 Temporadas (Thunder / Pacers / Kings)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'Gonzaga Bulldogs',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '11,00 mill. $',
        feeOrType: 'Draft de la NBA (Pick 11 / Traspaso Serge Ibaka)',
      },
      {
        season: '21/22',
        date: '08/02/2022',
        fromTeam: 'Indiana Pacers',
        fromTeamAbbr: 'IND',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/ind.png',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '75,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Tyrese Haliburton + Buddy Hield)',
      },
      {
        season: '23/24',
        date: '02/07/2023',
        fromTeam: 'Sacramento Kings',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '217,00 mill. $',
        feeOrType: 'Renegociación y Extensión Máxima (5 años / $217M)',
      },
    ],
    awards: [
      { icon: 'flame', name: '2x Máximo Reboteador de la NBA (Rebounding Leader)', count: 2, details: '2022-23 (12.3 rpp), 2023-24 (13.7 rpp)' },
      { icon: 'sparkles', name: 'Racha Histórica de 61 Dobles-Dobles Consecutivos', count: 1, details: '2023-24 (Récord histórico de la era moderna de la NBA)' },
      { icon: 'star', name: '3x NBA All-Star', count: 3, details: '2020, 2021, 2023' },
      { icon: 'albums', name: '2x 3er Equipo All-NBA', count: 2, details: '2023, 2024' },
      { icon: 'trophy', name: 'Campeón del NBA Skills Challenge', count: 1, details: '2021' },
      { icon: 'flame', name: 'Líder en Triples-Dobles de la NBA en 2023-24', count: 1, details: '26 Triples-Dobles en una temporada' },
    ],
    seasonAverages: {
      pts: '19.4',
      reb: '13.7',
      ast: '8.2',
      stl: '0.9',
      blk: '0.6',
      fgPct: '59.4%',
      threePct: '37.9%',
      ftPct: '70.4%',
    },
  },

  'Zach LaVine': {
    tacticalRole: 'Escolta Volador Superestrella, 2x Campeón de Mates & Oro Olímpico (Flight 8)',
    specialty: 'Mates de concurso desde el tiro libre, triples tras bote demoledores y anotación atlética fluida',
    playStyle: 'Uno de los mejores machacadores de todos los tiempos y francotirador de 25+ puntos',
    draftInfo: {
      year: 2014,
      round: 1,
      pick: 13,
      teamName: 'Minnesota Timberwolves',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'UCLA Bruins / Seattle, Washington',
    },
    draft: '2014 · Pick #13 (1ª Ronda por Minnesota Timberwolves)',
    experience: '11 Temporadas (Timberwolves / Bulls / Kings)',
    transfers: [
      {
        season: '14/15',
        date: '26/06/2014',
        fromTeam: 'UCLA Bruins',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '9,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13)',
      },
      {
        season: '17/18',
        date: '22/06/2017',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Chicago Bulls',
        toTeamAbbr: 'CHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        marketValue: '78,00 mill. $',
        feeOrType: 'Traspaso Jimmy Butler',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Chicago Bulls',
        fromTeamAbbr: 'CHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/chi.png',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '215,00 mill. $',
        feeOrType: 'Traspaso de Superestrella',
      },
    ],
    awards: [
      { icon: 'trophy', name: '2x Campeón Consecutivo del Concurso de Mates (Slam Dunk Contest)', count: 2, details: '2015, 2016 (Considerado el mejor de la historia moderna)' },
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'Tokio 2020' },
      { icon: 'star', name: '2x NBA All-Star', count: 2, details: '2021, 2022' },
      { icon: 'sparkles', name: 'MVP del Rising Stars Challenge', count: 1, details: '2016' },
      { icon: 'shield-checkmark', name: '2º Equipo NBA All-Rookie', count: 1, details: '2015' },
    ],
    seasonAverages: {
      pts: '22.8',
      reb: '4.8',
      ast: '4.2',
      stl: '0.9',
      blk: '0.3',
      fgPct: '48.5%',
      threePct: '39.0%',
      ftPct: '85.4%',
    },
  },

  'Ben Simmons': {
    tacticalRole: 'Base / Alero Alto Organizador & Defensor de Élite 1 al 5',
    specialty: 'Visión de pase en carrera, robos con envergadura de 2,14m y versatilidad defensiva total',
    playStyle: 'Base organizador puro de 2,08m con IQ defensivo de élite',
    draftInfo: {
      year: 2016,
      round: 1,
      pick: 1,
      teamName: 'Philadelphia 76ers',
      teamAbbr: 'PHI',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
      origin: 'LSU Tigers / Melbourne, Australia',
    },
    draft: '2016 · Pick #1 (1ª Ronda por Philadelphia 76ers — The Process)',
    experience: '8 Temporadas (76ers / Nets / Kings)',
    transfers: [
      {
        season: '16/17',
        date: '23/06/2016',
        fromTeam: 'LSU Tigers',
        toTeam: 'Philadelphia 76ers',
        toTeamAbbr: 'PHI',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        marketValue: '26,60 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1)',
      },
      {
        season: '21/22',
        date: '10/02/2022',
        fromTeam: 'Philadelphia 76ers',
        fromTeamAbbr: 'PHI',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phi.png',
        toTeam: 'Brooklyn Nets',
        toTeamAbbr: 'BKN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        marketValue: '177,00 mill. $',
        feeOrType: 'Mega-Traspaso James Harden',
      },
      {
        season: '24/25',
        date: '06/07/2024',
        fromTeam: 'Brooklyn Nets',
        fromTeamAbbr: 'BKN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/bkn.png',
        toTeam: 'Sacramento Kings',
        toTeamAbbr: 'SAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sac.png',
        marketValue: '40,00 mill. $',
        feeOrType: 'Traspaso de Base Creador',
      },
    ],
    awards: [
      { icon: 'ribbon', name: 'Rookie del Año de la NBA (ROTY)', count: 1, details: '2018' },
      { icon: 'star', name: '3x NBA All-Star', count: 3, details: '2019, 2020, 2021' },
      { icon: 'shield', name: '2x 1er Equipo NBA All-Defensive', count: 2, details: '2020, 2021 (Finalista al DPOY)' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 1, details: '2020' },
      { icon: 'flame', name: 'Líder en Robos de la NBA', count: 1, details: '2019-20 (2.1 robos por partido)' },
    ],
    seasonAverages: {
      pts: '7.8',
      reb: '7.0',
      ast: '6.5',
      stl: '1.2',
      blk: '0.6',
      fgPct: '58.1%',
      threePct: '0.0%',
      ftPct: '50.0%',
    },
  },
};
