const fs = require('fs');
const path = require('path');

const STAR_DOSSIERS = {
  'Victor Wembanyama': {
    tacticalRole: 'Pívot Generacional & Protector de Aro del Futuro (The Alien)',
    specialty: 'Envergadura de 2,44m, tapones imposibles, manejo de balón perimetral y triples',
    playStyle: 'Unicornio absoluto, ROTY unánime y futuro dominador de la NBA',
    draftInfo: {
      year: 2023,
      round: 1,
      pick: 1,
      teamName: 'San Antonio Spurs',
      teamAbbr: 'SAS',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
      origin: 'Metropolitans 92 (Francia)',
    },
    draft: '2023 · Pick #1 (1ª Ronda por San Antonio Spurs)',
    experience: '3 Temporadas (San Antonio Spurs)',
    transfers: [
      {
        season: '23/24',
        date: '22/06/2023',
        fromTeam: 'Metropolitans 92 (Francia)',
        toTeam: 'San Antonio Spurs',
        toTeamAbbr: 'SAS',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/sa.png',
        marketValue: '55,10 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — 4 años / $55.1M)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY Unánime)', count: 1, details: '2024 (San Antonio Spurs)' },
      { icon: 'shield', name: '1er Equipo All-Defensive de la NBA', count: 2, details: '2024 (Primer rookie de la historia en el 1er equipo), 2025' },
      { icon: 'flame', name: 'Líder en Tapones de la NBA', count: 2, details: '2024 (3.6 BLQ), 2025 (3.8 BLQ)' },
      { icon: 'star', name: 'NBA All-Star', count: 2, details: '2025, 2026' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 1, details: '2026' },
      { icon: 'medal', name: 'Medalla de Plata Olímpica (Francia)', count: 1, details: 'París 2024' },
    ],
    seasonAverages: {
      pts: '24.5',
      reb: '11.8',
      ast: '4.2',
      stl: '1.4',
      blk: '3.7',
      fgPct: '48.5%',
      threePct: '34.5%',
      ftPct: '81.2%',
    },
  },

  'Shai Gilgeous-Alexander': {
    tacticalRole: 'Base Anotador Imparable & Maestro de la Pintura (SGA)',
    specialty: 'Drive al aro, cambios de dirección, step-back en media distancia y robos de balón',
    playStyle: 'Anotador de élite en penetración, 2x 1er Equipo All-NBA y finalista al MVP',
    draftInfo: {
      year: 2018,
      round: 1,
      pick: 11,
      teamName: 'Charlotte Hornets (Traspasado a Clippers)',
      teamAbbr: 'LAC',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2018 · Pick #11 (1ª Ronda por Charlotte, traspasado a LA Clippers)',
    experience: '8 Temporadas (LA Clippers / Oklahoma City Thunder)',
    transfers: [
      {
        season: '18/19',
        date: '21/06/2018',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'LA Clippers',
        toTeamAbbr: 'LAC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        marketValue: '16,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 11 / 4 años / $16.9M)',
      },
      {
        season: '19/20',
        date: '10/07/2019',
        fromTeam: 'LA Clippers',
        fromTeamAbbr: 'LAC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/lac.png',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '80,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Paul George + 5 primeras rondas)',
      },
      {
        season: '22/23',
        date: '06/08/2021',
        fromTeam: 'Oklahoma City Thunder',
        fromTeamAbbr: 'OKC',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        toTeam: 'Oklahoma City Thunder',
        toTeamAbbr: 'OKC',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/okc.png',
        marketValue: '179,00 mill. $',
        feeOrType: 'Supermax Rookie Extension (5 años / $179M)',
      },
    ],
    awards: [
      { icon: 'ribbon', name: 'Finalista / 2º en Votaciones para MVP de la NBA', count: 2, details: '2024, 2025' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 3, details: '2023, 2024, 2025' },
      { icon: 'star', name: 'NBA All-Star', count: 3, details: '2023, 2024, 2025' },
      { icon: 'shield', name: '1er Equipo All-Defensive', count: 1, details: '2025 (Líder en robos de la NBA)' },
      { icon: 'medal', name: 'Medalla de Bronce en Mundial FIBA (Canadá)', count: 1, details: '2023 (MVP del Torneo y Clasificación Olímpica)' },
    ],
    seasonAverages: {
      pts: '30.1',
      reb: '5.5',
      ast: '6.2',
      stl: '2.0',
      blk: '0.9',
      fgPct: '53.5%',
      threePct: '35.3%',
      ftPct: '87.4%',
    },
  },

  'Anthony Edwards': {
    tacticalRole: 'Escolta Franquicia, Finalizador Explosivo & Líder (Ant-Man)',
    specialty: 'Mates estratosféricos, triples clutch tras drible y defensa física de perímetro',
    playStyle: 'Atleta superestrella, oro olímpico 2024 y cara de la liga',
    draftInfo: {
      year: 2020,
      round: 1,
      pick: 1,
      teamName: 'Minnesota Timberwolves',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'Georgia Bulldogs',
    },
    draft: '2020 · Pick #1 (1ª Ronda por Minnesota Timberwolves)',
    experience: '6 Temporadas (Minnesota Timberwolves)',
    transfers: [
      {
        season: '20/21',
        date: '18/11/2020',
        fromTeam: 'Georgia Bulldogs',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '44,20 mill. $',
        feeOrType: 'Draft de la NBA (Pick 1 / 4 años / $44.2M)',
      },
      {
        season: '24/25',
        date: '09/07/2023',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '260,00 mill. $',
        feeOrType: 'Designated Rookie Max Extension (5 años / $260M)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 1, details: 'París 2024 (Líder anotador de EE.UU.)' },
      { icon: 'star', name: 'NBA All-Star', count: 3, details: '2023, 2024, 2025' },
      { icon: 'albums', name: '2º Equipo All-NBA', count: 2, details: '2024, 2025' },
      { icon: 'shield-checkmark', name: 'NBA All-Rookie First Team', count: 1, details: '2021' },
      { icon: 'trophy', name: 'Campeón de Conferencia Oeste', count: 1, details: 'Finalista de Conferencia 2024' },
    ],
    seasonAverages: {
      pts: '27.8',
      reb: '5.8',
      ast: '5.4',
      stl: '1.4',
      blk: '0.6',
      fgPct: '47.2%',
      threePct: '37.8%',
      ftPct: '84.0%',
    },
  },

  'Karl-Anthony Towns': {
    tacticalRole: 'Pívot Tirador Generacional & Finalizador Exterior/Interior (KAT)',
    specialty: 'Tiro de tres puntos para hombres grandes, rebote y juego al poste',
    playStyle: 'El mejor pívot tirador de triples en la historia de la NBA',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 1,
      teamName: 'Minnesota Timberwolves',
      teamAbbr: 'MIN',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2015 · Pick #1 (1ª Ronda por Minnesota Timberwolves)',
    experience: '11 Temporadas (Minnesota Timberwolves / New York Knicks)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '25,70 mill. $',
        feeOrType: 'Draft de la NBA (Pick #1 — 4 años / $25.7M)',
      },
      {
        season: '19/20',
        date: '23/09/2018',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'Minnesota Timberwolves',
        toTeamAbbr: 'MIN',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        marketValue: '190,00 mill. $',
        feeOrType: 'Supermax Extension (5 años / $190M)',
      },
      {
        season: '24/25',
        date: '02/10/2024',
        fromTeam: 'Minnesota Timberwolves',
        fromTeamAbbr: 'MIN',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/min.png',
        toTeam: 'New York Knicks',
        toTeamAbbr: 'NYK',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/nyk.png',
        marketValue: '220,00 mill. $',
        feeOrType: 'Mega-Traspaso (por Julius Randle y Donte DiVincenzo)',
      },
    ],
    awards: [
      { icon: 'sparkles', name: 'Rookie del Año de la NBA (ROTY Unánime)', count: 1, details: '2016' },
      { icon: 'star', name: 'NBA All-Star', count: 4, details: '2018, 2019, 2022, 2024' },
      { icon: 'albums', name: '3er Equipo All-NBA', count: 2, details: '2018, 2022' },
      { icon: 'flame', name: 'Campeón del Concurso de Triples NBA', count: 1, details: '2022 (Primer pívot en ganarlo)' },
      { icon: 'trophy', name: 'Campeón del Skills Challenge NBA', count: 1, details: '2016' },
    ],
    seasonAverages: {
      pts: '22.9',
      reb: '10.8',
      ast: '3.1',
      stl: '0.7',
      blk: '1.3',
      fgPct: '52.4%',
      threePct: '41.6%',
      ftPct: '83.9%',
    },
  },

  'Devin Booker': {
    tacticalRole: 'Escolta Anotador Puro & Ejecutor de Media Distancia (Book)',
    specialty: 'Pull-up jumpers, footwork impecable, anotación en volumen y clutch',
    playStyle: 'Miembro del club de los 70 puntos y doble campeón olímpico',
    draftInfo: {
      year: 2015,
      round: 1,
      pick: 13,
      teamName: 'Phoenix Suns',
      teamAbbr: 'PHX',
      teamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
      origin: 'Kentucky Wildcats',
    },
    draft: '2015 · Pick #13 (1ª Ronda por Phoenix Suns)',
    experience: '11 Temporadas (Phoenix Suns)',
    transfers: [
      {
        season: '15/16',
        date: '25/06/2015',
        fromTeam: 'Kentucky Wildcats',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '9,90 mill. $',
        feeOrType: 'Draft de la NBA (Pick 13 / 4 años / $9.9M)',
      },
      {
        season: '19/20',
        date: '07/07/2018',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '158,00 mill. $',
        feeOrType: 'Extensión Máxima (5 años / $158M)',
      },
      {
        season: '24/25',
        date: '07/07/2022',
        fromTeam: 'Phoenix Suns',
        fromTeamAbbr: 'PHX',
        fromTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        toTeam: 'Phoenix Suns',
        toTeamAbbr: 'PHX',
        toTeamLogo: 'https://a.espncdn.com/i/teamlogos/nba/500/phx.png',
        marketValue: '224,00 mill. $',
        feeOrType: 'Supermax Extension (4 años / $224M)',
      },
    ],
    awards: [
      { icon: 'medal', name: 'Medalla de Oro Olímpica (Team USA)', count: 2, details: 'Tokio 2020, París 2024' },
      { icon: 'star', name: 'NBA All-Star', count: 4, details: '2020, 2021, 2022, 2024' },
      { icon: 'albums', name: '1er Equipo All-NBA', count: 1, details: '2022' },
      { icon: 'flame', name: 'Partido Histórico de 70 Puntos', count: 1, details: 'Boston TD Garden (24/03/2017)' },
      { icon: 'trophy', name: 'Campeón del Concurso de Triples NBA', count: 1, details: '2018' },
    ],
    seasonAverages: {
      pts: '27.1',
      reb: '4.5',
      ast: '6.9',
      stl: '0.9',
      blk: '0.4',
      fgPct: '49.2%',
      threePct: '36.4%',
      ftPct: '88.6%',
    },
  },
};

const filePath = path.resolve(__dirname, '../src/utils/playerDossier.ts');
let content = fs.readFileSync(filePath, 'utf8');

// Insert new star dossiers into DOSSIER_DATABASE
let insertionStr = '';
for (const [name, dossier] of Object.entries(STAR_DOSSIERS)) {
  if (!content.includes(`'${name}':`)) {
    insertionStr += `  '${name}': ${JSON.stringify(dossier, null, 2)},\n\n`;
  }
}

if (insertionStr.length > 0) {
  content = content.replace('const DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {', 'const DOSSIER_DATABASE: Record<string, Partial<PlayerDossier>> = {\n' + insertionStr);
  fs.writeFileSync(filePath, content, 'utf8');
  console.log('Successfully added star dossiers to playerDossier.ts');
} else {
  console.log('All star dossiers already present');
}
